### ISSUE TITLE
Cannot disable MongoDB logging

### ISSUE THREAD

**Issue by Ktar5** [tinylog-org/tinylog#101]
Hello,

I am using the following in my gradle build script
```gradle
compile group: 'org.tinylog', name: 'tinylog-api', version: '2.0.0-M4.2'
compile group: 'org.tinylog', name: 'tinylog-impl', version: '2.0.0-M4.2'
compile group: 'org.tinylog', name: 'jul-tinylog', version: '2.0.0-M4.2'
```

I am attempting to disable logging for MongoDB, because it is spammy as all hell, and I am so far unsuccessful.

Here is what logging looks like with "jul-tinylog" DISABLED
```
May 10, 2019 12:21:36 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Setting max election id to CENSORED from replica set CENSORED 
May 10, 2019 12:21:36 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Setting max set version to 1 from replica set primary CENSORED 
May 10, 2019 12:21:36 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Discovered replica set primary CENSORED
```

Here is what logging looks like with "jul-tinylog" enabled
```
24:48:795 JULLogger.log() [INFO]: Setting max election id to CENSORED
24:48:795 JULLogger.log() [INFO]: Setting max set version to 1 from CENSORED
24:48:795 JULLogger.log() [INFO]: Discovered replica set primary CENSORED
```

I'm not sure if this helps, but I've also tried using the slf4j bindings, which end up looking exactly like the JUL one except with SLF4JLogger.debug() in place of JULLogger.log()

As well, here is my configuration file
```
level@org.mongodb.driver = error

writerFile = file
writerFile.file = log.txt
writerFile.format = {date:mm:ss:SSS} {class-name}.{method}() [{level}]: {message}

writerConsole = console
writerConsole.format = {date:mm:ss:SSS} {class-name}.{method}() [{level}]: {message}
```

I would greatly appreciate details on removing the hundreds of messages that MongoDB spams from my console and log file.

Thank you!

**Comment by pmwmedia** [comment]
Just use the package name in your tinylog.properties: `level@com.mongodb = error`
