### ISSUE TITLE
rolling file: always write in the first file 

### ISSUE THREAD

**Issue by Nutriz** [tinylog-org/tinylog#103]
Hi.

One think I miss from my old log lib, is to have my more recent logs always in the first log file.

Hypothetic example:
```
#tinylog config
writer=rolling file
writer.file=/../logs.{count}.txt
writer.append=true
writer.backups=5
writer.policies=size: 1mb
writer.format={message}
```

- logs.0.txt <- more recent logs are always written here
- logs.1.txt <- when `logs.0.txt` reach the limit of 1mb, it is renamed into `logs.1.txt` and a new  `logs.0.txt` is created to continue to log in
- logs.2.txt <- previously `logs.1.txt`
- logs.3.txt <- previously `logs.2.txt`
- logs.4.txt <- previously `logs.3.txt`

This allows to work with log files much easy, like as getting only the last recents 500 lines of logs, or looping into log files without having to manage big consecutive numbers.

One concrete example where the current rolling file is difficult to work with:

I have to upload the logs in Hockeyapp when a crash happen, but the max file size is 200kb. So if I have this logs files it is not so complicate:
- logs.34.txt 1mb
- logs.35.txt 1mb
- logs.36.txt 580kb

I have to found the higher counter in my folder to get the more recent log file (logs.36.txt), and loop from the end of the file to get the last 200kb of logs, from 380kb to 580kb. Ok it's done.

But if i have this logs files, it start to be much difficult to handle:
- logs.34.txt 1mb
- logs.35.txt 1mb
- logs.36.txt 10kb

I have to found the higher counter in my folder to get the more recent log file (logs.36.txt), and loop from the end of the file to get the last 200kb of logs, but this one is only 10kb, so I write the 10kb of logs.36.txt. After I have to get the log file last-1 (logs.35.txt) and loop from the end of it and insert the 190kb of it in my log file (but before the last 10kb already appended) and finally send it with the crash.

With the behaviour describe at the start (more recent logs always written in file 0), this kind of work is much much easier to handle. Is it a possibility to include this kind of behavior in TinyLog ? :smiley:

Thanks in advance for your answer

**Comment by pmwmedia** [comment]
The rolling file writer of tinylog 1.x works exactly in way you describe. However, I have decided to change the behavior of the count policy to current one in tinylog 2.x for three reasons.

1. **Performance**: If tinylog always writes in the log file with the lowest number (= 0), all log files have to be renamed when the current log file is full. This can be slow, if you have an huge amount of log files.

2. **Stability:** If one of the log files cannot be renamed at rollover, how can the rolling file writer continue logging without loosing existing log files? This can easily happen on Windows, when an editor locks a file.

3. **Consistency:** If all log files are renamed regularly, it can be difficult to find a log entry again. For example, if you ask a colleague to look for a NullPointerException in log42.txt, these log file will probably have another file name, when your colleague wants to open it later.
