### ISSUE TITLE
Feature Request: Allow Unix Timestamp in Format Pattern

### ISSUE THREAD

**Issue by ryanthon** [tinylog-org/tinylog#104]
The {date} token only allows formatting dates to human-readable String formats (e.g. "May 5, 2019 11:49").

I need to write to my logs in JSON format, one entry per line, and I need a way of writing a plain unix timestamp in the pattern. I was thinking something like {timestamp} or {timestamp: seconds}, {timestamp: milliseconds}, etc.
Or even just extending the DateToken to allow something like {date: timestampSeconds}, etc (this one's not the most elegant, but you get the idea).

This should be very easy to do, I don't mind submitting a pull request for it if proposal is accepted.

**Comment by pmwmedia** [comment]
I like your idea of {timestamp} and {timestamp: seconds}.

A pull request is welcome :-)

**Comment by ryanthon** [comment]
Just finished, added PR #105 

Wasn't sure if you wanted to include support for microseconds as well, so I just allowed for seconds, and default to milliseconds.

**Comment by pmwmedia** [comment]
@ryanthon Thank you very much for your great and complete PR :-)
