### ISSUE TITLE
LOG4J2 to SLF4J + SLF4J binding wrong class name detected

### ISSUE THREAD

**Issue by teoincontatto** [tinylog-org/tinylog#106]
Hello,

Seems like using [log4j2-api](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api/2.11.2) together with [log4j-slf4j-impl](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-slf4j-impl/2.11.2) and [slf4j-tinylog](https://mvnrepository.com/artifact/org.tinylog/slf4j-tinylog) is failing in detecting correct class name in `RuntimeProvider.getCallerClassName(int)` due to different depth in the call stack.

A naive solution here for this kind of problems would be to add a Java system property for `org.tinylog.slf4j.TinylogLogger.STACKTRACE_DEPTH` that default to current value (`2`). This solution can be improved to support code that uses directly slf4j api or use it indirectly through log4j2 (or any other log library that can be bridged to slf4j) by converting `STACKTRACE_DEPTH` into a static map (for example `Map<String,Integer>`). The map will then allow to assign different depth depending on the name prefix configured by Java system properties (and/or configuration).

**Comment by pmwmedia** [comment]
If I understand your use case correctly, you want to output log entries issued by the Log4j API via SLF4J by tinylog. In this case, you need [log4j-to-slf4j](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-to-slf4j/2.11.2) instead of [log4j-slf4j-impl](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-slf4j-impl/2.11.2).

Example program:

```java
import org.slf4j.LoggerFactory;
import org.tinylog.Logger;

public class Application {

	public static void main(final String[] args) {
		Logger.info("Hello from tinylog!");
		LoggerFactory.getLogger(Application.class).info("Hello from SLF4J!");
	}

}
```
Dependencies:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.tinylog</groupId>
	<artifactId>sample</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<dependencies>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.11.2</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-to-slf4j</artifactId>
			<version>2.11.2</version>
		</dependency>
		<dependency>
			<groupId>org.tinylog</groupId>
			<artifactId>slf4j-tinylog</artifactId>
			<version>2.0.0-M4.3</version>
		</dependency>
		<dependency>
			<groupId>org.tinylog</groupId>
			<artifactId>tinylog-impl</artifactId>
			<version>2.0.0-M4.3</version>
		</dependency>
	</dependencies>
</project>
```

Output:

```
2019-06-04 20:09:28 [main] Application.main()
INFO: Hello from tinylog!
2019-06-04 20:09:28 [main] Application.main()
INFO: Hello from SLF4J!
```

The class name is correct :-)

**Comment by pmwmedia** [comment]
@teoincontatto Does it solve your problem? Can the issue be closed?

**Comment by pmwmedia** [comment]
Closed due to missing response. Can be reopened later if required.
