### ISSUE TITLE
tinylog init error when dynamic add jar

### ISSUE THREAD

**Issue by twogoods** [tinylog-org/tinylog#107]
dynamic add tinglog v2,  use `new URLClassLoader('urls for tinylog.jar', extClassLoader);`

in `org.tinylog.provider.ProviderRegistry.loadLoggingProvider()`

`ServiceLoader<LoggingProvider> loader = new ServiceLoader<>(LoggingProvider.class);` 
 `LoggingProvider.class`is load by URLClassLoader

In constructor:
```
public ServiceLoader(final Class<? extends T> service, final Class<?>... argumentTypes) {
	this.service = service; //load by URLClassLoader
	this.argumentTypes = argumentTypes;
	this.classLoader = Thread.currentThread().getContextClassLoader(); // Launcher.AppClassLoader
        // this classLoader can not load META-INF/services/...
	this.classes = loadClasses(classLoader, service);
}

private T createInstance(final String className, final Object... arguments) {
     try {
	Class<?> implementation = Class.forName(className, false, classLoader);
        // service load by URLClassLoader ,implementation load by AppClassLoader ，never be true
	if (service.isAssignableFrom(implementation)) {
	     return (T) implementation.getDeclaredConstructor(argumentTypes).newInstance(arguments);
	}
	...
}
```
So replace `Thread.currentThread().getContextClassLoader()` to `service.getClassLoader()` ? Is there any other problem?

**Comment by pmwmedia** [comment]
@twogoods Could you provide some details about your environment. What VM are you using? Why do you load the tinylog.jar dynamically at runtime?

**Comment by twogoods** [comment]
@pmwmedia I am developing a javaagent project ,the javaagent will enhance user's java program, like springboot，so javaagent will add many jar to user's program dynamically. In this case may need change to `service.getClassLoader()`

**Comment by pmwmedia** [comment]
Would this fix it for you?

```java
ClassLoader originalClassLoader = Thread.currentThread().getContextClassLoader();
try {
    // Set any class loader you need
    Thread.currentThread().setContextClassLoader(getClass().getClassLoader()); 
    new URLClassLoader('urls for tinylog.jar', extClassLoader);
} finally {
    Thread.currentThread().setContextClassLoader(originalClassLoader);
}
```

**Comment by pmwmedia** [comment]
@twogoods Can the issue be closed?

**Comment by twogoods** [comment]
@pmwmedia It work,  but i think framework adapt this case is better.
And shared file writer can support rolling policy?

**Comment by pmwmedia** [comment]
`Thread.currentThread().getContextClassLoader()` works for all use cases I know yet. The only known exception is the Java agent example you have posted here. Theoretically, tinylog could follow the way of Apache Log4j 2 to try two different class loaders (see [Loader.java](https://github.com/apache/logging-log4j2/blob/master/log4j-core/src/main/java/org/apache/logging/log4j/core/util/Loader.java#L91)). However, I think that this is a very specific use case that doesn't apply for many other users.

The shared file writer cannot support rolling policies. The overhead of synchronizing policies over multiple JVM instances would be too huge. I recommend to use a rolling file writer with a `{pid}` placeholder.
