### ISSUE TITLE
[Question]  writer.format {class-name} and {method} with obfuscator (proguard)

### ISSUE THREAD

**Issue by Nutriz** [tinylog-org/tinylog#108]
Hi,

We use Proguard in our Android App for the release apk and we have problem to use the writer.format masks `{class-name}` and `{method}`, because of the Obfuscation pass, log like `MainActivity.onCreate()` are transformed in a form of `a.b()`.

I know this is normal but I ask if it's a way to enjoy the `{class-name}` and `{method}` masks with an obfuscator ? These mask are really useful and we have already switched to tinylog and refactored all our base code to remove class names in code to use this mask feature.

**Comment by pmwmedia** [comment]
You can configure Proguard to keep all class names and method names.

I don't use Proguard, but according to their [manual](https://www.guardsquare.com/en/products/proguard/manual/examples), this should work:

```
-keep class * {
    <methods>;
}
```

**Comment by Nutriz** [comment]
Yes but with this, we are loosing a big part of the obfuscator interest (no more class and method name obfuscated). I don't know if another solution is possible...

**Comment by pmwmedia** [comment]
Obfuscating applies also to tinylog. If not, Proguard would be a bad obfuscator and wouldn't help at all. Personally I don't think that obfuscating does really help to protect source code. However that is a company decision. For tinylog, you could create [tagged loggers](https://tinylog.org/v2/configuration/#tags) for having at least some tags for categorizing log entries.
