### ISSUE TITLE
Android Implementation

### ISSUE THREAD

**Issue by lfom** [tinylog-org/tinylog#109]
Hello! First, thanks for Tinylog, it is great! But I am having a few issues using it on Android... I am running Android Studio 3.4.1, project is built using Gradle 5.4 and plugin version 3.4.1, with the latest Tinylog:
> implementation 'org.tinylog:tinylog-api:2.0.0-M4.3'
> implementation 'org.tinylog:tinylog-impl:2.0.0-M4.3'

I have searched a lot, bit I could not fix these issues:

1. I get this error when running the app:

`W/System.err: LOGGER WARN: No logging framework implementation found in classpath. Add tinylog-impl.jar for outputting log entries.`

I have found an old issue on GitHub with a similar error, but it should have been fixed, haven't it? Maybe because of this I have the other two problems bellow...

2. Tinylog only works when I set the build to debugable=true, is that normal?

3. I cannot use formatting for Logcat writer, is it normal too?

Thanks again! Regards,
LFOM

**Comment by pmwmedia** [comment]
Could you provide a fully working minimal sample project that demonstrate your issues? I would like to analyze these issues as I'm close to release the first major version of tinylog 2. I want to ensure that there are no severe bugs before releasing.

If tinylog can't find "tinylog-impl.jar", logging via tinylog including it's Logcat writer won't work at all. So, the first issue is the one to solve.

There are no known open bugs about using tinylog on Android. Could you link the issue you found?

**Comment by lfom** [comment]
Hi. Thank you for your reply. You mean the old bug with the same error? It wasn't on Android, just the error message was the same (issue #96). The project I am working on is quite big (AmazMod) but as soon as I can I will try to add Tinylog to another smaller app and publish it on GitHub for testing.

**Comment by pmwmedia** [comment]
Issue #96 is fixed in the tinylog version you are using.

The best way would be, if you could create a new minimalist Android project that does nothing else than using tinylog and demonstrating the issue: `W/System.err: LOGGER WARN: No logging framework implementation found in classpath. Add tinylog-impl.jar for outputting log entries.`

**Comment by lfom** [comment]
Hello, again. Maybe this helps:

> 06-28 19:51:13.628 18471-18471/? W/ActivityThread: ClassLoader.getResources: The class loader returned by Thread.getContextClassLoader() may fail for processes that host multiple applications. You should explicitly specify a context class loader. For example: Thread.setContextClassLoader(getClass().getClassLoader());
> 06-28 19:51:13.640 18471-18471/? W/art: Failed to open zip archive '/system/framework/telephony-common.jar': I/O Error
> 06-28 19:51:13.640 18471-18471/? W/art: Failed to open zip archive '/system/framework/ims-common.jar': I/O Error
> 06-28 19:51:13.640 18471-18471/? W/art: Failed to open zip archive '/system/framework/mms-common.jar': I/O Error
> 06-28 19:51:13.661 18471-18471/? W/art: Failed to open zip archive '/system/framework/telephony-common.jar': I/O Error
> 06-28 19:51:13.661 18471-18471/? W/art: Failed to open zip archive '/system/framework/ims-common.jar': I/O Error
> 06-28 19:51:13.661 18471-18471/? W/art: Failed to open zip archive '/system/framework/mms-common.jar': I/O Error
> **06-28 19:51:13.674 18471-18471/? W/System.err: LOGGER WARN: No logging framework implementation found in classpath. Add tinylog-impl.jar for outputting log entries.**
> 06-28 19:51:13.895 18471-18471/? I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
> 06-28 19:51:13.896 18471-18471/? I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>

I am using AndroidX libs in Android Studio, gradle.properties has the code below:
`android.useAndroidX=true`
`android.enableJetifier=true`

EDIT: I think I got it working... About the error: the app has one service that runs as a plugin of a system process (a widget for a SpringBoard server), and when we started to use Tinylog many of the system processes also were logged via Tinylog (I can identify them because no all Tinylog entries have the format "date time/com.app.name", what was bothering me so I wanted to change the configuration) and it seems that there is some error in a system process and it displays the log above... Does it make sense?

About the configuration, I am using Configuration.set when the app starts, and you it must be the first thing done, right? If Logger is used before the configuration it goes crazy, maybe it should be stated somewhere in the documentation, not everyone uses a properties file, specially on Android. 

Thanks again for your help and this nice tool. Regards.

**Comment by pmwmedia** [comment]
You are welcome!

**Comment by pmwmedia** [comment]
@lfom Where do you initialize tinylog's configuration now? What is your entry point before any other class can log?

**Comment by lfom** [comment]
I have added the call to configuration in `attachBaseContext` of the Application class, and it it working great now. Thanks again.

**Comment by pmwmedia** [comment]
@lfom Thanks for your feedback!

**Comment by lfom** [comment]
Just confirming it: the error about `tinylog-impl.jar` was really the use of Tinylog in the widget, what uses a special context, what prevented Tinylog to work in that class. I have replaced it with android.util.Log just in the widget and I don't get the message anymore.
