### ISSUE TITLE
Include an automatic module name in the manifest

### ISSUE THREAD

**Issue by frozen-chameleon** [tinylog-org/tinylog#110]
Adding an automatic-module-name manifest entry will make it easier to use tinylog in a modular java application without making tinylog a modular application itself.

**Comment by pmwmedia** [comment]
@frozen-chameleon Could you create a pull-request? I would publish it in Version 2.0.0-RC2.

**Comment by frozen-chameleon** [comment]
Unfortunately I do not have much experience with maven. I managed to add the entries by editing the pom.xml of each module.
```
<plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-jar-plugin</artifactId>
   <configuration>
      <archive>
         <manifestEntries>
            <Automatic-Module-Name>the.module.name</Automatic-Module-Name>
         </manifestEntries>
      </archive>
   </configuration>
</plugin>
```
A unique automatic-module-name has to be provided for each module. The naming depends mainly on how you want to structure the project. 

Some ideas:
tinylog-api => org.tinylog / org.tinylog.base / org.tinylog.core / org.tinylog.api
tinylog-api-kotlin => org.tinylog.kotlin
tinylog-impl => org.tinylog.impl / org.tinylog.simple

**Comment by pmwmedia** [comment]
Thank you for your suggestion!

I prefer the following module names:

tinylog-api => org.tinylog.api
tinylog-api-kotlin => org.tinylog.api.kotlin
jul-tinylog => org.tinylog.api.jul
tinylog-impl => org.tinylog.impl
tinylog-jul => org.tinylog.adapter.jul

**Comment by pmwmedia** [comment]
I have added Automatic-Module-Name to all manifest files.

@frozen-chameleon Can you test them, if they work as expected in your modular application?

**tinylog**

[tinylog-2.0-SNAPSHOT.zip](https://github.com/pmwmedia/tinylog/files/3393934/tinylog-2.0-SNAPSHOT.zip)
[tinylog-kotlin-2.0-SNAPSHOT.zip](https://github.com/pmwmedia/tinylog/files/3393937/tinylog-kotlin-2.0-SNAPSHOT.zip)
[tinylog-scala-2.0-SNAPSHOT.zip](https://github.com/pmwmedia/tinylog/files/3393938/tinylog-scala-2.0-SNAPSHOT.zip)

**Third-Party Logging APIs**

[slf4j-tinylog-2.0-SNAPSHOT.zip](https://github.com/pmwmedia/tinylog/files/3393932/slf4j-tinylog-2.0-SNAPSHOT.zip)
[tinylog1.3-api-2.0-SNAPSHOT.zip](https://github.com/pmwmedia/tinylog/files/3393933/tinylog1.3-api-2.0-SNAPSHOT.zip)
[jboss-tinylog-2.0-SNAPSHOT.zip](https://github.com/pmwmedia/tinylog/files/3393939/jboss-tinylog-2.0-SNAPSHOT.zip)
[jcl-tinylog-2.0-SNAPSHOT.zip](https://github.com/pmwmedia/tinylog/files/3393940/jcl-tinylog-2.0-SNAPSHOT.zip)
[jul-tinylog-2.0-SNAPSHOT.zip](https://github.com/pmwmedia/tinylog/files/3393941/jul-tinylog-2.0-SNAPSHOT.zip)
[log4j1.2-api-2.0-SNAPSHOT.zip](https://github.com/pmwmedia/tinylog/files/3393942/log4j1.2-api-2.0-SNAPSHOT.zip)

**Web and Application Servers**

[tinylog-jboss-2.0-SNAPSHOT.zip](https://github.com/pmwmedia/tinylog/files/3393935/tinylog-jboss-2.0-SNAPSHOT.zip)
[tinylog-jul-2.0-SNAPSHOT.zip](https://github.com/pmwmedia/tinylog/files/3393936/tinylog-jul-2.0-SNAPSHOT.zip)

**Comment by frozen-chameleon** [comment]
I tested `tinylog-2.0-SNAPSHOT.zip` and `jul-tinylog-2.0-SNAPSHOT.zip` and `slf4j-tinylog-2.0-SNAPSHOT.zip`. Everything is working fine in my project when I add `requires org.tinylog.api;` in `module-info.java`.

As a side node: Windows Defender flagged tinylog-2.0, tinylog-kotlin-2.0 and tinylog-scala-2.0  snapshots as a virus (Trojan:Java/Tisifi.C). The flagged file is `tinylog-impl-2.0-SNAPSHOT-javadoc.jar`. Looks like it is a false positive according to the [virustotal](https://www.virustotal.com/gui/file/3596a9da9a79ca5d50830c7954a2e8222e4e367d977268e7390b43d4224c15ef/detection) report.

**Comment by pmwmedia** [comment]
@frozen-chameleon Thank you for testing! Yes, that is a false positive that Windows Defender likes to report sometimes for unknown JAR files for any reason. I received it also for JARs of other projects in the past. As soon as Windows Defender has scanned such a JAR file on multiple but different PC, it will not be reported anymore.
