### ISSUE TITLE
feature request: default values for environment variables in config file

### ISSUE THREAD

**Issue by simonsilvalauinger** [tinylog-org/tinylog#112]
Hi,
I request a simple feature which could be useful.
At the moment it's possible to use environment variables in the config file. But if I use them, e.g. for the log level, I can not set a default value for unset environment variables. Instead I get an error message at application start that tells me that the environment variable could not be found and that the given key is not a valid value.
It would be amazing if this little feature could be added.

Thank you
Simon

**Comment by pmwmedia** [comment]
Thank you for your suggestion! I like you your idea :)

I could imagine `$(NAME:DEFAULT}` as syntax for environment variables, and `#(NAME:DEFAULT}` for system properties. However, the colon and default value should be optionally.

@simonsilvalauinger Could you provide a pull request?
