### ISSUE TITLE
Benchmarks for Log4j and Logback do not use buffering.

### ISSUE THREAD

**Issue by rgoers** [tinylog-org/tinylog#113]
The vast majority of users will use buffering on their files as writing is extremely slow otherwise.

**Comment by pmwmedia** [comment]
The benchmarks support buffering for Log4j and Logback:

https://github.com/pmwmedia/tinylog/blob/v2.0/benchmarks/src/main/java/org/tinylog/benchmarks/logging/Log4j1Benchmark.java#L134

https://github.com/pmwmedia/tinylog/blob/v2.0/benchmarks/src/main/java/org/tinylog/benchmarks/logging/Log4j2Benchmark.java#L108

https://github.com/pmwmedia/tinylog/blob/v2.0/benchmarks/src/main/java/org/tinylog/benchmarks/logging/LogbackBenchmark.java#L161

**Comment by rgoers** [comment]
Unless I misunderstand, these only support buffering when using asynchronous logging.  Buffering should not be related to async logging.

**Comment by pmwmedia** [comment]
You are right, I have published only a synchronous unbuffered (typical development environment) and an asynchronous buffered benchmark (typical production environment) on https://tinylog.org/v2/benchmark/. I know that there also many other common configurations. However, I don't want to overflow the benchmark page. A synchronous buffered logging will be between the both published benchmark and change not much about the order.

I have published the benchmark program as open source and have made is parameterizable to ensure that everybody can benchmark also custom settings.

**Comment by rgoers** [comment]
Is tinylog's synchronous benchmark using unbuffered i/o? If not then you are comparing apples to oranges.

**Comment by pmwmedia** [comment]
All logging frameworks including tinylog uses unbuffered i/o in the synchronous benchmark (yellow bars) and buffered i/o in the asynchronous benchmark (blue bars). For me, this looks like fair and same conditions for all of them. Why do you think this is like comparing apples to oranges?
