### ISSUE TITLE
Problem with Rolling File Writer behavior

### ISSUE THREAD

**Issue by Cyb0rk** [tinylog-org/tinylog#116]
Hi there,

I have an Issue with the Rolling File Write behavior.

In Tinylog 1.x the files get created by this schema if I setup 10MB filesize and 10 backups:

```
logfile.txt
logfile.1.txt
logfile.2.txt
[...]
logfile.10.txt
```

Tinylog 2.x creates the files via the following schema with the same settings:

```
logfile.0.txt (deleted)
logfile.1.txt (deleted)
logfile.2.txt (deleted)
[...]
logfile.50.txt (deleted)
logfile.51.txt
[...]
logfile.60.txt
```

In Tinylog 1.x I use this settings:

```
Configurator.defaultConfig()
  .formatPattern("{date:yyyy-MM-dd HH:mm:ss} [{thread}] {class}.{method}()\\t{level}: {message}")
  .writer(new RollingFileWriter("logs/aster_log.txt", 10, new CountLabeler(), new SizePolicy(10000 * 1024)))
  .activate();
```

in Tinylog 2.x I use this settings:

```
writer          = rolling file
writer.format   = {date:yyyy-MM-dd HH:mm:ss} [{thread}] {class}.{method} {level}: {message}
writer.file     = logs/APPNAME_log.{count}.txt
writer.charset  = UTF-8
writer.policies = size: 10mb
writer.backups  = 10
```

Could it be possible to change to 1.X behavior? This seems to be a more compatible option to Linux logrotate and is way more logical.

**Comment by pmwmedia** [comment]
You can find the reasons for the change here: https://github.com/pmwmedia/tinylog/issues/103#issuecomment-495292048

However, I could imagine to make the count placeholder configurable to get the old behavior if really needed.

**Comment by Cyb0rk** [comment]
Hello there,

if you could add a switch like "logrotate behavior" that would be greate. Otherwise I'll just switch to rotate logfiles via logrotate.

But I won't switch from tinylog to any other library. Tinylog is really great and with its small footprint and simple configuration it fits all of my needs :)

Great job with tinylog!

**Comment by winooxx** [comment]
The backup naming behaviour that TinyLog v1 does is far more intuitive than v2, I agree with [#116( issue comment )](https://github.com/pmwmedia/tinylog/issues/116#issuecomment-518298776). TinyLog is really simple enough to use and fits all my needs, except this little change on v2 :). Thank you for creating such a great logging framework.

**Comment by pmwmedia** [comment]
Close in favor of #149
