### ISSUE TITLE
Problem using two policies. (daily and size)

### ISSUE THREAD

**Issue by pedroguialves** [tinylog-org/tinylog#117]
I'm trying to use two policies at tinylog.properties :
`tinylog.writer.policies = size: 1MB, daily`
however just **size** policy is working.

**Obs** : When I try to use just the daily policy it is working.

My question is know if is possilble work with two policies and know if i am doing something wrong.

Thanks.

**Comment by pmwmedia** [comment]
It should be possible to use to use multiple policies for the rolling file writer. I will try if I can reproduce your issue with tinylog 1.3.6.

@pedroguialves Could you provide your whole tinylog configuration just for any case?

**Comment by pedroguialves** [comment]
i'm sending whole my configurations.

Thank you @pmwmedia 

```
tinylog.writer = rollingfile
tinylog.writer.filename = log/log.log 
tinylog.level = warning
tinylog.writer.backups = 5
tinylog.writer.label = timestamp
tinylog.writer.policies = size: 1MB, daily
tinylog.writingthread = true
tinylog.writingthread.observe = null
tinylog.writingthread.priority = 1
```

**Comment by pmwmedia** [comment]
I have tested your configuration and daily policy works even in combination with size policy correctly.

Java Application

```java
package my.example;

import org.pmw.tinylog.Logger;

public class Application {

	public static void main(String[] args) throws InterruptedException {
		for (int i = 0; ; ++i) {
			Logger.warn("Turn {}", i);
			Thread.sleep(60 * 1000);
		}
	}

}
```

Configuration

```properties
tinylog.writer = rollingfile
tinylog.writer.filename = log/log.log 
tinylog.level = warning
tinylog.writer.backups = 5
tinylog.writer.label = timestamp
tinylog.writer.policies = size: 1MB, daily
tinylog.writingthread = true
tinylog.writingthread.observe = null
tinylog.writingthread.priority = 1
```

Generated log files

[log.2019-08-16 22-48-14.log](https://github.com/pmwmedia/tinylog/files/3511399/log.2019-08-16.22-48-14.log)
[log.2019-08-17 00-00-14.log](https://github.com/pmwmedia/tinylog/files/3511400/log.2019-08-17.00-00-14.log)

**Comment by pmwmedia** [comment]
I close this issue due to no response within in a month. If required, the issue can be reopened again at any time.
