### ISSUE TITLE
Support for SLF4J 2.0

### ISSUE THREAD

**Issue by mikehearn** [tinylog-org/tinylog#119]
In https://github.com/pmwmedia/tinylog/issues/85 I requested support for the SLF4J 1.8 which does Jigsaw. It was closed as SLF4J 1.8 disappeared, but now it's back as SLF4J 2.0

It'd still be good to have support for this!

**Comment by pmwmedia** [comment]
Is the API compatible with SLF4J 1.7? Would you be able to provide a pull request?

**Comment by mikehearn** [comment]
I think it is, yes.

If I find time I'll take a look.

**Comment by pmwmedia** [comment]
Fixed by @f4lco in #199

**Comment by mikehearn** [comment]
Perfect timing guys, I'm just starting a new project and was starting to think about how I wanted logging done. Great to see TinyLog 2 is thriving! Thanks for the excellent work. I'll try it out now for this project.
