### ISSUE TITLE
Service implementation 'x' not found when extending Writer

### ISSUE THREAD

**Issue by maxnz** [tinylog-org/tinylog#120]
I'm trying to extend tinylog to add a writer that writes to a socket. I've followed the documentation but I get `LOGGER ERROR: Service implementation 'socket' not found`
<img width="704" alt="TinyLog output" src="https://user-images.githubusercontent.com/16338288/64837736-8f362d00-d5b5-11e9-887e-e870bd980e88.png">

The program works perfectly fine other than not writing logs to the right place.

Writer is defined here: [SocketWriter.kt](https://github.com/AnimatedLEDStrip/AnimatedLEDStripServer/blob/v0.4/src/main/java/animatedledstrip/server/SocketWriter.kt)
Services file is here: [org.tinylog.writers.Writer](https://github.com/AnimatedLEDStrip/AnimatedLEDStripServer/blob/v0.4/src/main/resources/META-INF/services/org.tinylog.writers.Writer)
Properties file is here: [tinylog.properties](https://github.com/AnimatedLEDStrip/AnimatedLEDStripServer/blob/v0.4/src/main/resources/tinylog.properties) (parent library here: [tinylog.properties](https://github.com/AnimatedLEDStrip/AnimatedLEDStrip/blob/v0.4/src/main/resources/tinylog.properties))

Is there something I'm missing?

**Comment by pmwmedia** [comment]
@maxnz I will take a look! Probably, Kotlin doesn't generate a compatible constructor.

**Comment by maxnz** [comment]
It looks like you may be right - I changed the constructor to use `java.util.Map` instead of the Kotlin `Map` and I don't get the error message anymore. I still am not getting any indication that it is being used though.

**Comment by pmwmedia** [comment]
Your application doesn't issue many log entries with severity level info and higher, but there are many trace log entries. Therefore, I suggest to activate trace log entries.

However, your SocketWriter.kt works on my machine:

```kotlin
fun main() {
	Logger.info { "Hello World!" }
}
```

tinylog.properties

```
writer = socket
writer.format = {{level}:|min-size=8} {message}
writer.level = trace
```

Output:

```
Hello World!
```

My JAR file: [animatedledstrip-server-0.4-SNAPSHOT-jar-with-dependencies.jar.zip](https://github.com/pmwmedia/tinylog/files/3612084/animatedledstrip-server-0.4-SNAPSHOT-jar-with-dependencies.jar.zip)
Execute: java -jar animatedledstrip-server-0.4-SNAPSHOT-jar-with-dependencies.jar

**Comment by maxnz** [comment]
Looks like it's working now. Not sure what I changed to make it work. I made a lot of changes trying to fix it and then after it worked I reverted them and it still works. 🤷‍♂ 

It might be a good idea to add a note to the documentation about using `java.util.Map` instead of `Map` when using Kotlin.
