### ISSUE TITLE
INFO level is getting written in DEBUG level file

### ISSUE THREAD

**Issue by sapandang** [tinylog-org/tinylog#121]
Hi I have two file writer in `tinylog.properties`
```
writer4 = file
writer4.level = debug
writer4.format = {date: HH:mm:ss.SSS} {level} {message}
writer4.file = debug.txt

writer = file
writer.format = {date: HH:mm:ss.SSS} {level} : {message}
writer.file = info.txt
writer.level = info
```
using  `Logger.info("registering task ");` outputs to **debug.txt** as well as **info.txt**
am I missing something.
*****
##### using
```
name: 'tinylog-impl', version: '2.0.0'
name: 'tinylog-api', version: '2.0.0'
```

**Comment by pmwmedia** [comment]
With `writer.level`, you define the minimum severity level. That you see also info log entries in your **debug.txt** shows that tinylog works as designed. What is your use case for only writing debug log entries to a log file? I think that debug log entries are only useful in context with info, warning, and error log entries.

**Comment by sapandang** [comment]
Thanks for info. I wanted to use tinyLogger to log reponses to file.
Using `Tags` solves the problem.
