### ISSUE TITLE
Configuration#set doesn't seem to work

### ISSUE THREAD

**Issue by dzikoysk** [tinylog-org/tinylog#123]
Hey,

If I'll try to set property using the `Configuration` class, it just does not affect logging. It looks like problem with the implementation, because if I set this property using the `System.setProperty`, everything works.

![obraz](https://user-images.githubusercontent.com/4235722/67896442-a8426f80-fb5c-11e9-8160-ee5a2cc2d8bb.png)

tinylog version: 2.0.0

**Comment by dzikoysk** [comment]
Oh, my bad, I've checked the implementation and I found that `Configuration.set` does not resolve properties with `tinylog` prefix. I think it could be a good idea to make a note in docs/website about it. It's logical that the prefix here is unnecessary, but if you read examples, it may not be so obvious 😅 

![obraz](https://user-images.githubusercontent.com/4235722/67945391-10399a00-fbdf-11e9-939f-40fcf8ab0e9f.png)

**Comment by pmwmedia** [comment]
I have precise it in the documentation. Thank you for your hint :-)
