### ISSUE TITLE
Tinylog usage in Android project

### ISSUE THREAD

**Issue by Kameswari** [tinylog-org/tinylog#124]
Hi,

I am trying to use Tinylog library for my Android project. I have added the dependencies in build.gradle and I have created the tinylog.properties file under app\src\main\resources folder with the below properties

writer          = rolling file
writer.format   = {date:yyyy-MM-dd HH:mm:ss} {class}.{method} {level}: {message}
writer.file     = logs/TINY_log.{count}.txt
writer.charset  = UTF-8
writer.policies = size: 1mb
writer.backups  = 2
I just added Logger.info("Test message"); line in my activity class

I have below questions regarding this.
1. Where the log file is being created? 
2. Can I send the log file over email from my app?
3. is the .properties file has been placed in correct path?

Please help to resolve these. Thanks

**Comment by pmwmedia** [comment]
1. Relative paths are not really predictable on Android. I would suggest to point to the files dir of your app `/data/data/[your app package]/files/TINY_log.{count}.txt`.

2. tinylog doesn't have any integrated email support. However, you can implement sending emails in your app by yourself of course. I personally would implement a web service that accepts logs and let the app sending your logs directly to this web service.

3. Yes, the correct path for `tinylog.properties` is `src/main/resources`.

**Comment by Kameswari** [comment]
@pmwmedia Thanks for the reply.
As per your point1, the file will be stored in internal storage of the device. But, in order to email that file, I have to store it external storage(sdcard) only since it should be accessible to email app which is outside of my app.

And the path of external storage is not consistent across all devices. Is there any way to set the path dynamically?

**Comment by pmwmedia** [comment]
Yes. you can set the path dynamically. I suggest to use system properties for this purpose. In `tinylog.properties` you can configure `#{logs.folder}/TINY_log.{count}.txt` as target log file. At startup of your app, you can set `logs.folder` dynamically as system property.

For example:
```java
File folder = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS);
System.setProperty("logs.folder", folder.getAbsolutePath());
```

Important is that you set the system property before any log entries are issued. I suggest to set `logs.folder` in the `onCreate()` method of your main activity.

**Comment by Kameswari** [comment]
@pmwmedia Thanks for the quick responses. This works well. I will continue to use this.

**Comment by danielwilson1702** [comment]
Hi @pmwmedia , I'm trying to get this working with basic internal storage but it doesn't appear to be creating a file. Any ideas? I am using an emulator so maybe that is an issue.

res\tinylog.properties
```
writer = rolling file
writer.format = {date:yyyy-MM-dd HH:mm:ss} {class}.{method} {level}: {message}
writer.file = /data/data/com.sp.myapp/files/tiny_log_{count}.txt
writer.charset = UTF-8
writer.policies = size: 1mb
writer.backups = 2

writerlogcat = logcat
```


```
Logger.info("I am a test log " + System.currentTimeMillis());

File data = Environment.getDataDirectory();
File myLogs = new File(data, "data/" + getPackageName() + "/files/tiny_log_0.txt");
Logger.info("Does " + myLogs.getPath() + " exist? " + (myLogs.exists()));
```

**Comment by danielwilson1702** [comment]
Well I made a stupid mistake of confusing the `res` folder with a `resources` folder for the location of the properties file. Placing it in src/main/resources fixes the issue.

This library is the bomb.
