### ISSUE TITLE
Need suggestion on properties to be used

### ISSUE THREAD

**Issue by Kameswari** [tinylog-org/tinylog#125]
Hi,

I have integrated this library for my Android project. Please find my requirement below.

Maximum log file size - 2mb
Maximum no.of days - 7 days

i.e. while saving logs, if any of the above conditions are met, it has to clear the total content of the log file and start logging again.

Please suggest what are the correct properties to be used.

Also, can we give the file size property in kb's? I tried by giving but its not working it seems. Only mb is working.

**Comment by pmwmedia** [comment]
In opposite to tinylog 1.x, tinylog2.x has no weekly policy. I dropped it as the weekly policy had been used very rarely. An alternative would be to use the daily policy and keep 7 backup log files. Maybe you have to use an higher number, as log file could be rolled much more often, if the 2 MB are reached within less than a day.

```
writer          = rolling file
writer.file     = log_{date}.txt
writer.policies = daily, size: 2mb       ; size: 2048kb works also
writer.backups  = 7
```

Size properties in KB work for me. Can you give me an example, in which it failed?

**Comment by Kameswari** [comment]
@pmwmedia Thanks for the reply. I checked the size property in kbs and is working fine.

Regarding my requirement, at any point of time, all the log files size together shouldn't exceed 2MB. i.e. per day it can hold maximum 2MB size and next day, it has to erase the data and start logging again as the limit exceeded. If not exceeded, it has to create new file and shouldn't erase previous day file.

With the properties you have given, daily maximum limit is 2MB and allowed 7 days backup. i.e. it can hold maximum of 14MB of log files size together in worst case. 

Is there any way to fulfill my need? Thanks in advance.

**Comment by pmwmedia** [comment]
@Kameswari You can fulfill your needs by forking the rolling writer. Your requirements are very specific and cannot fulfilled without any custom Java code. Just copy [RollingFileWriter.java](https://github.com/pmwmedia/tinylog/blob/v2.1/tinylog-impl/src/main/java/org/tinylog/writers/RollingFileWriter.java), rename the class, change the code to your requiremnts, and register your custom rolling file writer as described in https://tinylog.org/v2/extending/#custom-writer.
