### ISSUE TITLE
Custom level (level@) per writer not working

### ISSUE THREAD

**Issue by omatei01** [tinylog-org/tinylog#128]
JHi,
Tinylog works great. A small problem with custom level. In 2.0.1 it works only custom level for all writers not for specific one.

**Comment by pmwmedia** [comment]
This is a new feature request. Could you provide a pull request?

**Comment by omatei01** [comment]
sure.. but still, documentation is slightly confusing

**Comment by pmwmedia** [comment]
Thank you for your feedback! Which part of the documentation is confusing? How can we formulate it to avoid any misunderstanding?

The documentation is an important part of tinylog and should help users to use tinylog instead of confusing them.

**Comment by omatei01** [comment]
"If required, particular severity levels for packages or classes can be set. This overrides the default severity level.

If multiple writers are used, it is possible to define particular severity levels for them. In this case, these writers will only output log entries with the defined severity level or higher."

**Comment by pmwmedia** [comment]
Thanks, I updated this section: https://tinylog.org/v2/configuration/#severity-level

I hope it is clear now!
