### ISSUE TITLE
Application uptime placeholder

### ISSUE THREAD

**Issue by dzikoysk** [tinylog-org/tinylog#129]
It could be great to have a placeholder that represents the current uptime of application, e.g. `{uptime}`. The init time may be the same as the logger initialization time.

Even if you don't like this proposal, it might be solved by the posiblity of being able to register custom placeholder.

**Comment by pmwmedia** [comment]
A pull request for an `{uptime}` placeholder is welcome :-) I think the up time placeholder could be formatted via the same format pattern syntax as the existing `{date}` placeholder.

**Comment by pmwmedia** [comment]
API for plain Java:
`java.lang.management.ManagementFactory.getRuntimeMXBean().getUptime()`

API for Android:
`android.os.SystemClock.uptimeMillis()`

**Comment by dzikoysk** [comment]
Yeah, I was thinking about `ManagementFactory`, but it also counts JVM startup time. On the other hand maybe it could be better to separate relative uptime for each logger instance 🤔 

```
{uptime} - ManagementFactory/SystemClock
{relative-uptime} - initialized when logger is created
```

The first one is obvious, but in fact, the second one is much more useful.

**Comment by pmwmedia** [comment]
The use case for JVM up time is obvious for me. However, what is the use case for logger instances up times?

**Comment by dzikoysk** [comment]
Oh, I had to miss the notification about your response, sorry, I have a lot of them. Anyway, thanks for the implementation ❤️
