### ISSUE TITLE
No logging framework implementation found in classpath. Add tinylog-impl.jar for outputting log entries.

### ISSUE THREAD

**Issue by MairwunNx** [tinylog-org/tinylog#135]
I don't know why this exception throw when i adds via gradle collect dependencies and in bundle i have all `impl` module classes.

![image](https://user-images.githubusercontent.com/39625750/74837394-72efa680-5332-11ea-8b99-edf34d906fec.png)

![image](https://user-images.githubusercontent.com/39625750/74837401-75520080-5332-11ea-9c4d-fabe08ade13f.png)

![image](https://user-images.githubusercontent.com/39625750/74837414-81d65900-5332-11ea-8545-0f116ff3cd80.png)

I also noticed that many have the same problem.

Gradle dependencies:

![image](https://user-images.githubusercontent.com/39625750/74837506-b3e7bb00-5332-11ea-8983-073d8fb6bb94.png)

Embed configuration:

![image](https://user-images.githubusercontent.com/39625750/74837530-bea25000-5332-11ea-9897-07619bc0c467.png)

Jar configuration:

![image](https://user-images.githubusercontent.com/39625750/74837554-cbbf3f00-5332-11ea-87b2-9ec862230340.png)

**Comment by pmwmedia** [comment]
I think it should be:

```gradle
implementation 'org.tinylog:tinylog-api:2.1.0-RC3'
implementation 'org.tinylog:tinylog-impl:2.1.0-RC3'
```

**Edit:** Do you have an Android project? If yes, try to add tinylog-impl as `compile 'org.tinylog:tinylog-impl:2.1.0-RC3'`. Also don't forget the ProGuard rules: https://tinylog.org/v2/configuration/#proguard

**Comment by MairwunNx** [comment]
@pmwmedia not, i don't have an android project, i have Minecraft Forge project, and for including libraries in bundle i must use `from configurations.embed.collect { ... }` by extending configurations.

I tried implementation and compile - not difference. If i not include impl bundle in my bundle, i get exception "NoClassFoundException" or something like that.

Library existing in bundle. Perhaps this is a problem with the code that is responsible for finding the implementation in the bundle.

I also tried call `java.util.ServiceLoader.load(LoggingProvider.class);` but it did not give a positive result.

**Comment by MairwunNx** [comment]
@pmwmedia  What it is `provider=myprovider` in configuration? Why it required, i tried create this field in configuration and now i get error 

```
LOGGER ERROR: Service implementation 'myprovider' not found
LOGGER ERROR: Requested logging provider is not available. Logging will be disabled.
```

**Comment by MairwunNx** [comment]
Hmm, i write `provider=org.tinylog.provider.NopLoggingProvider` and i "suppress" logger errors, but i also didn't see logger messages and logger file. :(

**Comment by MairwunNx** [comment]
The problem has not been solved yet, I do not know why this is happening, I am looking at the code of your library.

**Comment by pmwmedia** [comment]
Could you provide a minimal example project to reproduce the issue?

Pavel Erokhin <notifications@github.com> schrieb am Mi., 19. Feb. 2020,
19:12:

**Comment by MairwunNx** [comment]
@pmwmedia My project depends on Minecraft Forge API, for testing mod bundle need minecraft.
I can try make simple console java application with some build script, but idk will worked it or not. If you can download minecraft forge, i can drop forge project, if don't can i can make simple console app.

**Comment by pmwmedia** [comment]
If you can reproduce the issue with a simple console app, I would prefer this. However I can also install Minecraft Forge (http://files.minecraftforge.net/), if required..

**Comment by MairwunNx** [comment]
Ok, ill try. Wait ...

**Comment by MairwunNx** [comment]
I reproduced this bug on simple console application -> [untitled4.zip](https://github.com/pmwmedia/tinylog/files/4229061/untitled4.zip)


If you run project via task `Run` you'll get `LOGGER WARN: No logging framework implementation found in classpath. Add tinylog-impl.jar for outputting log entries.`

If you run project via command line (after building via `build` task) via command `java -jar untitled4-1.0-SNAPSHOT.jar` then you'll see good result, logging worked.

But, with task run, not work. And i include some dependencies like on forge project.

**EDIT 1**: If i add implementation for impl and run task `run` then error not throws.

Hmm... Why some with some dependencies not work on forge ... :( i confused.

**EDIT 2**: I tried fully copy-paste package org from successful bundle to my not work bundle, but it did not help.

**Comment by MairwunNx** [comment]
I also tried set provider on `provider=org.tinylog.core.TinylogLoggingProvider` and get error message:

```
[STDERR/]: [org.tinylog.provider.InternalLogger:log:38]: LOGGER ERROR: Service implementation 'rolling file' not found
```

**Comment by MairwunNx** [comment]
I also tried call `TinylogLoggingProvider#log` directly, but it din't help.

Log:

```
LOGGER WARN: No logging framework implementation found in classpath. Add tinylog-impl.jar for outputting log entries.
LOGGER ERROR: Service implementation 'rolling file' not found
```

![image](https://user-images.githubusercontent.com/39625750/74909972-79c9f800-53ca-11ea-96bf-735934e06515.png)

**Comment by pmwmedia** [comment]
The problem is that the Gradle run task executes an application from `build/classes` and not from JAR. It even doesn't build any JAR. The run task adds `runtimeOnly` and `implementation` dependencies to the classpath, but not `embed` dependencies, because these are Minecraft Forge specific and not part of the Gradle standard. This is an issue of Minecraft Forge and not of tinylog. You would get the same issue with any library you add as `embed` to your project. 

A workaround would be add all dependencies as `embed` and `implementation`:

```gradle
dependencies {
    implementation(kotlin("stdlib-jdk8"))
    embed(kotlin("stdlib-jdk8"))
    implementation("org.tinylog:tinylog-api:2.1.0-RC3")
    embed("org.tinylog:tinylog-api:2.1.0-RC3")
    implementation("org.tinylog:tinylog-impl:2.1.0-RC3")
    embed("org.tinylog:tinylog-impl:2.1.0-RC3")
}
```

However, you can even avoid these duplicate dependencies by customizing the Gradle jar task: https://www.baeldung.com/gradle-fat-jar

**Comment by pmwmedia** [comment]
By the way, I recommend to use `tinylog-api-kotlin` instead of `tinylog-api` for Kotlin. Then you can import `org.tinylog.kotlin.Logger` instead of `org.tinylog.Logger`. This logger is especially developed for Kotlin.

**Comment by MairwunNx** [comment]
No. You can try build demo with builtin library classes, and it work.

Information at your link: 

![image](https://user-images.githubusercontent.com/39625750/74953416-af92cf00-5412-11ea-977b-6c8760764a45.png)
https://www.baeldung.com/gradle-fat-jar

I am doing everything right, probably the problem is in the code that the class is looking for. All dependencies are placed in the final JAR, and I know perfectly well that all other libraries work fine, including log4j and logback, and the runtime kotlin itself.

In my case, the implementation and compile do not differ during the assembly, the assembly requires the embed that I created.

Also, i tried embed your library with Shadow plugin, it also don't work.

**Comment by MairwunNx** [comment]
> A workaround would be add all dependencies as embed and implementation:

I already have it configuration. And by default i was make dependencies like you.

![image](https://user-images.githubusercontent.com/39625750/74954349-08169c00-5414-11ea-90db-032c8cf5e345.png)

**Comment by MairwunNx** [comment]
:( Hmmm, i don't know why always don't find impl classes, but it classes contains in bundle. ¯\_(ツ)_/¯

**Comment by michieltjampens** [comment]
I've got the same issue but in a different situation...
When i run my program via java -jar program.jar it works fine.
The jar was built using maven.
But when it's started through Tanuki wrapper (to run it as a service) it show this:
LOGGER WARN: No logging framework implementation found in classpath. Add tinylog-impl.jar for outputting log entries.

**Comment by pmwmedia** [comment]
@michieltjampens Could you open a new issue and provide there a minimal sample?

@MairwunNx Is there still anything I can help? The workaround I posted worked on my environment with your example project.
