### ISSUE TITLE
What about using kotlin files without object?

### ISSUE THREAD

**Issue by MairwunNx** [tinylog-org/tinylog#138]
Currently if we use kotlin module need type `Logger.info()` for minimal logging any message.

But, we can just remove object and it will looks like `info()` or `warn()`, but possible conflicts with `error()` with kotlin `error() // in kotlin it alias for throw()` what does throwing exceptions.

**Comment by pmwmedia** [comment]
Interesting suggestion!

**Comment by pmwmedia** [comment]
Actually, this works already today. For example, you can import the `info()` method of tinylog's logger via `import org.tinylog.kotlin.Logger.info` and issue a log entry by `info("Hello World!")`.

It works even with `error()` !

**Comment by MairwunNx** [comment]
Oh, really cool! 😁😁

**Comment by pmwmedia** [comment]
I close this issue as no changes are required ;-)
