### ISSUE TITLE
No logger implementation found when using Tanuki Wrapper.

### ISSUE THREAD

**Issue by michieltjampens** [tinylog-org/tinylog#140]
When the jar is run, no errors are given. So the build is fine. But when the jar is started through a bat file that calls the wrapper, 

> jvm 1    | LOGGER WARN: No logging framework implementation found in classpath. Add tinylog-impl.jar for outputting log entries.

To replicate, first run the DAS.jar (to see it works properly) and then the Test.bat (both found in the bin folder).
[Tanuki_tinylog.zip](https://github.com/pmwmedia/tinylog/files/4326612/Tanuki_tinylog.zip)

**Comment by pmwmedia** [comment]
Could you provide the source code and your build script?

**Comment by michieltjampens** [comment]
[Tanuki.zip](https://github.com/pmwmedia/tinylog/files/4323110/Tanuki.zip)
Here's the whole eclipse folder.

**Comment by pmwmedia** [comment]
I will have a look tomorrow.

**Comment by michieltjampens** [comment]
Sounds great. 
Not sure if it makes a difference but it happens on jdk8 and jdk11 and on most recent and older versions of tanuki.

Ok, found a first step, in the dasWrapper.conf, adding the bottom two lines fixes the not found issue but the tinylog.properties isn't found/applied...
```
# Java Classpath (include wrapper.jar)  Add class path elements as
#  needed starting from 1
wrapper.java.classpath.1=../lib/wrapper.jar
wrapper.java.classpath.2=./lib/tinylog-impl-2.0.1.jar
wrapper.java.classpath.3=./lib/tinylog-api-2.0.1.jar
```
edit: removed one dot to use the lib folder from the project.

And alter this line to find a properties file:
wrapper.java.additional.1=-Dtinylog.configuration=../bin/tinylog.properties

So both issues have a workaround, would be nice if this wasn't required.

**Comment by pmwmedia** [comment]
I propose to post this issue to [Tanuki's user mailing list](https://sourceforge.net/p/wrapper/mailman/). Your workarounds look like that the problem is very Tanuki specific and we cannot do much from tinylog side.

**Comment by michieltjampens** [comment]
Well the project has 17 other jars besides Tinylog that work fine and so did it when using logback (before switching to tinylog). So i think it might be a combination of how tanuki handles jars and how the api impl mix works? But i'll post it there and see what the response is.

**Comment by pmwmedia** [comment]
I have just tested it on my system and it works. I used a fat JAR and edited wrapper\conf\wrapper.conf.

My project: [Tanuki.zip](https://github.com/pmwmedia/tinylog/files/4331762/Tanuki.zip)

Output:
```
jvm 3    | Hello from stdout!
jvm 3    | 22:42:11.187 INFO    App.main        Hello from tinylog
```

**Comment by michieltjampens** [comment]
Ok, so it works if the libs are inside the main jar. In my case i'd like to keep that jar as small as possible (limited bandwith) but this is probably a good solution for others.

**Comment by pmwmedia** [comment]
It works even without fat JAR.

Here, the libs are outside of the main JAR: [Tanuki.zip](https://github.com/pmwmedia/tinylog/files/4332764/Tanuki.zip)

**Comment by michieltjampens** [comment]
Hm, gues i'll try to figure out what makes the difference...
