### ISSUE TITLE
Combining rolling and count

### ISSUE THREAD

**Issue by michieltjampens** [tinylog-org/tinylog#141]
Probably more a question than an issue/bug.

> #Raw sensor data
> writer4		     = rolling file
> #Only write things with the RAW tag
> writer4.tag		 = RAW
> writer4.file     = raw/{date:yyyy-MM}/{date:yyyy-MM-dd}_RAW_{count}.log
> #All the levels
> writer4.level    = info
> #Buffered means write every 64KB 
> writer4.buffered = true
> #Append to existing file
> writer4.append   = true
> writer4.policies = daily, size: 100mb
> writer4.format = [{date: yyyy-MM-dd HH:mm:ss.SSS}]\t{message}
> 

With this as writer setup i get the following files:
![rolling_numbers](https://user-images.githubusercontent.com/60646590/76601570-788f7500-6509-11ea-8c14-38dafe651ebc.jpg)
Is this a bug or how do i make it so it restarts the count by day?

**Comment by pmwmedia** [comment]
~~Currently, the count works globally. However, I agree that it would be nice to have a count that restarts when the rest of the path (before the count placeholder) has changed.~~

**Update:** My first assumption was wrong, see https://github.com/pmwmedia/tinylog/issues/141#issuecomment-794532251

**Comment by michieltjampens** [comment]
That in combination with the compression would be ideal. I might look into it next week.

**Comment by pmwmedia** [comment]
Pull requests are welcome :)

**Comment by pmwmedia** [comment]
Actually, it should already work as you have requested. I have just tested your `tinylog.properties` configuration. My log files look like this:

```
2021-03-08_RAW_0.log
2021-03-08_RAW_1.log
2021-03-08_RAW_2.log
2021-03-09_RAW_0.log
2021-03-09_RAW_1.log
```

@michieltjampens Are you still able to reproduce the issue? If yes, which tinylog version are you using? Could you provide a minimal reproduction example as GitHub repository?

**Comment by michieltjampens** [comment]
At first i thought this was now caused by the added gzip (thanks for the enhancement) but doesn't appear so.
Just checked on instance of the project and honestly don't have a clue how it determines to start a new count...
Using 2.2.1, i get this:
![image](https://user-images.githubusercontent.com/60646590/110588080-cd91b580-8174-11eb-8f35-01301f031b10.png)
It hasn't restarted the count since the 15th, this is running on a Raspbian board.
This is the current properties file: [tinylog.txt](https://github.com/pmwmedia/tinylog/files/6113801/tinylog.txt)

Another instance of the project (using the same properties file) is up to count 517 and is on windows server.
Both are using java11.
The project itself should be on github within a week or so (om my employer hub) but that isn't exactly minimal. Not sure how i would make a minimal version of it (that i'm allowed to post).

**Comment by pmwmedia** [comment]
I have just found the cause. The issue only occurs when rolling during runtime, but never at the application start. Actually, the fix is very trivial.
