### ISSUE TITLE
Android device - Unable to save logs with tinylogs

### ISSUE THREAD

**Issue by Kameswari** [tinylog-org/tinylog#142]
Hi,

I have used this tinylog library and able to save and retrieve logs on Android simulator. But this is not working on Android device. Below are the properties I used.

writer          = rolling file
writer.format   = {date:yyyy-MM-dd HH:mm:ss} {level}: {message}
writer.file     = #{logs.folder}/log.{count}.txt
writer.charset  = UTF-8
writer.policies = size: 1mb
writer.backups  = 1

I have used below line to set the logs folder dynamically.
System.setProperty("logs.folder", getFilesDir().getAbsolutePath());

I have enabled Multidex for my application and compiling with Java 1.8 version. Could someone help me on how to resolve this issue?

I really wonder why its working only in simulator and not on device.

Thanks,
Kameswari

**Comment by pmwmedia** [comment]
I assume that your apps doesn't have the required privileges to write any files to the configured folder. What happens if you try to write into the configured folder by your app directly?

**Comment by Kameswari** [comment]
@pmwmedia 
Thanks for the reply. I am already saving profilepic in my app and its saved successfully. Its saved under "files" folder of the application's internal memory which is the same path given for tinylogs too. From the logcat, I have seen the below error.

2020-03-17 12:54:53.027 29845-29845/com.carrier.myway W/m.carrier.mywa: Accessing hidden method Ldalvik/system/VMStack;->fillStackTraceElements(Ljava/lang/Thread;[Ljava/lang/StackTraceElement;)I (light greylist, reflection)
2020-03-17 12:54:53.063 29845-29845/com.carrier.myway W/System.err: LOGGER WARN: 'logs.folder' could not be found in system properties
2020-03-17 12:54:53.138 29845-29845/com.carrier.myway W/System.err: ERROR: Failed creating service implementation 'org.tinylog.writers.RollingFileWriter' (java.lang.IllegalArgumentException: Invalid token 'logs.folder' in '#{logs.folder}/logs/log.{count}.txt')

Could you please let me know how to solve this issue?

FYI, I am setting the system.property as below 
String filePath = getFilesDir().getAbsolutePath();
System.setProperty("logs.folder", filePath);

Thanks

**Comment by pmwmedia** [comment]
> 2020-03-17 12:54:53.027 29845-29845/com.carrier.myway W/m.carrier.mywa: Accessing hidden method Ldalvik/system/VMStack;->fillStackTraceElements(Ljava/lang/Thread;[Ljava/lang/StackTraceElement;)I (light greylist, reflection)

That is no problem, just a warning about usage of internal API what tinylog does for performance reasons.

> 2020-03-17 12:54:53.063 29845-29845/com.carrier.myway W/System.err: LOGGER WARN: 'logs.folder' could not be found in system properties

This is the real cause for your issue. Please ensure that you set the system property before any log entry will be issued.

> 2020-03-17 12:54:53.138 29845-29845/com.carrier.myway W/System.err: ERROR: Failed creating service implementation 'org.tinylog.writers.RollingFileWriter' (java.lang.IllegalArgumentException: Invalid token 'logs.folder' in '#{logs.folder}/logs/log.{count}.txt')

Only a subsequent error.

**Comment by Kameswari** [comment]
@pmwmedia 
Thanks for the reply. You are right. I am calling the setproperty after issuing the log entry.

Your answer helped a lot and resolved my issue. Thanks once again.

**Comment by pmwmedia** [comment]
Your are welcome :-)
