### ISSUE TITLE
Throw UnsupportedOperationException for runtime configuration attempts

### ISSUE THREAD

**Issue by martinandersson** [tinylog-org/tinylog#143]
I read in the JavaDoc of [`Configuration`](https://tinylog.org/v2/javadoc/org/tinylog/configuration/Configuration.html) that attempts made to change the configuration once it has been put in use will be silently ignored.

In my opinion this is a bad design. The most obvious reason being that real-world applications may wrongfully assume that they can make configuration attempts during runtime only to discover post-fact that it was a NOP. If I may be real frank here, I actually think that NOP methods is like one of the most profound evils in the world of programming and should be avoided like the plague. You know, "dead code", telling an object to do something but he doesn't do anything, et cetera et cetera.

But maybe even a stronger argument is that this pattern breaks away from the Java-idiom of being explicit and clear with an `UnsupportedOperationException` for any operation that is not supported. See the JDK type [Files](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/Files.html) for example.

Let's put it this way; if there is a valid reason to do something that upsets purist object-oriented programmers that are used to their language and libraries behaving in a particular way that probably makes the most sense for the most people, how about we add that reason in the JavaDoc? For me, I want to know that the libraries and code I import into my applications are "sound" and professionally constructed. The API is a telltale sign on what lurks beneath it.

And finally, I haven't looked into the source code, but if the Configuration class is not mutable and the fact that this mutation is not supported because his state has been "committed", maybe IllegalStateException would be more appropriate to throw. But I believe this depends on the semantics of this class a bit and how the configuration takes effect in the first place.

Merci!! =)

**Comment by martinandersson** [comment]
Why was this issue closed?

Did you look into the Files JavaDoc? I found 33 UnsupportedOperationException documented, you know, thrown if user attempts to use an unsupported option. How is this any different than what we're doing?

This is what I read from Tinylog's [`Configuration`](https://tinylog.org/v2/javadoc/org/tinylog/configuration/Configuration.html) JavaDoc:

> If the framework has been initialised once, the configuration is immutable and further configuration changes will be just ignored.

Am I the only one who think this is complete madness? Is this what we would have expected the Java compiler to do if we tried to change a final variable? Silently ignoring the statement? Hey, what do we expect a Collection.unmodifiableList(), List.of() et cetera, do ... when attempts to modify them are done? Most "views" or whatever that I can think of end up with UnsupportedOperationException. But as stated earlier, IllegalStateException could also be warranted. A Java Stream for example can only be operated once, otherwise IllegalStateException. Sort of sounds like our configuration reaches a "committed" point.

But bottom line is this, I could go on all day with examples here. We do not ever never "just do nothing". Madness! Please, make Tinylog great again!

**Comment by pmwmedia** [comment]
This issue is closed as it has been fixed by commit 827e86f. Originally, it was even planed to be part of tinylog 2.2.0-M1. However, due to a late push, it will be part of second milestone.

**Comment by martinandersson** [comment]
Nice, thanx! =)
