### ISSUE TITLE
Conditional formatting of numbers is not working with SLF4J

### ISSUE THREAD

**Issue by karklik** [tinylog-org/tinylog#144]
Hello,
Recently I have started using this wonderful framework :) and found out that one of features mentioned in documentation is not behaving correctly with SLF4J wrapper in my project and I'm not sure it it is any kind of limitation or a bug so please take a look on following details.

### Example code:
```
import org.tinylog.Logger;

public class Main {
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(Main.class);

    public static void main(String[] args) {
        //SLF4J
        log.info("There {0#are no files|1#is one file|1<are {} files}", 5);
        //tinylog
        Logger.info("There {0#are no files|1#is one file|1<are {} files}", 5);
    }
}
```

### Console output:
```
10:03:20 AM: Executing task 'Main.main()'...

> Task :compileJava UP-TO-DATE
> Task :compileGroovy NO-SOURCE
> Task :processResources
> Task :classes

> Task :Main.main()
2020-03-20 10:03:22 [main] com.circlekeurope.Main.main()
INFO: There {0#are no files|1#is one file|1<are 5 files}
2020-03-20 10:03:22 [main] com.circlekeurope.Main.main()
INFO: There are 5 files

BUILD SUCCESSFUL in 2s
3 actionable tasks: 2 executed, 1 up-to-date
10:03:22 AM: Task execution finished 'Main.main()'.

```

### Configuration
default

### java -version
```
>java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

### gradle help
```
Welcome to Gradle 6.2.2.
```

### Dependencies
```
    // https://mvnrepository.com/artifact/org.slf4j/slf4j-api
    implementation group: 'org.slf4j', name: 'slf4j-api', version: '1.7.30'
    // https://mvnrepository.com/artifact/org.tinylog/slf4j-tinylog
    implementation group: 'org.tinylog', name: 'slf4j-tinylog', version: '2.1.0'
    // https://mvnrepository.com/artifact/org.tinylog/tinylog-api
    implementation group: 'org.tinylog', name: 'tinylog-impl', version: '2.1.0'
```

**Comment by pmwmedia** [comment]
Firstly, thank you very much for the complete and very good documentation of your issue!

Until version 2.1, tinylog used the same algorithm for formatted log messages, regardless by which logging API these have been issued. This caused some problems and incompatibilities when log messages contained curly brackets to output.

For example, if a user wants to log a JSON object via SLF4J by calling `log.info("{\"number\": {}}", 42)`, he or she will receive the message `{"number": 42}`, if using Logback or Log4j as logging implementation, but won't if using tinylog before version 2.1 as tinylog interpreted the JSON object as formatted placeholder.

The idea of SLF4J is that users can format log statements independently from the concentrate logging implementation. Therefor, tinylog cannot support conditional formatting of numbers via SLF4J API without breaking SLF4J compatibility.

**Comment by karklik** [comment]
Thanks for detailed explanation 👍 In that case I'm closing issue.
