### ISSUE TITLE
Tinylog does not work in Eclipse plugin

### ISSUE THREAD

**Issue by chengm349** [tinylog-org/tinylog#147]
please refer to the [link](https://www.eclipse.org/forums/index.php?t=rview&goto=1826693#msg_1826693) to get all information.

**Comment by pmwmedia** [comment]
Closed in favor to https://stackoverflow.com/questions/61318315/how-to-use-tinylog-in-eclipse-plugin.

@chengm349 I added the missing tinylog tag in your question on StackOverflow.
