### ISSUE TITLE
TinyLog module-info.java

### ISSUE THREAD

**Issue by moxit0** [tinylog-org/tinylog#151]
Hello, have you thinking about providing module-info.java module descriptor then TinyLog to be compatible with Java Platform Module System and make possible creating of runtime image with jlink ?

**Comment by pmwmedia** [comment]
Hi, due to Android compatibility, tinylog needs to be compiled as Java 6 byte code. When I added module information to the tinylog JARs, I couldn't find any convenient way in Maven to set Java 6 byte code as compiler output, but providing also module-info.java files.

Instead, I have set the `Automatic-Module-Name` entry in all Manifest files. According to the feedback I received that time, all tinylog artifacts have been worked well with Java Platform Module System since then. What issues due you have?

**Comment by moxit0** [comment]
Hi, thank you for your answer. I am developing app which UI is based on JavaFX. Since I need a real multi platform solution I am using Jlink creating a runtime image. It works perfect with libraries migrated to JPMS but without success with those that have automatic modules. I am using "javafx-maven-plugin" for launching an application and creating of runtime image as well. Integrating TinyLog is working perfectly if I just launch an application but when I try to create a runtime image with the plugin I receive : 
`[INFO] --- javafx-maven-plugin:0.0.4:jlink (default-cli) @ application ---
Error: automatic module cannot be used with jlink: org.tinylog.api from file:///C:/data/m2/org/tinylog/tinylog-api/2.1.2/tinylog-api-2.1.2.jar
[ERROR] Command execution failed.` 

This error unfortunately I have seen many times when I use libraries that are still not modular .

**Comment by pmwmedia** [comment]
I see, automatic module cannot be used with jlink. We need another solution.

**Comment by pmwmedia** [comment]
ModiTect looks promising:
https://github.com/moditect/moditect/#adding-a-module-descriptor-to-the-project-jar

**Comment by moxit0** [comment]
Thank you for offering a workaround but unfortunately I still cannot make it work. Using example of your link: 
```
               <plugin>
                <groupId>org.moditect</groupId>
                <artifactId>moditect-maven-plugin</artifactId>
                <version>1.0.0.Beta2</version>
                <executions>
                    <execution>
                        <id>add-module-infos</id>
                        <phase>package</phase>
                        <goals>
                            <goal>add-module-info</goal>
                        </goals>
                        <configuration>
                            <jvmVersion>11</jvmVersion>
                            <module>
                                <moduleInfo>
                                    <name>org.tinylog.api</name>
                                    <exports>
                                        org.tinylog.*;
                                    </exports>
                                </moduleInfo>
                            </module>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
but result is :
```
Failed to execute goal org.moditect:moditect-maven-plugin:1.0.0.Beta2:add-module-info (add-module-infos) on project common: Execution add-module-infos of goal org.moditect:moditect-maven-plugin:1.0.0.Beta2:add-module-info failed: Invocation of jdeps failed: jdeps --generate-module-info C:\Users\projectDir\development\App\common\target\moditect --add-modules org.tinylog.impl,com.fasterxml.jackson.datatype.jsr310,org.tinylog.api,com.fasterxml.jackson.databind,com.fasterxml.jackson.annotation,com.fasterxml.jackson.core --module-path C:\data\m2\org\tinylog\tinylog-impl\2.1.2\tinylog-impl-2.1.2.jar;C:\data\m2\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.11.0\jackson-datatype-jsr310-2.11.0.jar;C:\data\m2\org\tinylog\tinylog-api\2.1.2\tinylog-api-2.1.2.jar;C:\data\m2\com\fasterxml\jackson\core\jackson-databind\2.11.0\jackson-databind-2.11.0.jar;C:\data\m2\com\fasterxml\jackson\core\jackson-annotations\2.11.0\jackson-annotations-2.11.0.jar;C:\data\m2\com\fasterxml\jackson\core\jackson-core\2.11.0\jackson-core-2.11.0.jar C:\Users\projectDir\development\App\common\target\common-1.0-SNAPSHOT.jar
```
I even have no Idea what the problem is :)

**Comment by pmwmedia** [comment]
There is a misunderstanding :D I want to use ModiTect in the tinylog project itself for generating valid modules.

**Comment by moxit0** [comment]
Ohh great :D will looking forward for a new Jlink compatible version.

**Comment by pmwmedia** [comment]
Wait for https://github.com/moditect/moditect/issues/122

**Comment by pmwmedia** [comment]
@moxit0 Could you test the latest version with Jlink: [tinylog-2.2-SNAPSHOT.zip](https://github.com/pmwmedia/tinylog/files/4815160/tinylog-2.2-SNAPSHOT.zip)?

**Comment by moxit0** [comment]
Sure, soon will give you feedback.

На пн, 22.06.2020 г. в 22:17 Martin Winandy <notifications@github.com>
написа:

**Comment by moxit0** [comment]
Hi,

How did you test the modules ? I am using Intellij and Maven, added jars
from tinylog-2.2-SNAPSHOT.zip as a library to Intellij but when I run mvn
install result is:
*[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile
(default-compile) on project common: Compilation failure: Compilation
failure: *
*[ERROR] /xxx/PROJECT/common/src/main/java/module-info.java:[9,25] module
not found: org.tinylog.api*
*[ERROR] /xxx/ PROJECT/common/src/main/java/module-info.java:[10,25] module
not found: org.tinylog.impl*

Is there any possibility to publish this version of TinyLog in some
repository that I can use with Maven ?

На пн, 22.06.2020 г. в 22:34 nikolai petkov <moxito.niki@gmail.com> написа:

**Comment by pmwmedia** [comment]
@moxit0 I have just released all artifacts as version 2.2.0-M1

**Comment by moxit0** [comment]
Hi,

it is working now, Jlink can be executed and runtime image is created
successfully.

Thank you.

На вт, 23.06.2020 г. в 23:19 Martin Winandy <notifications@github.com>
написа:

**Comment by pmwmedia** [comment]
@moxit0 Thank you for testing!

**Comment by swardana** [comment]
Hi All,
First, I'm sorry to comment on this closed ticket, but I wonder how to use the tinylog module name in project?
Is there any sample or documentation? because I can't find it in tinylog website documentation.

**Comment by pmwmedia** [comment]
You just need to add a `module-info.java` file:

```
module example {
	requires org.tinylog.api;
}
```

Full example: [example.zip](https://github.com/tinylog-org/tinylog/files/7347926/example.zip)
