### ISSUE TITLE
Change Configuration at runtime

### ISSUE THREAD

**Issue by ghost** [tinylog-org/tinylog#157]
Is that possible to change configuration with Configuration.set at runtime? I mean I want to log information for e.g. different users/objects to different files while the software running.

When there is no created object e.g. MYOBJECT1, there will be no log file for it. When user created such an object I tried to configure a log writer and record all logs into that file by using tags also.

e.g. 
```
String someWriter = "myobject1";
String tag = "myobject1-tag";
if (Configuration.get(someWriter ) == null) {
        Configuration.set("autoshutdown", "true");
        Configuration.set(someWriter , "rolling file");
        Configuration.set(someWriter + ".tag", tag);
        etc
        etc
}
```
This throws "java.lang.UnsupportedOperationException: Configuration cannot be changed after applying to tinylog" as you said in your web page, tinylog config cannot be changed after it becomes immutable. 

Is there a way to make it not immutable so that I can change the configuration ?

Thank you.

**Comment by pmwmedia** [comment]
When do you want to change the configuration? If you haven't issued any log entry yet, you can still change the configuration however you want at runtime. The immutability of the configuration after issuing the first log entry is one of the reasons why tinylog 2 is such fast in [benchmarks](https://tinylog.org/v2/benchmark/).

If you just want to have a rolling file writer that outputs all log entries with a tag but ignores all log entries without tags, you can use the plus place placeholder: `someWriter.tag = +`.

If you really need to change the configuration after issuing the first log entry, you can take a look in https://github.com/pmwmedia/tinylog/issues/102. It is possible to wrap the `LoggingProvider` from tinylog-impl and make it mutable. The solution there works for tinylog 2.0 and 2.1, but needs some adjustments for tinylog 2.2.
