### ISSUE TITLE
Allow access to writer and provider 

### ISSUE THREAD

**Issue by Git5000** [tinylog-org/tinylog#158]
The automatic loading via services of (custom) writers and providers is nice but prevents access to the created objects (unless you call out somewhere from the constructor). Is it possible to add getters for writers and maybe providers. The idea behind it is to change writer properties at runtime.

Possible solution:
Add getProviders() to BundleLoggingProvider to get its internal array.
Add getWriters() or getWriter(tag,level) or getWriters(tag) to TinylogLoggingProvider.

**Comment by Git5000** [comment]
Attached is a possible patch for above issue. The patch is against V2.1.2 (api and impl) but I would guess it is the same against HEAD. Feedback or suggestions are of course welcome.

It affects:

- TinylogLoggingProvider.java
- BundleLoggingProvider.java	
- ProviderRegistry.java	
	
and gives you:

- ProviderRegistry.getLoggingProviders()                     // Resolves the Bundle if it is a bundle otherwise the provider
- TinylogLoggingProvider.getWriters()                         // Get all writers of the provider
- TinylogLoggingProvider.getWriters(final String tag) // Get all writers of the provider registered for a tag (or no tag)
- TinylogLoggingProvider..setWriters(final String tag, final Level level) //  The same but with a level (all at and above the level)

Actually I think that the setWriters(final String tag, final Level level) is not necessary and should be left out. But for completeness the patch contains it.

[impl_patch.txt](https://github.com/pmwmedia/tinylog/files/5080224/impl_patch.txt)
[api_patch.txt](https://github.com/pmwmedia/tinylog/files/5080225/api_patch.txt)

**Comment by pmwmedia** [comment]
@Git5000 Could you provide your changes as pull requests and add some JUnit tests? I would be glad to merge your changes!
