### ISSUE TITLE
MiniBug: NullPointerException in ThreadNameToken

### ISSUE THREAD

**Issue by Git5000** [tinylog-org/tinylog#159]
_ThreadNameToken_ (and similar _ThreadIdToken_) generate a  _NullPointerException_ if a log entry does not contain the thread entries  (LogEntry.* are null then). This normally does not happen as any format containing a {thread} entry should generate "THREAD" as required log entry. However, if a writer does not do this  (accidentaly) the _ThreadNameToken_ , ...  throw a _NullPointerException_ which is a bit hard to find, as the logger just writes that there was some _NullPointerException_. Similar behaviour for class, method or file token write a "null" text in the output instead of throwing an exception.

The Code is 
`	public void render(final LogEntry logEntry, final StringBuilder builder) {`
`		builder.append(logEntry.getThread().getName());`
`	}`

Better would be something like 
`Thread thread = logEntry.getThread();`
`builder.append(thread==null?"null":thread.getName());`

and similar for the other `logEntry.getThread()` calls in ThreadNameToken and ThreadIdToken.

This is only a mini bug (or a feature?) but hard to find if it is wrong.

It is tested in V2.1.2.

**Comment by pmwmedia** [comment]
I don't see this as a real bug as writers should not lie about the required log entry values. However, I would accept a pull request to fix this issue. I assume that also further tokens are affected if expected log entry values are not set. I propose to output a meaningful message instead of `"null"` like `"<Unknown Thread>"` or `"<Thread is not set>"`. Better ideas are welcome!

**Comment by Git5000** [comment]
I completely agree. It is at most a "Mini bug" (as mentioned in the title). With proper coding it should not happen. But of course it did happen :-) It is the question whether the little added safety is worth the extra code.

**Comment by pmwmedia** [comment]
For me, it does not have top priority. However, I would accept a pull request.
