### ISSUE TITLE
 java -Dtinylog.writer.level=OFF does not seem to work

### ISSUE THREAD

**Issue by ghost** [tinylog-org/tinylog#162]
I'm trying to disable the logger by overriding it with a -D, however, the log files are still being generated as zero length files. Am I doing this correctly?  Is there another way?

Using 2.2.0-M2 maven dep
Using jar tinylog.properties in jar file as follows:
```
writer          = rolling file
writer.locale   = en_US
writer.charset  = UTF-8
writer.level    = info
writer.latest   = logs/my.log
writer.file     = logs/my{count}.log
writer.format   = {date}:{level}:{message}
writer.policies = startup, size: 10kb
writer.backups  = 10
```

**Comment by pmwmedia** [comment]
Do you want to disable only one writer or logging at all? `-Dtinylog.writer.level=OFF` does not prevent the creation of the writer. It only sets the logging level for the writer. However, `-Dtinylog.level=OFF` will disable logging completely and prevent the creation of any writer.

**Comment by ghost** [comment]
In this one case, I need it to simply disable all writers (all logging essentially). I will try -Dtinylog.level=OFF and let you know how it works.  The end goal is not to have a zero length file upon startup.  Thanks -Alan

**Comment by ghost** [comment]
Unfortunately, I can confirm that it still creates zero length log files based on the aforementioned tinylog.properties in my.jar file. I have a small snippet project that tests this in isolation.

java -Dtinylog.level=OFF -Dfile.encoding=UTF-8 -jar my.jar
<img width="1076" alt="Screen Shot 2020-08-19 at 10 23 05 PM" src="https://user-images.githubusercontent.com/9642883/90709678-b936ab80-e26a-11ea-8eaf-f71a6ebd5905.png">

**Comment by pmwmedia** [comment]
I can reproduce the issue, too
