### ISSUE TITLE
Question|Feature: Multi-Tag Writer

### ISSUE THREAD

**Issue by Git5000** [tinylog-org/tinylog#164]
The following scenario occurs:

- Library 1: Logs to TAG "Lib1"
- Library 2: Logs to TAG "Lib2"
- Main program includes the libs (but cannot change them) and logs to TAG "Main"
- All tags shall appear in the the same log (typically a file, but could be something else)

So the question is (or an idea if the feature does not exists yet) is:

_Can a writer support multiple tags._ 

```
writer.tag = Lib1|Lib2|Main
writer.tag = Lib1,Lib2,Main
```

On writer creation the writer would then just need to be written so several positions on the matrix[TAG][LEVEL] like the levels already do. I am not sure whether this is already possible as the matrix supports this feature but it seems for each entry a new writer object is created and I could not find any other way on how to set the multiple tags on the writer. That approach would be a very small change to `ConfigurationParser`.

Possible other approaches to the problem are (but none is fully convincing)

-  SharedFileWriter (but this is an overkill with locking and seems to not work inside one thread in one program?)
- Static writers like the Console writer (so a static File Writer with a static FileStream)  do work
- Having a "Forwarding" Writer does in principlly work (it forwards the log to another tag. But has a bit problems with the required log entries if they differ as you need to know about the required log entries before all writers exists).
- Use an user defined writer (extend FileWriteR) which gets all TAGs and filter for the TAGS of interest.

**Comment by pmwmedia** [comment]
> All tags shall appear in the the same log (typically a file, but could be something else)

If you don't set `writer.tag`, tinylog will write all log entries (tagged and untagged) to this writer. This works for all writers including  the `file writer` and `rolling file writer`. You can also set `writer.tag = +` to write all tagged log entries but to exclude untagged log entries.

**Comment by Git5000** [comment]
Thank you for your quick answer. With your feedback another solution is of course to make a "catchall" writer (e.g. an extension of  the FileWriter and then filter out the tags of interest (updated comment above to include that). This does fulfill the use case and question.

However, you do need to do the manual filtering and provide some "user tags" as the scenario above is simplified and it can contain more loggers with other tags which you dont want in the output. Using the empty tag all of them would be logged. But it of course easy to extend a standard writer and put a TAG check in I suppose.

PS: The "+" does not work with me and V2.2. "-", a "TAG" string and "no entry" do work.

**Comment by Git5000** [comment]
In case this feature `writer.tag = TAG1, TAG2, TAG3` is of interest to the library: I tried as a test to put the multi tag option in the `ConfigurationParser`. It works with around 10 lines of extra code to have such a multi tag option.  You just need to fill your writer matrix on N-positions.

It needs something like
```
String[] tagArray = tag.split("\\s*,\\s*");
for (String tagArrayItem : tagArray) {
  addWriter(writer, matrix, tags.indexOf(tagArrayItem.trim()) + 1, level);
}
```
in ConfigurationParser createWriters() and a similiar loop in getTags().  

The rest including shutdown looks like it would work out of the box. 

You of course know the tinylog library better to know whether there are some unforseen side effects.

**Comment by pmwmedia** [comment]
> The "+" does not work with me and V2.2.

You are right! It had been planned but have never been implemented for any reason. I have just realized it while reading the source code after seeing your response.

> In case this feature `writer.tag = TAG1, TAG2, TAG3` is of interest to the library: I tried as a test to put the multi tag option in the `ConfigurationParser`. It works with around 10 lines of extra code to have such a multi tag option. You just need to fill your writer matrix on N-positions.
> 
> It needs something like
> 
> ```
> String[] tagArray = tag.split("\\s*,\\s*");
> for (String tagArrayItem : tagArray) {
>   addWriter(writer, matrix, tags.indexOf(tagArrayItem.trim()) + 1, level);
> }
> ```
> 
> in ConfigurationParser createWriters() and a similiar loop in getTags().
> 
> The rest including shutdown looks like it would work out of the box.
> 
> You of course know the tinylog library better to know whether there are some unforseen side effects.

I agree, it should be enough to change these both methods. The only side effect would be that we will break support for tags with commas inside :-D However, I think we can live with that ;-)

**Comment by Git5000** [comment]
I think it is a nice enhancement in function and configuration possibility for very little effort and risk. Your architecture of the tags and levels basically asks for such a feature :-) 

After your hint this morning, I implemented for my use case the "catchall" function storing the necessary tags as a "user field". The loggers work now as expected but it requires extending or copying all used writers. Which is no problem but not a very elegant solution. So I would revert that and use the multi-tag feature instead.
