### ISSUE TITLE
Multiple LoggingProvider entries in configuration

### ISSUE THREAD

**Issue by Git5000** [tinylog-org/tinylog#166]
Creating `LoggingProviders `gives three options:

1.  Automatically create all logging provider from the services (this includes typically the `TinylogLoggingProvider`)
2.  Creating a (user defined) provider explicitley (provider = user provider)
3.  Creating the NOP Provider for no logging (provider = nop)  - a special case of 2.

Using the options 1+2 you can create all providers or exactley one LoggingProvider but not for example specify two providers. Although this is problably not such a widely used "use case" it would be nice to have a multiple provider configuration similar to the multiple writer selection implemented earlier on. Using the `BundledLoggingProvider` already a cointainer for multiple providers exists and this would give the user more configuration possibility on the library with little extra code in the logging provider loading.

Suggested configuration syntax:
` provider = system out, user out, special out`

Suggested code change is in `ProviderRegistry,.java`, method `LoggingProvider loadLoggingProvider()` [replacing the else branch which treated one named provider]

```
List<LoggingProvider> providers = new LinkedList<LoggingProvider>();
			String[] nameItems = name.split(",");
			for (String nameItem : nameItems)
			{
				LoggingProvider provider = loader.create(nameItem.trim());
				if (provider == null) {
					InternalLogger.log(Level.ERROR, "Requested logging provider '" + nameItem + "' is not available.");
				}
				else {
					providers.add(provider);	
				}
			}
			if (providers.size() == 0) {
				InternalLogger.log(Level.ERROR, "Requested logging provider is not available. Logging will be disabled.");
				return new NopLoggingProvider();
			} else if (providers.size() == 1) {
				return providers.get(0);
			} else {
				return new BundleLoggingProvider(providers);
			}
```

If you want this feature to be implemented you can assign it to me :-)

**Comment by pmwmedia** [comment]
Sounds great! Your pull request is very welcome :-)
