### ISSUE TITLE
-D options suppose to override options set in tinylog.properties?

### ISSUE THREAD

**Issue by ghost** [tinylog-org/tinylog#169]
Please correct me if I'm using this correctly.

I have a jar file with the following tinylog.properties resource settings:
```
writer          = rolling file
writer.locale   = en_US
writer.charset  = UTF-8
writer.level    = info
writer.latest   = logs/my.log
writer.file     = logs/my{count}.log
writer.format   = {date}:{level}:{message}
writer.policies = startup, size: 10kb
writer.backups  = 10
```
If I set java -Dtinylog.writer=console then I override "rolling file", correct?

tinylog is throwing the following error in this case, even though I thought I was overriding rolling file from the -D command line option:
`ERROR: Failed creating service implementation 'org.tinylog.writers.RollingFileWriter' (java.lang.IllegalArgumentException: File name is missing for file writer)`

**Comment by pmwmedia** [comment]
Actually this should work. I have just tested overriding a writer by setting `-Dtinylog.writer=console`. It works for me. I have used the latest version of tinylog (2.2.0-M3).

Could you set a break point in `org.tinylog.configuration.Configuration.load()` and debug what is happening there?

**Comment by ghost** [comment]
Yep, it works for 2.20-M2/M3.  I'm using Proguard it could be that the writers are not loading properly.  Thank you for taking the time to try this out.
