### ISSUE TITLE
Trying to understand how rolling logs work ...

### ISSUE THREAD

**Issue by ghost** [tinylog-org/tinylog#171]
```
writer          = rolling file
writer.locale   = en_US
writer.charset  = UTF-8
writer.level    = info
writer.latest   = test-logs/snippet.log
writer.file     = test-logs/snippet{count}.log
writer.format   = {level}:[{date}]:[{line}]:[{class}.{method}()]    {message}
writer.policies = startup, size: 10mb
writer.append   = true
writer.backups  = 10
```
I thought the way rolling logs work is when snippet.log reaches 10mb then it starts a new snippet0.log.  Is this correct with the configuration I have above?  If so, then my snippet.log reaches about 840kb then a new snippet0.log gets created.  Maybe I need to be corrected.

I thought that the snippet.log gets appended between restarts with the writer.append = true option until it reaches 10mb before starting a new snippet0.log.  This is not the case for me on 2.2.0-M3.

**Comment by pmwmedia** [comment]
You are using two policies: startup and size:10mb. This means that tinylog will start a new log file on every start of your application. If you change `writer.policies = startup, size: 10mb` into `writer.policies = size: 10mb`, tinylog will continue the last log file when starting your application.

**Comment by ghost** [comment]
I made the adjustments as you described.  However, I am still getting ~839k log files. It seems that **between restarts** it still creates new log files (snippet0.log, snippet1.log ...)?  Is this the expected behavior?

What do I need to do to the properties file in order to get snippet.log to fill up to 10mb before starting a new log snippet0.log?

```
writer          = rolling file
writer.locale   = en_US
writer.charset  = UTF-8
writer.level    = info
writer.latest   = test-logs/snippet.log
writer.file     = test-logs/snippet{count}.log
writer.format   = {level}:[{date}]:[{line}]:[{class}.{method}()]    {message}
writer.policies = size: 10mb
writer.append   = true
writer.backups  = 10
```

**Comment by pmwmedia** [comment]
You are right, there is a bug in the latest milestone (2.2.0-M3). I'm going to fix that.

In the latest stable version (2.1.2), continuing rolling log files is still working. But this version does not support `writer.latest` yet.

**Comment by ghost** [comment]
I understand why you want to fix that in 2.1.2.  Looking forward to the next release with this fix.

Apologies for being such a pest - but I really like the implementation you have.

**Comment by pmwmedia** [comment]
I'm going to fix it in version 2.2.0-M4. This bug happened in the tinylog 2.2 branch, In earlier tinylog versions (2.1.2 and earlier), this feature was never broken.

**Comment by ghost** [comment]
👍 looking forward to M4

**Comment by ghost** [comment]
2.2.0-M4 is now appending log properly (as expected). 

However, it still creates snippet0.log with the same outputs as snippet.log in my example.  While this is not a deal breaker (I can tolerate this issue no problem).  I just wanted you to know that this is its current behavior.

**Comment by pmwmedia** [comment]
@aguedeney Actually, "snippet.log" is only a hard link to the latest log file. If you don't need any link to the latest log file, you can remove the property `writer.latest = *`.
