### ISSUE TITLE
Allow access to writer and provider (Part II )

### ISSUE THREAD

**Issue by Git5000** [tinylog-org/tinylog#176]
In issue #158 the access to the writers were enhanced. Although initially discussed the third getter 
`TinylogLoggingProvider.setWriters(final String tag, final Level level) // The same but with a level (all at and above the level)`
was  not implemented. It turns out that it might be nice to have it after all. Can we add the third getter?

**Comment by pmwmedia** [comment]
Fixed by pull request #178
