### ISSUE TITLE
Flexible Console Writer Error Level (very optional)

### ISSUE THREAD

**Issue by Git5000** [tinylog-org/tinylog#180]
The console writer allows to choose which error level goes to STDERR and STDOUT. The selection is:

- (default): ERROR+WARN go to STDERR , the rest to STDOUT
- ("err"): all goes to STDERR 
- ("out"): all goes to STDOUT

In a user defined console writer I want only ERROR to go STDERR the rest to STDOUT. I therefore set the cut off level differently so that the user can choose from what level on the STDERR stream shall be used. I configure my user defined console writer:

`
Configuration.set("stream", "err@ERROR")
`

Maybe this would be an addition to the _Tinylog_ console writer too. It is only 4 LOC extra code in the console writer.
Of course the syntax of the property can be discussed, e.g.

- Have an extra property e.g. "`errlevel","ERROR" `or so. Properly it should  replace the "stream" property if present
- Have a combined property like above `"stream", "err@ERROR"` or `"stream","ERROR@err"`
- Have a special syntax in the stream property "`stream", "@ERROR"` or `"level:ERROR"` (since the steam "err" is redundant in my example as you only define the cutoff between two)

This is very optional and here just as an idea to consider whether this would be an addition or not. Just close the issue if it is too optional.

**Comment by pmwmedia** [comment]
I like the `err@ERROR` syntax as it easy to understand and readable. However, the current configuration options `err` and `out` should still work for compatibility reasons.

**Comment by Git5000** [comment]
Yes the old syntax has to work. It is the same as with the tags and levels. If a @ is present the level is extracted otherwise the default level is kept (so all or none).

**Comment by Git5000** [comment]
Just a note on this one: I did not forget this issue and will implement it resp. copy my implementation to the github code base - But I had a bit limited time recently.

**Comment by pmwmedia** [comment]
No rush :)
