### ISSUE TITLE
Package specific log levels (tinylog 2.1.2)

### ISSUE THREAD

**Issue by mattjlewis** [tinylog-org/tinylog#182]
I can't see to get package specific log levels working - see my sample application here:
https://github.com/mattjlewis/tinylog-test

Am I doing something wrong? I was following the documentation here: https://tinylog.org/v2/configuration/#severity-level

**Comment by mattjlewis** [comment]
Apologies - I think I've worked it out. I was getting confused between the writer's max log level and the configured log levels.

**Comment by pmwmedia** [comment]
Can we improve the configuration to avoid confusing?

**Comment by mattjlewis** [comment]
It would be helpful if the documentation could be updated, in particular in the Severity Level section, as well as providing examples. You have this text in the Configuration page:

> If multiple writers are used, it is possible to define particular severity levels for them. In this case, these writers will only output log entries with the defined severity level or higher.

This could possibly be changed to something like:

> It is also possible to define the maximum logging level for a particular writer to limit the log messages output by that writer. For example, setting `writer1.level = info` and `writer2.level = warn` alongside `level = debug` results in writer1 only logging messages at level info and higher and writer2 logging at warn or higher.
Note that the behaviour of `writer.level = xxx` is different to `level = xxx` - `writer.level` defines the maximum log level for that cannot be overridden for specific packages, whereas `level` defines the default log level that can have package specific log level overrides.

I know this is obvious when you think about it but it tripped me up for a while as I was originally setting `writer.level` rather than simply `level` thinking that I could still enable debug output for specific packages. As noted, the behaviour is different between `writer.level` and `level` hence my initial confusion.

It would also be great if you provide something like my trivial example application to illustrate this alongside your other example configurations. An Examples page in your Documentation would also be good.

**Comment by pmwmedia** [comment]
@mattjlewis Thank you very much for your great and well written documentation update. I really like your improvements and have exchanged the paragraph as you have suggested: https://tinylog.org/v2/configuration/#severity-level
