### ISSUE TITLE
Android bugs

### ISSUE THREAD

**Issue by mirmajeed1** [tinylog-org/tinylog#184]
**Describe the bug**
Does this works for Android? as I only been able to get basic logging. {date} does not work, appending to same log file does not work, everytime the app starts it delete the old file and creates a new one.

**To Reproduce**
writer1       = console
writer1.level = debug

writer2       = file
writer2.file  = /data/appname/files/logs/applogs.{date}.txt
writer2.level = debug
writer.format   = {level}: {message} 
writer.charset  = UTF-8
writer.append   = true
writer.buffered = true

**Environment**
tinylog version: 2.1.2
Java version: Java 8

**Comment by pmwmedia** [comment]
You should use the `rolling file` writer.

```
writer2 = rolling file
```

**Comment by mirmajeed1** [comment]
wow! you were right, that fixed the date issue, however I am still having the issue where everytime the app starts it creates a new file and does not append into the same date's file. Here is my updated tinylog.properties

writer1       = console
writer1.level = debug

writer2       = rolling file
writer2.file  = /data/data/appname/files/logs/applogs-{date:yyyy-MM-dd}.txt
writer2.level = info
writer2.format   = {date} \t {level}: {message} \t [{thread}] {class}.{method}()
writer2.charset  = UTF-8
writer2.append   = true
writer2.buffered = false

**Comment by pmwmedia** [comment]
Instead of the `append` property, the rolling file writer uses `policies`. If you don't define any policy, tinylog will use the `startup` policy by default (see https://tinylog.org/v2/configuration/#rolling-file-writer). For avoiding running out of disk space, you need to define at least one policy. You could use the `daily` or `size` policy for example.

```
writer2 = rolling file
writer2.file = /data/data/appname/files/logs/applogs-{date:yyyy-MM-dd}.txt
writer2.level = info
writer2.format = {date} \t {level}: {message} \t [{thread}] {class}.{method}()
writer2.charset = UTF-8
writer2.policies = size: 512mb
writer2.buffered = false
```

**Comment by mirmajeed1** [comment]
Yes, Big thank you!!
