### ISSUE TITLE
Tinylog and Proguard

### ISSUE THREAD

**Issue by prfarlow1** [tinylog-org/tinylog#186]
I'm interested in using Tinylog in my project, but I use Proguard so most class and file names are obfuscated in release builds. I'm worried that if a user had a problem, then sent me their logs, all of the log tags for classes would be obfuscated. What do you recommend for projects that use Proguard? How could I maintain those tags? Can I manually set the tag name (which by convention is usually the class name) that will show up in the logged output file?

**Comment by prfarlow1** [comment]
Sorry, I realize now that I am using the word "tag" a bit differently than the Tinylog documentation uses it. I don't want to add tags to logs, I want to ensure the format pattern, which by default is `{date} [{thread}] {class}.{method}()\n{level}: {message}`, has the correct class name, even when Proguard changes the class name.

**Comment by pmwmedia** [comment]
You could configure Proguard to keep the class and method names of your own classes:
`-keep class org.mypackage.** { <methods>; }`

If you configure only the root package of your own classes, Proguard can still shorten all class and method names from your used dependencies. So, Proguard will be still able to drastically reduce the final app size.
