### ISSUE TITLE
tinylog_extra_stuff

### ISSUE THREAD

**Issue by Git5000** [tinylog-org/tinylog#187]
I promised you a while ago an example for the YAML and JSON properties configuration loader. I finally managed to upload it to 
https://github.com/Git5000/tinylog_extra_stuff.

Have a look at it if you like.  Note, that the repository layout and POM are copied 1:1 from your tinylog project. Hope that is ok.

The examples were based on a bit previous version of our joint work on the configuration loader. We renamed a few things afterwards in the process of releasing them.  I tried to add these changes now in the examples but I did not test them too well. They seem to still work though (but I am not 100% sure). But even if not, the main idea of the loaders is still there.

The module requires a tinylog **2.3** build (which does not exist in public yet, so you have to first build it locally if you want the examples to run).

Main files are:
* JsonConfigurationLoader: Implementation JSON
* YamlConfigurationLoader: Implementation YAML
* ExampleConfigurationLoaderJson: Example using JSON
* ExampleConfigurationLoaderYaml: Example using YAML
* The configuration files in resources

To not spam your issue list you can of course delete this issue after having a look at the https://github.com/Git5000/tinylog_extra_stuff repo. 
But I didn't know any other easy way of communicating this information to you.

**Comment by pmwmedia** [comment]
These are great news! Especially, I like the YAML configuration. Looking forward for a Maven artifacts soon. Feel free to add your project to https://tinylog.org/v2/external-resources/.

> Have a look at it if you like. Note, that the repository layout and POM are copied 1:1 from your tinylog project. Hope that is ok.

tinylog is open source. You are welcome to copy :)

> The module requires a tinylog 2.3 build

On the weekend, I can publish the current v2.3 branch of tinylog as first milestone, if it will make it easier for your development.

**Comment by Git5000** [comment]
Thank you for your feedback. Initially the code was only meant as example for people to implement their own loader. Therefore I put no emphasis on the format layout. However I read your issue comments and they make good sense. While having the example code I can just as well make the format proper. Since it is good what you suggest,  I will have a look at it and change it accordingly.

I have little time at the moment so I doubt I can do anything before Christmas. This also means you do not need to hurry with 2.3.

**Comment by Git5000** [comment]
I finally managed to change the YAML and JSON configuration loaders to support nested properties as suggested by you. I also added the Github page for the loaders to your external resources page as suggested by you above.

I think this issue here can be closed.

**Comment by pmwmedia** [comment]
These are great news :) Thank you very much for awesome contribution!

Is there any chance that you can publish your YAML and JSON configuration loaders on [Maven Central Repository](https://search.maven.org/)? Your loaders are ready for real usage and their availability on Maven Central Repository would make it much more easy for other users to use them?

**Comment by Git5000** [comment]
Making the loaders available is not so straightforward. The example includes the dependent libraries for both JSON and YAML. However, if someone wants a YAML loader he probably does not want to include the gson libraries as well. So to be useful one probably would need one JAR published for JSON and one for YAML. However, then we have a jar published for one configuration loader *.java file only. This seems to be an overkill too. So maybe it is easier if interested parties just copy the one configuration file as Java source into their projects?

**Comment by pmwmedia** [comment]
My experience is that people rarely use code that they have to copy from somewhere. You have already invested much time in tinylog itself and in the both configuration loaders in your repository. I would find it a pity, if nobody would use your both configuration loader after you invested so much effort in them with great results.

**Comment by Git5000** [comment]
But then the only useful option is two jar file uploads. I would not like mixing **json** and **yaml** libraries in a project needing only one of them for no real reason. Since you think it beneficial to upload jars over source code, I will look into making two jars then.

**Comment by pmwmedia** [comment]
@Git5000: Your repository made into the latest JAXenter article: https://jaxenter.de/java/tinylog-2-3-100145
