### ISSUE TITLE
Benchmarks without location information

### ISSUE THREAD

**Issue by A248** [tinylog-org/tinylog#193]
The benchmarks use `{date:yyyy-MM-dd HH:mm:ss} [{thread}] {class}.{method}(): {message}` as the logging format. For log4j2, {class} and {method} translate to %C and %M, and indeed the log4j2 benchmark uses this. ([link](https://github.com/pmwmedia/tinylog/blob/4bc4c9a6e6ed979f2e67da67be9078f18e64d9d6/benchmarks/src/main/java/org/tinylog/benchmarks/logging/Log4j2Benchmark.java#L109))

Log4j2 says that such "location information" significantly slows down the logging process:
> If one of the layouts is configured with a location-related attribute like HTML locationInfo, or one of the patterns %C or %class, %F or %file, %l or %location, %L or %line, %M or %method, Log4j will take a snapshot of the stack, and walk the stack trace to find the location information.
>
> This is an expensive operation: 1.3 - 5 times slower for synchronous loggers. Synchronous loggers wait as long as possible before they take this stack snapshot. If no location is required, the snapshot will never be taken.
>
> The performance impact of taking a stack trace snapshot is even higher for asynchronous loggers: logging with location is 30-100 times slower than without location. For this reason, asynchronous loggers and asynchronous appenders do not include location information by default.
> https://logging.apache.org/log4j/2.x/manual/layouts.html#LocationInformation

Considering this, anyone who is performance-conscious and uses log4j2 will surely not use the class or method name.

It would be sensible to include a benchmark which does not use this information.

**Comment by pmwmedia** [comment]
My first draft for the new benchmark page including benchmarks for three different levels of caller information: https://tinylog.org/v2/new-benchmark/

Feedback is welcome :)

**Comment by pmwmedia** [comment]
Hi @A248, could you take it a look on the new benchmark? Is the [new benchmark page](https://tinylog.org/v2/new-benchmark/) comprehensible? Does it provide the required information for new tinylog users?

**Comment by A248** [comment]
It looks good! Very comprehensive and the explanations will be helpful to anyone looking at the benchmarks. For one thing I might change, on the subject of latency which you mention, perhaps I'd add some benchmarks to show-case the trade-off. I'd be willing to PR this sometime over the next few weeks.

**Comment by pmwmedia** [comment]
@A248 Thank your review! I agree about adding a latency benchmark.

**Comment by pmwmedia** [comment]
I have added a new issue for adding a latency benchmark: #202

@A248: Looking forward to your pull request :)
