### ISSUE TITLE
(Kotlin) Overload resolution ambiguity. All these functions match.

### ISSUE THREAD

**Issue by open-schnick** [tinylog-org/tinylog#198]
**Describe the bug**
When using `Logger.info("someString")` or legit any function the kotlin compiler will fail because of  
```
Overload resolution ambiguity. All these functions match.
- public open fun debug(message: Any!): Unit defined in org.tinylog.Logger
- public open fun debug(message: String!, vararg arguments: Any!): Unit defined in org.tinylog.Logger
- public open fun debug(message: String!, vararg arguments: Supplier<*>!): Unit defined in org.tinylog.Logger
```
**To Reproduce**
1. Use kotlin
2. Use mvn
3. Use `Logger.info("something")`

**Environment**
tinylog version: 2.2.1
JRE: 1.8
JDK: 14

**Comment by open-schnick** [comment]
Same Error with info, debug, warn btw.

**Comment by pmwmedia** [comment]
Have you added the Maven artifact `tinylog-api-kotlin` and ensured that you are using `org.tinylog.kotlin.Logger` instead of  `org.tinylog.Logger`?

**Comment by open-schnick** [comment]
that worked. Thanks for the fast response <3
