### ISSUE TITLE
tinylog does not create new file when max file size definied is reached

### ISSUE THREAD

**Issue by thebatu** [tinylog-org/tinylog#203]
I have the following configurations for an Android project. I am logging to 2 files that I set the size with the property policy to 10000kb, however, file size is not respected and no new files are being created when 10 mb is reached, what I am missing here. tinylog ver 2.1

`writer1          = logcat
writer1.level    = info
writer1.format   = {message}

writer2          = file
writer2.level    = warn
writer2.file     = #{tinylog.directory}/warnlog.txt
writer2.append   = true
writer2.backups  = 2
writer2.format   = {date: HH:mm:ss.SSS} {class} {line} {level}: {message}
writer2.policies = size: 10mb
writer2.buffered = true
writer2.writingthread = true

writer3          = file
writer3.level    = info
writer3.file     = #{tinylog.directory2}/infolog.txt
writer3.append   = true
writer3.backups  = 2
writer3.format   = {date: HH:mm:ss.SSS} {class} {line} {level}: {message}
writer3.policies = size: 10mb
writer3.buffered = true
writer3.writingthread = true`

**Comment by pmwmedia** [comment]
just use `rolling file` instead `file`

**Comment by thebatu** [comment]
Yes, thanks.
