### ISSUE TITLE
Tinylog only logs from a different thread

### ISSUE THREAD

**Issue by thebatu** [tinylog-org/tinylog#204]
Hello, I have the following configuration for an Android project using tinylog 2.1.
Log files are being created on the internal storage, but the problem is that tinylog only logs if I log from a different thread! otherwise the file size remains 0 B. 

if I remove the for loop in the init function it will not log
````
private void initTinyLog(Context context)
{
        System.setProperty("tinylog.directory", context.getFilesDir() + "/" + mManualLogsDir);
        System.setProperty("tinylog.directory2", context.getFilesDir() + "/" + mManualLogsDir);
                int count = 1000;
                ScheduledFuture<?> future = FleetExecutor.getData().schedule(new Runnable()
                {
                    @Override
                    public void run()
                    {
                        for (int i = 0; i < count; i++)
                            Logger.warn("this is a warn message");
                    }
                }, 0, TimeUnit.SECONDS);
        Logger.info("Hello World!");
        Logger.warn("First Hello WARN!");
}
````

my tinylog.properties
````
writer1          = logcat
writer1.level    = info
writer1.format   = {message}

writer2          = rolling file
writer2.level    = warn
writer2.file     = #{tinylog.directory}/warnlog.txt
writer2.append   = true
writer2.backups  = 2
writer2.format   = {date: HH:mm:ss.SSS} {class} {line} {level}: {message}
writer2.policies = startup, size: 10mb
writer2.buffered = true
writer2.writingthread = true

writer3          = rolling file
writer3.level    = info
writer3.file     = #{tinylog.directory2}/infolog.txt
writer3.append   = true
writer3.backups  = 2
writer3.format   = {date: HH:mm:ss.SSS} {class} {line} {level}: {message}
writer3.policies = startup, size: 10mb
writer3.buffered = true
writer3.writingthread = true
```

**Comment by thebatu** [comment]
```
`writer3.buffered = true
`
```
this line breaks the configuration file and writing operation dies silently.

**Comment by pmwmedia** [comment]
Hi @thebatu,

If you want to use the writing thread for asynchronous logging, you can replace `writer2.writingthread = true` and `writer3.writingthread = true` with `writingthread = true`. In tinylog, the writing thread can be only activated globally, not for a particular writer.

With your example configuration, tinylog does use buffered writing but not the writing thread for both rolling file writers. Therefore, both writers write all log entries into the buffer. However, the log entries from the buffer are written to the log file itself only when either the buffer is full (64KB) or the application terminates.

However, if you will activate the writing thread globally, the writing thread will write the log entries from the buffer also regularly during run time.

**Comment by thebatu** [comment]
@pmwmedia 
Thanks for the detailed explanation on how tinylog buffer and threads operate. This should be added to the docs.
cheers.
