### ISSUE TITLE
GzipFileConverter is not accessible

### ISSUE THREAD

**Issue by ds67** [tinylog-org/tinylog#211]
**Describe the bug**
When using a self defined ConfigurationLoader and add rollgin files with gzip support the following error message is giben:
LOGGER ERROR: Constructor of service implementation 'org.tinylog.converters.GzipFileConverter' is not accessible

**To Reproduce**
1. Use a self defined ConfigurationLoader in a modules based project
2. Load file with
writer = rolling file
writer.convert  = gzip
3. watch out for log message

**Environment**
tinylog version: 2.3.1
Java version: 11

**Comment by pmwmedia** [comment]
@ds67: Could you test if my fixes work for you before I will publish them as tinylog 2.3.2?

I have fixed the access to GzipFileConverter and the loading of configuration loaders including the Javadoc.

[jboss-tinylog-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/files/6602853/jboss-tinylog-2.3-SNAPSHOT.zip)
[jcl-tinylog-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/files/6602854/jcl-tinylog-2.3-SNAPSHOT.zip)
[jul-tinylog-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/files/6602855/jul-tinylog-2.3-SNAPSHOT.zip)
[log4j1.2-api-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/files/6602856/log4j1.2-api-2.3-SNAPSHOT.zip)
[slf4j-tinylog-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/files/6602858/slf4j-tinylog-2.3-SNAPSHOT.zip)
[tinylog1.3-api-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/files/6602859/tinylog1.3-api-2.3-SNAPSHOT.zip)
[tinylog-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/files/6602860/tinylog-2.3-SNAPSHOT.zip)
[tinylog-jboss-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/files/6602861/tinylog-jboss-2.3-SNAPSHOT.zip)
[tinylog-jul-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/files/6602862/tinylog-jul-2.3-SNAPSHOT.zip)
[tinylog-kotlin-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/files/6602863/tinylog-kotlin-2.3-SNAPSHOT.zip)
[tinylog-scala-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/files/6602864/tinylog-scala-2.3-SNAPSHOT.zip)

**Comment by ds67** [comment]
Hi Martin,

from my perspective it works. Here is what I did:

* started my app, with -D parameter -> works
* remove -D systemproperty & restart -> intitialization failed
* downloaded tinylog-2.3-SNAPSHOT.zip
* replaced tinylog-impl.jar
* restarted -> configuration was done, success
* included gzip parameter & restart
* zipping works, success

I tested on Linux / Java 11 only.

Jens


Am Samstag, 5. Juni 2021, 18:29:59 CEST schrieb Martin Winandy:
> @ds67: Could you test if my fixes work for you before I will publish them as
> tinylog 2.3.2?
> 
> I have fixed the access to GzipFileConverter and the loading of
> configuration loaders including the Javadoc.
> 
> [jboss-tinylog-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/file
> s/6602853/jboss-tinylog-2.3-SNAPSHOT.zip)
> [jcl-tinylog-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/files
> /6602854/jcl-tinylog-2.3-SNAPSHOT.zip)
> [jul-tinylog-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/files
> /6602855/jul-tinylog-2.3-SNAPSHOT.zip)
> [log4j1.2-api-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/file
> s/6602856/log4j1.2-api-2.3-SNAPSHOT.zip)
> [slf4j-tinylog-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/fil
> es/6602858/slf4j-tinylog-2.3-SNAPSHOT.zip)
> [tinylog1.3-api-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/fi
> les/6602859/tinylog1.3-api-2.3-SNAPSHOT.zip)
> [tinylog-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/files/660
> 2860/tinylog-2.3-SNAPSHOT.zip)
> [tinylog-jboss-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/fil
> es/6602861/tinylog-jboss-2.3-SNAPSHOT.zip)
> [tinylog-jul-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/files
> /6602862/tinylog-jul-2.3-SNAPSHOT.zip)
> [tinylog-kotlin-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/fi
> les/6602863/tinylog-kotlin-2.3-SNAPSHOT.zip)
> [tinylog-scala-2.3-SNAPSHOT.zip](https://github.com/tinylog-org/tinylog/fil
> es/6602864/tinylog-scala-2.3-SNAPSHOT.zip)

**Comment by pmwmedia** [comment]
Hi Jens,

Thanks for testing! I'm going to release tinylog 2.3.2 today.
