### ISSUE TITLE
[Android] Disable all logs for release variant

### ISSUE THREAD

**Issue by WebTiger89** [tinylog-org/tinylog#212]
Hello,
is there a flag or something so I can disable all logs when building the release variant in android. Something like this:

`if (BuildConfig.DEBUG) {
    Timber.plant(new DebugTree()); } // this is how Timber library is handling it
`

**Comment by pmwmedia** [comment]
There are even two ways to disable any logging in release builds:

1. Replace your "tinylog.properties" file with any properties file containing the line `level = off`
2. Execute `if (!BuildConfig.DEBUG) { Configuration.set("level", "off"); }` before issuing any log entries
