### ISSUE TITLE
LOGGER ERROR: Failed to write log entry (java.lang.ArrayIndexOutOfBoundsException: Array index out of range: -1)

### ISSUE THREAD

**Issue by dbacinski** [tinylog-org/tinylog#214]
**Describe the bug**
While running app on Kubernetes logger randomly starts failing with:

`LOGGER ERROR: Failed to write log entry <original message here> (java.lang.ArrayIndexOutOfBoundsException: Array index out of range: -1)`

```
#file
writer1=rolling file
writer1.policies=daily
writer1.backups=60
writer1.label="timestamp: yyyy-MM-dd_HH-mm-ss"
writer1.format="{date} [{level}] [{thread}] {file}:{line} - {message}"
#console
writer2=console json
writer2.level=debug
writer2.field.severity=level
writer2.field.timestamp={date:yyyy-MM-dd'T'HH:mm:ss.SSSXXX}
writer2.field.thread=thread
writer2.field.ref={file}:{line}
writer2.field.file=file
writer2.field.class=class
writer2.field.message=message
```

log is coming from here:
https://github.com/tinylog-org/tinylog/blob/506bf901b7b015d4ab8d4fb615ce77758402da1d/tinylog-impl/src/main/java/org/tinylog/core/TinylogLoggingProvider.java#L253

any ideas why? or how to debug it? 

would be great to add to this error log which writer has failed.

**Environment**
tinylog version: 2.3.1
Java version: 1.8
Kotlin: 1.4.32

**Comment by dbacinski** [comment]
it works for some time (hours, even days) and then starts failing

could it be that rolling files is failing?

**Comment by pmwmedia** [comment]
The rolling file writer is used by thousands of users and I have never seen such error from this writer. Of course, I can't guarantee that this error isn't thrown from the rolling file writer nevertheless. However, it is more likely that the cause of the error is anywhere in the console JSON writer. Could you try to catch any exception in the write() method of the console JSON writer and outputting the whole stack trace?

**Comment by dbacinski** [comment]
Yes, sorry I did that and the exception is coming from the console json writer.

**Comment by pmwmedia** [comment]
I'm glad that to read that the issue is solved :)
