### ISSUE TITLE
Logger Run time configuration

### ISSUE THREAD

**Issue by salmanmpp** [tinylog-org/tinylog#215]
How do we change the logger configuration for the 2.3.2 version?

**Comment by pmwmedia** [comment]
tinylog's native logging provider does not support configuration changes after issuing the first log entry. However, you could create your custom logging implementation by extending or wrapping tinylog's native logging provider [TinylogLoggingProvider](https://github.com/tinylog-org/tinylog/blob/v2.3/tinylog-impl/src/main/java/org/tinylog/core/TinylogLoggingProvider.java) and add your required runtime changing logic by yourself.

You can find a documentation how to register and use a custom logging provider on the tinylog website: https://tinylog.org/v2/extending/#custom-logging-provider

**Comment by salmanmpp** [comment]
I got  java.lang.UnsupportedOperationException: Configuration cannot be changed after applying to tin log this exception

**Comment by salmanmpp** [comment]
my code is 
lass ReconfigurableLoggingProvider : TinylogLoggingProvider() {

    private var realProvider: TinylogLoggingProvider = TinylogLoggingProvider()
    lateinit var logLevel: String
    var fileSize: Int = 0

    fun reload() {
        realProvider.shutdown()
        val method = Configuration::class.java.getDeclaredMethod("load")
        method.isAccessible = true
        val map = method.invoke(null) as MutableMap<String, String>
        map["level"] = logLevel
        map["writer2.policies"] = "size:${fileSize}kb"
        Configuration.replace(map)
          realProvider = TinylogLoggingProvider()
    }

    override fun getContextProvider(): ContextProvider {
        return realProvider.contextProvider
    }

    override fun getMinimumLevel(): Level {
        return Level.TRACE
    }

    override fun getMinimumLevel(tag: String?): Level {
        return Level.TRACE
    }

    override fun isEnabled(depth: Int, tag: String?, level: Level?): Boolean {
        return realProvider.isEnabled(depth+1, tag, level)
    }

//    override fun log(
//        depth: Int,
//        tag: String?,
//        level: Level?,
//        exception: Throwable?,
//        obj: Any?,
//        vararg arguments: Any?
//    ) {
//        realProvider.log(depth+1, tag, level, exception, obj, arguments)
//    }
//
//    override fun log(
//        loggerClassName: String?,
//        tag: String?,
//        level: Level?,
//        exception: Throwable?,
//        obj: Any?,
//        vararg arguments: Any?
//    ) {
//        realProvider.log(loggerClassName, tag, level, exception, obj, arguments)
//    }

    override fun shutdown() {
        realProvider.shutdown()
    }
    @JvmName("setLogLevel1")
    fun setLogLevel(logLevel:String){
        this.logLevel = logLevel
    }
    @JvmName("setFileSize1")
    fun setFileSize(size:Int){
        this.fileSize = size
    }
}

**Comment by pmwmedia** [comment]
Here is a logging provider that can change the severity level at runtime:

```kotlin
import org.tinylog.Level
import org.tinylog.core.TinylogLoggingProvider
import org.tinylog.format.MessageFormatter

class DynamicLevelLoggingProvider : TinylogLoggingProvider() {

    @Volatile
    var activeLevel: Level = Level.TRACE;

    override fun isEnabled(depth: Int, tag: String?, level: Level?): Boolean {
        return activeLevel <= level && super.isEnabled(depth + 1, tag, level)
    }

    override fun log(
        depth: Int,
        tag: String?,
        level: Level?,
        exception: Throwable?,
        formatter: MessageFormatter?,
        obj: Any?,
        vararg arguments: Any?
    ) {
        if (activeLevel <= level) {
            super.log(depth + 1, tag, level, exception, formatter, obj, *arguments)
        }
    }

    override fun log(
        loggerClassName: String?,
        tag: String?,
        level: Level?,
        exception: Throwable?,
        formatter: MessageFormatter?,
        obj: Any?,
        vararg arguments: Any?
    ) {
        if (activeLevel <= level) {
            super.log(loggerClassName, tag, level, exception, formatter, obj, *arguments)
        }
    }

}
```

Usage example:

```kotlin
fun main() {
    val provider = org.tinylog.provider.ProviderRegistry.getLoggingProvider() as DynamicLevelLoggingProvider

    provider.activeLevel = Level.WARN
    Logger.info("1") // Ignored

    provider.activeLevel = Level.DEBUG
    Logger.info("2") // Output
}
```

Please be aware that the `level` property in `tinylog.properties` will be still used as minimum severity level. If you need really all severity levels at runtime, you can just set it to `trace`. If you know that you will never active some severity levels, you can use a higher severity level and benefit from performance improvements.

```properties
provider      = dynamic level
level         = trace

writer        = console
writer.format = {level}: {message}
```

For changing the file size at runtime, I would implement a dynamic file size policy. This is easier to implement and you avoid some potential concurrency issues.

**Comment by pmwmedia** [comment]
Here is my dynamic size policy implementation:

```kotlin
class DynamicSizePolicy : Policy {

    companion object {
        @Volatile
        var maxSize: Int = 64 * 1024 // Maximum file size in bytes (default 64KB)
    }

    private var count: Long = 0

    @Suppress("unused")
    constructor() { // Default constructor is required by ProGuard
    }

    @Suppress("unused")
    constructor(argument: String?) { // Argumented constructor is required by tinylog
    }

    override fun continueExistingFile(path: String): Boolean {
        val file = File(path)
        count = file.length()
        return count <= maxSize
    }

    override fun continueCurrentFile(entry: ByteArray): Boolean {
        count += entry.size.toLong()
        return count <= maxSize
    }

    override fun reset() {
        count = 0
    }

}
```

My `tinylog.properties`:

```properties
provider        = dynamic level
level           = trace

writer          = rolling file
writer.file     = app_{count}.log
writer.policies = dynamic size
writer.format   = {level}: {message}
```

Usage example for my tests:

```kotlin
fun main() {
    for (i in 0 until 100_000) {
        if (i == 40_000) {
            DynamicSizePolicy.maxSize = 1 * 1024;
        }

        if (i == 50_000) {
            DynamicSizePolicy.maxSize = 64 * 1024 * 10;
        }

        Logger.info("Test")
    }
}
```

**Comment by salmanmpp** [comment]
Thank you for the timely reply It saves me

**Comment by aberman** [comment]
I am trying to completely configure TinyLog at runtime and, unfortunately, it's not really doable without copying the source code in TinylogLoggingProvider.  The code does not allow a subclass to override the values of the private fields, like writers.  If instead all log methods in that class accessed those fields via a getter method or a setter for those fields existed, I could extend the provider and override the methods (or call the setter) so I wouldn't have to copy the code.  For example, in getMinimumLevel((), the method uses the private writers field, but if it instead called getWriters(), I could override it so I can provide my own set of dynamic writers.  

Is there any other way to do it?

**Comment by pmwmedia** [comment]
@aberman Just create a new issue here and describe there exactly what code need to be change for which reason.
