### ISSUE TITLE
Android Shared User Not Working 

### ISSUE THREAD

**Issue by epsmae** [tinylog-org/tinylog#216]
**Describe the bug**
`android:sharedUserId="android.uid.my_shared_user"`
As soon as the shared user is set in the AndroidManifest.xml the following error occurs on the first log entry:

`W/System.err: LOGGER WARN: No logging framework implementation found in classpath. Add tinylog-impl.jar for outputting log entries.`

This is reproduceable without proguard.
```
        release {
            debuggable true
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
```

I use the following config.
```
writer1 = rolling file
writer1.file = #{logs.folder}/my_app_{date: yyyy-MM-dd}.log
writer1.backups = 10
writer1.policies = daily, size: 8000KB
writer1.format = {date:yyyy-MM-dd HH:mm:ss:sss} {message}
writer2 = logcat
writer2.format = {message}
```

An set the the logs folder like:
```
File appDirectory = new File(app.getApplicationInfo().dataDir);
File logDirectory = new File(appDirectory, "logs");
System.setProperty("logs.folder", logDirectory.getAbsolutePath());
```

**To Reproduce**
1. Set android:sharedUserId in AndroidManifest.xml

**Environment**

```
compileSdkVersion 30
buildToolsVersion "30.0.3"
minSdkVersion 23
targetSdkVersion 30
```

```
implementation 'org.tinylog:tinylog-api:2.3.2'
runtimeOnly 'org.tinylog:tinylog-impl:2.3.2'
```

**Comment by pmwmedia** [comment]
Unfortunately, I'm not able to reproduce this issue.

My MainActivity:
```java
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        File appDirectory = new File(getApplicationInfo().dataDir);
        File logDirectory = new File(appDirectory, "logs");
        System.setProperty("logs.folder", logDirectory.getAbsolutePath());

        Logger.info("Hello World!");
        Logger.info("Logs can be found in \"{}\"", logDirectory);

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
     }

}
```

My AndroidManifest:
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.tinylog.demo">

    <application
        android:allowBackup="false"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:sharedUserId="android.uid.my_shared_user"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
```

Output on runtime:
```
2021-07-27 12:51:09.091 6267-6267/org.tinylog.android.demo I/MainActivity: Hello World!
2021-07-27 12:51:09.092 6267-6267/org.tinylog.android.demo I/MainActivity: Logs can be found in "/data/user/0/org.tinylog.android.demo/logs"
```

**Comment by pmwmedia** [comment]
My full demo project: 
[tinylog-android-example.zip](https://github.com/tinylog-org/tinylog/files/6884887/tinylog-android-example.zip)

**Comment by epsmae** [comment]
@pmwmedia thanks for the fast response.
I have the same issue in your application if I set the on the manifest tag where it should be.
[Android Manifest](https://developer.android.com/guide/topics/manifest/manifest-element)

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.tinylog.demo"
    android:sharedUserId="android.uid.my_shared_user">
...
```

`2686-2686/org.tinylog.android.demo W/System.err: LOGGER WARN: No logging framework implementation found in classpath. Add tinylog-impl.jar for outputting log entries.`

Interesting is that there is an additional log entry which I missed so far.
`2686-2686/org.tinylog.android.demo W/ActivityThread: ClassLoader.getResources: The class loader returned by Thread.getContextClassLoader() may fail for processes that host multiple applications. You should explicitly specify a context class loader. For example: Thread.setContextClassLoader(getClass().getClassLoader());`

If I add these line in front of the "Logger.info("Hello World!")" it works.
`Thread.currentThread().setContextClassLoader(getClass().getClassLoader());`

Probably you can't do much about that in the library as it seems to be an android thing right?
However, I am not exactly aware of the side effects of shareUserId, will try to find some more info.

**Comment by pmwmedia** [comment]
> I have the same issue in your application if I set the on the manifest tag where it should be.
> [Android Manifest](https://developer.android.com/guide/topics/manifest/manifest-element)

Thanks for the correction! I have never used `android:sharedUserId` before.

> If I add these line in front of the "Logger.info("Hello World!")" it works.
> `Thread.currentThread().setContextClassLoader(getClass().getClassLoader());`
> 
> Probably you can't do much about that in the library as it seems to be an android thing right?
> However, I am not exactly aware of the side effects of shareUserId, will try to find some more info.

This is indeed a very strange side effect of `android:sharedUserId`. Maybe we can find a way for setting the correct class loader for tinylog automatically?

**Comment by pmwmedia** [comment]
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     package="com.example.tinylog.demo"
>     android:sharedUserId="android.uid.my_shared_user">
> ...
> ```

I'm not even able to install my example app in the emulator.

```
07/27 14:20:21: Launching 'app' on Pixel_3a_API_30_x86.
Installation did not succeed.
The application could not be installed: INSTALL_FAILED_SHARED_USER_INCOMPATIBLE
```

**Comment by epsmae** [comment]
I tested back in my application and it works like that.
I have only to set the class loader once before I log the first entry.
I have multiple activities and do the first log call in my derived class from Application.

May this is required on the first logger call as some initialization is done there?

Not sure if this should be in the library as it is security related.
Moreover sharedUserId is deprecated in Android API 29 [SharedUserId](https://developer.android.com/guide/topics/manifest/manifest-element#uid).

My application will run on a specific android device (with API 27) as a system app and won't be distributed over a store.

Thanks for your support, feel free to close the issue.

**Comment by epsmae** [comment]
> > ```
> > <manifest xmlns:android="http://schemas.android.com/apk/res/android"
> >     package="com.example.tinylog.demo"
> >     android:sharedUserId="android.uid.my_shared_user">
> > ...
> > ```
> 
> I'm not even able to install my example app in the emulator.
> 
> ```
> 07/27 14:20:21: Launching 'app' on Pixel_3a_API_30_x86.
> Installation did not succeed.
> The application could not be installed: INSTALL_FAILED_SHARED_USER_INCOMPATIBLE
> ```

Try to uninstall the old app first, and or change the shared user id and application id.

**Comment by pmwmedia** [comment]
@epsmae Thank you for your input and research results. I will fix this issue even `SharedUserId` is deprecated. tinylog 2,4 will use the class loader from the class, if it cannot find any service files via the context class loader of the current thread. This solution is very general and maybe also useful for other class loader related issues,
