### ISSUE TITLE
Support max-size style modifier to limit the length of the token

### ISSUE THREAD

**Issue by kropp** [tinylog-org/tinylog#219]
`min-size` style modifier is very helpful to maintain consistent column layout for tokens with known length.
However, there are cases when token length is unknown, but you still want to see it in a fixed width column.
Example would be thread or class name, which may be short or long and setting `min-size` too big to accommodate the longest message is just a waste of, err, space.

Therefore, I suggest `max-size` style modifier which limits the length of the token and trims it at the **beginning** (thread names are most likely to differ at the end).
And a convenient `size` modifier, which combines both `min-size` and `max-size` to achieve the desired effect of truly fixed width column.

**Comment by pmwmedia** [comment]
Solved by #220
