### ISSUE TITLE
Typo in method name

### ISSUE THREAD

**Issue by a1730** [tinylog-org/tinylog#222]
Thank you for Tinylog.
Tinylog fails to load in SLF4J alpha3+ because of a typo in the method name.

Compare slf4j api method named [getRequeste**d**ApiVersion](https://github.com/qos-ch/slf4j/blob/98f1f2f46533eba4945dda995225cf3c4017a075/slf4j-api/src/main/java/org/slf4j/spi/SLF4JServiceProvider.java#L42) to tinylog's implementation [getRequesteApiVersion](https://github.com/tinylog-org/tinylog/blob/c99d39f623a0f4ddd92600c1c0219c13d09ce543/slf4j-tinylog/src/main/java/org/tinylog/slf4j/TinylogSlf4jServiceProvider.java#L56)

Please notice the missing ``d`` in the implementation method name. You may want o make amends.

**Comment by pmwmedia** [comment]
This typo was fixed in SLF4J by commit https://github.com/qos-ch/slf4j/commit/7483a11dd6ba1398f4b51c2e673800325cc609fc.

I will update to the latest SLF4J 2 alpha version,
