### ISSUE TITLE
Wondering if it's possible to turn tinylog off during testing

### ISSUE THREAD

**Issue by davidmoshal** [tinylog-org/tinylog#231]
basically profiles (test, dev, prod, others?) that can be pre-pended to any config property:

eg:
test.console = false
dev.console = true
prod.console = true

or, alternatively, a way to specify the tinylog.properties file to use

**Comment by pmwmedia** [comment]
The recommended way to turn off tinylog during tests is putting a separate `tinylog.properties` into `src/test/resources` with the content `level = off`.
