### ISSUE TITLE
Proguard obfuscation fails with: "1 duplicate class definitions" and "there were 2 classes in incorrectly named files"

### ISSUE THREAD

**Issue by vidar-goran** [tinylog-org/tinylog#238]
I run the tiny-log 2.4.1 and tried also 2.4.0 I have the following specified in the proguard.conf file: 

-keepnames interface org.tinylog.**
-keepnames class * implements org.tinylog.**
-keepclassmembers class * implements org.tinylog.** { <init>(...); }

The following output is generated and obfuscation fails and thereby the whole build, do you have any suggestion how to solve the issue  

[proguard] Note: there were 1 duplicate class definitions.
 [proguard]       (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
 [proguard] Warning: there were 2 classes in incorrectly named files.
 [proguard]          You should make sure all file names correspond to their class names.
 [proguard]          The directory hierarchies must correspond to the package hierarchies.
 [proguard]          (http://proguard.sourceforge.net/manual/troubleshooting.html#unexpectedclass)
 [proguard]          If you don't mind the mentioned classes not being written out,
 [proguard]          you could try your luck using the '-ignorewarnings' option.

**Comment by pmwmedia** [comment]
What version of Proguard and "com.android.tools.build:gradle" do you use? Could you share all your dependencies?

**Comment by vidar-goran** [comment]
Hi we use proguard-maven-plugin version 2.2.0 and maven 3.6.3. I think I resolved the problem yesterday - proguard fails due to the module-info.class:es in tinylog-api-2.4.1.jar and tinylog-impl-2.4.1.jar. If I add **-dontwarn module-info**  to proguard.conf then obfuscation doesn't fail. I don't know if that is good solution or it could cause other issues but it seems to work. If you have any other recommendations please inform me

**Comment by pmwmedia** [comment]
I'm unable to reproduce the issue in tinylog's minimal Android example project: https://github.com/tinylog-org/tinylog-android-example. Any pull request is welcome that can cause the same warnings in this project.
