### ISSUE TITLE
Attempting to provide additional Context Variable Sources

### ISSUE THREAD

**Issue by kevind-wgu** [tinylog-org/tinylog#239]
I am attempting to implement a NewRelic's "Logs in Context" and "distributed tracing" solutions using the tinylog logger. For both of these solutions to work NewRelic expects log messages to contain NewRelic log properties that it will use to tie various applications threads together. This works very similarly  to MDC (ThreadContext) variables being put into the logs.

I am looking for a way to supply these NewRelic variables to the logs so that they can be emitted with log messages in the same way that a ThreadContext variable can be emitted in a log message `{context:name}`.

Reading through the docs I noticed that there is the concept of a `Custom Logging Provider` that theoretically would allow me to do define my own `ContextProvider`. BUT reading through the TinylogLoggingProvider solution I really don't want to write my own LoggingProvider, I simply want to add additional variables. I thought about creating my own provider that extends `TinylogLoggingProvider` and overrides the `getContextProvider` method but ultimately this doesn't work because `TinylogLoggingProvider` uses the context generated internally directly rather than using the `getContextProvider` method.

Anyway, any direction you could give me around extending tinylog such that I could get the variables into the log message would be helpful.

Thanks.

**Comment by pmwmedia** [comment]
`TinylogLoggingProvider` will support custom a `ContextProvider` in tinylog 2.5. You can just extend from `TinylogLoggingProvider` and pass your own `ContextProvider` without implementing any methods in the logging provider.

With tinylog 3, such custom context can be even easier implemented by a custom format pattern placeholder.

**Comment by kevind-wgu** [comment]
@pmwmedia Any chance you could make the BundleContextProvider class public as a part of this? I still want to use the TinyLogContextProvider in addition to the NewRelicLogProvider. In order to use both I will essentially have to rewrite the BundleContextProvider. If it were public I wouldn't need to rewrite it.
