### ISSUE TITLE
Separate log message FORMAT from Log Message DESTINATION

### ISSUE THREAD

**Issue by kevind-wgu** [tinylog-org/tinylog#240]
I would like to write JSON log messages to the console. Given Tinylog's current implementation this isn't possible.

Additional things that are not possible -- Using JSON message format and writing to a rolling log file.

**Comment by pmwmedia** [comment]
In tinylog 3, the output format (pattern or line-delimited JSON) is already separated from the writer (supported by console and file writer). A backporting to tinylog 2 is possible but will require some effort.

see [branch v3](https://github.com/tinylog-org/tinylog/tree/v3.0/tinylog-impl)

**Comment by kevind-wgu** [comment]
@pmwmedia I don't see a released version of v3. Is there a timeline to put out a released version? (Or an alpha or beta version?)

**Comment by pmwmedia** [comment]
There is no released version of tinylog 3 yet. Actually it's still pre-alpha, but the development is already quite advanced:

- logging API for Java is done and source code compatible with tinylog 2
- logging back-end is mainly only lacking of some file rolling functionality and JDBC writer

However, the documentation is still completely missing. It will take much effort to write it and without any documentation, there is no sense of releasing already a version of tinylog 3.

**Comment by pmwmedia** [comment]
Implemented in the up-coming version 3.0
