### ISSUE TITLE
Make org.tinylog.provider.BundleContextProvider public

### ISSUE THREAD

**Issue by kevind-wgu** [tinylog-org/tinylog#242]
Recently you added the ability to pass in your own ContextProvider into TinylogLoggingProvider. I plan on using this once released. I would like to combine the functionality in the TinylogContextProvider with my own context variables. It looks like this functionality is already implemented in BundleContextProvider but this class is package private. Any thoughts on making it public?

**Comment by pmwmedia** [comment]
Just made them public
