### ISSUE TITLE
About JDNI Support

### ISSUE THREAD

**Issue by justinjohnson02** [tinylog-org/tinylog#246]
As indicated in https://github.com/tinylog-org/tinylog/issues/235, will JDNI support only be limited to the configuration scope and **not message formatting?**

I just want to know if yall are steering clear of said messaging attack surface, as seen with Log4J 2.

Appreciate the Tinylog team 🙇🏾 👍🏾 !

**Comment by pmwmedia** [comment]
Yes, tinylog does only support JNDI in the initial and immutable configuration, and not in plain log messages. I'm totally aware about the security issues Apache Log4j 2 has faced. I have ensured that tinylog won't face similar security issues.

**Comment by justinjohnson02** [comment]
> Yes, tinylog does only support JNDI in the initial and immutable configuration, and not in plain log messages. I'm totally aware about the security issues Apache Log4j 2 has faced. I have ensured that tinylog won't face similar security issues.

Thanks @pmwmedia !

**Comment by WenTao-Love** [comment]
why not forbidden jndi?

**Comment by pmwmedia** [comment]
JNDI is not generally evil or dangerous. The way how Log4j supported JNDI in log messages was the root the security vulnerability that time. However, there are good use cases for using JNDI in the log configuration. This is secure and the only place, where tinylog supports JNDI.
