### ISSUE TITLE
Why use `org.tinylog.configuration.ServiceLoader`?

### ISSUE THREAD

**Issue by overheadhunter** [tinylog-org/tinylog#249]
I just spent hours trying to understand why the heck the ServiceLoader can't load my custom `ConfigurationLoader`, before I found out this is _not_ Java's ServiceLoader but a custom one that relies on reflection, which will not work in modular apps unless one `opens` the package containing the implementation to tinylog.

Furthermore, you can't `provide` a service in the `module-info` but _must_ use the legacy `META-INF/services` approach.

This isn't documented (in fact the documentation doesn't really cover modular apps at all). While the class mentions that this custom ServiceLoader is capable of providing args to the constructor, I didn't find any place where you made use of this. So it looks a bit like reinventing the wheel here, but relying on reflection and thereby weakening the strong encapsulation that the module system brought us. Furthermore reflection is a nightmare for AOT-compilation and requires special care and workarounds e.g. in conjunction with GraalVM.

So may I ask, why you decided to re-implement this?

**Comment by pmwmedia** [comment]
tinylog 2 uses a custom `ServiceLoader`, because Java's `ServiceLoader` supports only default constructors without any arguments. When tinylog 2 was developed, Java 9, modules, and GraalVM weren't a thing yet.

However, tinylog 3 uses Java's `ServiceLoader` to avoid all the issues you have mentioned. The disadvantage is that we need for all services an additional builder class for passing the required arguments. This requires some boilerplate code that will increase the source code of tinylog 3. The Java logging API and all writers but the JDBC writer are already developed, the rest is still under development for tinylog 3.

**Comment by overheadhunter** [comment]
I see, thanks for clarifying. Is there a roadmap for 3.x already? I don't dare asking for an ETA 😅

**Comment by pmwmedia** [comment]
tinylog 3 is a completely redevelopment of tinylog from scratch.

## Current state
- **tinylog-api**: done and ready, source code compatible with the logging API of tinylog 2.x
- **tinylog-api-kotlin**: `TaggedLogger` done but `Logger` still under development, source code compatible with the Kotlin logging API of tinylog 2.x
- **tinylog-impl**: almost done as only the `JdbcWriter` is still missing, the configuration is similar but not the same as for tinylog 2
- third-party logging APIs and server adapters: almost completely missing, only **slf4j-tinylog** still exists as Maven module but without any source code yet
- Documentation is still completely missing
- [Branch v3](https://github.com/tinylog-org/tinylog/tree/v3.0) does compile (`mvn install`). The example in the [README](https://github.com/tinylog-org/tinylog/blob/v3.0/readme.md) works. tinylog 3 could already be used in a custom project, if you install it to the local Maven repository by yourself and mind the limitations above.

## Roadmap

### tinylog 3.0-M1
- Complete `tinylog-api`, `tinylog-api-kotlin`, and `tinylog-impl` (not much left to do)
- Develop `slf4j-tinylog` (still completely missing, but not such much effort)
- Write documentation (still completely missing and takes a lot of effort)

### tinylog 3.0-M2
- Develop `tinylog-slf4j` as server adapter and replacement for `tinylog-jboss` and `tinylog-jul`
- Check all closed issues of tinylog 2 for regressions
- Bug fixes

### tinylog 3.0-M3
- Develop `jul-tinylog` and `jsl-tinylog`
- Bug fixes
