### ISSUE TITLE
Ability to configure a writer for all untagged messages + some tags

### ISSUE THREAD

**Issue by mikehearn** [tinylog-org/tinylog#252]
You can't write this:

```
writer.tag = -, sometag
```

because `-` is not actually a way to simply express the empty tag, but a whole 'command' by itself. I'd like to have such a thing so I can use tags as a way to enable or disable extra detail in logging. It seems like an obvious use case but there's no way to express it because you can't write "no tag + this list of extra tags I need for this run".

**Comment by pmwmedia** [comment]
Implemented in the up-coming version 3.0
