### ISSUE TITLE
Is there Rolling File Writer with JSON Support

### ISSUE THREAD

**Issue by salmanmpp** [tinylog-org/tinylog#253]
- Can we write logs into a file with JSON format using Rolling File Writer

**Comment by pmwmedia** [comment]
The rolling writer of tinylog 2 doesn't support the JSON format so far. However, in the latest snapshot of tinylog 3 you can use all rolling file writer functionality with the JSON format.

If you want to build and configure tinylog 3, just let me know. I can provide all required information.

**Comment by salmanmpp** [comment]
I would like to build and configure tinylog 3

**Comment by pmwmedia** [comment]
Steps:
1. Clone repository https://github.com/tinylog-org/tinylog/tree/v3.0
2. Switch to branch v3
3. Install tinylog 3 via `mvn install` locally (use JDK 9, 11, or 17)
4. Add the artifacts `org.tinylog:tinylog-api:3.0-SNAPSHOT`, `org.tinylog:tinylog-api-kotlin:3.0-SNAPSHOT`, `org.tinylog:slf4j-tinylog:3.0-SNAPSHOT`, and/or `org.tinylog:tinylog-impl:3.0-SNAPSHOT` to your project
5. Example configuration for JSON output (`rolling file writer` became `file writer` in tinylog 3):
```properties
level             = INFO

writer.type       = file
writer.file       = logs/{date: yyyy-MM-dd}/log_{count}.txt
writer.policies   = startup, daily: 03:00
writer.format     = ld-json
writer.fields.lvl = level
writer.fields.msg = message
```
