### ISSUE TITLE
How can i get the current log file name on runtime?

### ISSUE THREAD

**Issue by Schnippsche** [tinylog-org/tinylog#254]
Hi, im am using tinylog 2 and i want to load the current log file content to show it in my gui.
My tinylog.properties looks something like this:
`writer=rolling file

writer.file=project_{date: yyyy-MM-dd}.log`

So my problem is: How can i get the current filename of the logger file ?
i can resolve it with hard coded java String formatter, but when someone change the properties file it doesn't fit.
Is there a way to get the current resolved logfile name ?
Thanks

**Comment by pmwmedia** [comment]
I have just answered your question on Stackoverflow: https://stackoverflow.com/a/72299664/5899171
