### ISSUE TITLE
How to config level to split log file by level

### ISSUE THREAD

**Issue by kscorpio** [tinylog-org/tinylog#258]
I need to split log file by level

file1 : only debug level
file2 : only info level
file3 : warn & error

**Comment by pmwmedia** [comment]
You can only do:

file1 : debug level + all more serve levels
file2 : only info level + all more serve levels
file3 : warn & error

What is the use case of having only debug log entries in a log file? Doesn't make it sense to have also log entries with more serve levels in the same log file for context?
