### ISSUE TITLE
DynamicPath

### ISSUE THREAD

**Issue by Saxintosh** [tinylog-org/tinylog#259]
It appears that the backup property of the Rolling File Writer does not work when dynamically changing the path.

In configuration I have:

```
writerFile = rolling file
writerFile.format = {date:yy.MM.dd HH:mm:ss,SSS} {level|min-size=5} {{class-name}.{method}|min-size=40}: [{context:ctx}] {message|indent=4}
writerFile.file = {dynamic: ../log}/log.{date}.txt
writerFile.latest = {dynamic: ../log}/zzLatest.txt
writerFile.policies = dynamic, daily: 00:00
writerFile.backups = 90
```
When I change the dynamic segment with: `DynamicSegment.setText(logFolder.path)`
the new folder remains full of log files... not limited to the last 90

By the way, should be nice to have the possibilities to start the logging, only when i set the dynamic segment in my code! 
In fact, even if I configure the segment without the initial text as: `{dynamic}/log.{date}.txt`, it seems that it is equivalent to `{dynamic: .}/log.{date}.txt`

**Environment**
tinylog version: 1.5.0
Java version: 17

**Comment by pmwmedia** [comment]
> When I change the dynamic segment with: `DynamicSegment.setText(logFolder.path)`
> the new folder remains full of log files... not limited to the last 90

Deleting old log files works only if you have a static log folder root. Otherwise, tinylog cannot find the old log files. For example, `../log/{dynamic: foo}/log.{date}.txt` would work. In your case, you could call `DynamicSegment.setText(logFolder.path)` with completely different log folder roots like '/tmp', '~/foo/bar' and so on. Therefore, tinylog has no idea where to search for all the old log files for deletion. I can't think of a good generic solution at the moment.

> By the way, should be nice to have the possibilities to start the logging, only when i set the dynamic segment in my code!
In fact, even if I configure the segment without the initial text as: {dynamic}/log.{date}.txt, it seems that it is equivalent to {dynamic: .}/log.{date}.txt

Such feature would be possible. If you like, you can open a separate feature request for this.

**Comment by Saxintosh** [comment]
Hi, thanks for your replay.
Unfortunately, logging with DynamicSegment, crashed my JVM (tested with Java 8 and Java 17) on an old ubuntu machine. All fine on my Mac HW.
If you want I can privately send you the log file.

I solved this by creating a new Writer (Kotlin):

It's a simple version that works very well!

```Kotlin
class CustomRollingFileWriter(properties: Map<String, String>) : AbstractFormatPatternWriter(properties) {
	private val myProps = HashMap(properties)
	private var w: RollingFileWriter? = null

	init {
		if(theInstance != null)
			throw Exception("Unexpected")

		theInstance = this
	}

	private fun start(folder: File) {
		if(w != null)
			throw Exception("Already started!")

		val path = folder.absolutePath + "/"

		val file = myProps["file"]
		val newFile = path + file
		val latest = myProps["latest"]
		val newLatest = path + latest

		if (file != null)
			myProps["file"] = newFile
		if (latest != null)
			myProps["latest"] = newLatest

		w = RollingFileWriter(myProps)
	}

	override fun write(logEntry: LogEntry) = w?.write(logEntry) ?: Unit

	override fun flush() = w?.flush() ?: Unit

	override fun close() = w?.close() ?: Unit

	companion object {
		var theInstance : SxRollingFileWriter? = null

		fun setPath(folder: File) {
			theInstance?.start(folder)
		}
	}
}


```

**Comment by pmwmedia** [comment]
Please send me the log file to martin@tinylog.org. I will have a look what is the cause.

**Comment by pmwmedia** [comment]
This bug is not reproducible on any of my systems. The log files show a potential bug of the JRE in connection with the used file system.
