### ISSUE TITLE
slf4j 2.0.3 + Lombok: logging class always resolved to org.slf4j.spi.DefaultLoggingEventBuilder

### ISSUE THREAD

**Issue by q3769** [tinylog-org/tinylog#291]
**Describe the bug**
It should have been resolved to the class issuing the logs, not the SPI class of the Slf4j.

**To Reproduce**
1. In Maven pom.xml
```
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.3</version>
        </dependency>
        <dependency>
            <groupId>org.tinylog</groupId>
            <artifactId>slf4j-tinylog</artifactId>
            <version>2.5.0</version>
        </dependency>
        <dependency>
            <groupId>org.tinylog</groupId>
            <artifactId>tinylog-impl</artifactId>
            <version>2.5.0</version>
        </dependency>
```
2. Use Lombok @Slf4j in logging class, not manual import of tinylog Logger. 
3. Log code sample
```
log.atInfo()
                .log("[{}] tasks were run by [{}] threads, with thread pool size [{}]",
                        TASK_COUNT,
                        actualThreadCount,
                        threadPoolSize);
```

**Environment**
tinylog version: 2.5.0
Java version: 17 (with release target 8)

**Comment by pmwmedia** [comment]
@q3769 What is the output in the log file?

**Comment by q3769** [comment]
It looks like this when I do "mvn clean install":

2022-10-03 15:11:38 [main] org.slf4j.spi.DefaultLoggingEventBuilder.logViaPublicSLF4JLoggerAPI()
INFO: [100] tasks were run by [100] threads, with thread pool size [1000]
