### ISSUE TITLE
Change Logger level at runtime

### ISSUE THREAD

**Issue by torakiki** [tinylog-org/tinylog#305]
I'm trying to change the level of some logger at runtime, the use case is a desktop application where users can select the logging level or some flag or command line argument to have a "verbose" mode.
I looked at this https://github.com/tinylog-org/tinylog/issues/215#issuecomment-870418371 but from what I can understand this works only if you are moving to a stricter level since you are calling super.log, is this correct? 
If so, say I have a org.example set to WARN, is there a way to make it DEBUG at runtime?

**Comment by pmwmedia** [comment]
Yesterday, I set up a minimal example project for re-configuring tinylog at runtime: https://github.com/tinylog-org/tinylog-reload-configuration-example

According to your use case, this example project should exactly do for what you are asking.

**Comment by torakiki** [comment]
Ok, first thanks for taking time to provide a workaround... but, while I understand the benefit of immutability, it seems to me that this feature has been requested few times already. Going through reflection to overcome the restrictions put in place to guarantee immutability seems very fragile, what if the next release renames the internal `frozen` to `blocked` and when someone changes the log level in my GUI the application crashes?
All that is needed to be able to reload a new configuration is already there, it's just unavailable to make it immutable. I'd suggest to make immutability the default but to add a switch or something (not reflecting some internal field) to let those who consciously need to change the configuration being able do it.
My 2 cents.

**Comment by pmwmedia** [comment]
Actually, re-configuring the logging framework at runtime was a feature of tinylog 1. It was very rarely used and therefore I dropped it for tinylog 2. However, you are right that this is currently the most requested feature. Nevertheless, the architecture of tinylog 2 is based on immutability and it would require radical architecture changes to implement a clean solution for changing the configuration at runtime. I don't want to do this in a minor version of tinylog 2.

Therefore, I prefer to deliver such feature with tinylog 3. Until the release for tinylog 3, the workaround is the best I can offer. It works well with all current Java versions and the latest tinylog versions. If you are afraid that a future minor release of tinylog 2 could break something, you can write a small JUnit test that triggers the reconfiguration. So you can ensure that there will be no crashes. By the way, tinylog 2 and tinylog 3 have source code compatible logging APIs. So you will be able to switch from tinylog 2 to 3 without any major source code changes.

**Comment by torakiki** [comment]
Ok, thanks for your time and explanation, I'll wait for version 3 and in the meantime I managed to implement my requirements in a slightly different way so I'm good with the current implementation.
