### ISSUE TITLE
Ping

### ISSUE THREAD

**Issue by yegeniy** [tinylog-org/tinylog#32]
Hi, no real specific issue here. I just stumbled on this tool from https://github.com/akullpp/awesome-java#logging

This tool seems really nice as of 1.1 (what with the excellent documentation, RollingFileWriter, and the SLF4J binding)!

I was just wondering whether there are still plans to continue maintenance of 1.x and 2.0 development?

Either way, this looks great!

**Comment by pmwmedia** [comment]
Currently I'm developing tinylog 1.2 and plan to release it during this year. tinylog 1.2 will have full support of Android and Java EE data sources.

tinylog 2.0 is still in a very early concept phase. As for tinylog 1.0, there will be a very long beta phase of tinylog 2.0 to ensure a stable API. tinylog 1.x will be supported even after releasing tinylog 2.0 as the new version will require Java 1.8 and current Android versions support only Java 1.6.

**Comment by yegeniy** [comment]
Thank you!
