### ISSUE TITLE
Can the animal-sniffer-annotations dependency scope be changed to "provided" on tinylog-impl?

### ISSUE THREAD

**Issue by rsribeiro** [tinylog-org/tinylog#326]
I was having trouble using tinylog in a modular java application because of this dependency, whose scope is set as "compile" in tinylog-impl's [pom.xml](https://github.com/tinylog-org/tinylog/blob/v2.6/tinylog-impl/pom.xml).

My problems were over once I forced the dependency to the "provided" scope. Since my application is small I don't know if this would have unintended side effects to bigger applications that use more features and programs in older java verions

**Comment by pmwmedia** [comment]
I will change the scope in tinylog 3.6.0-M2
