### ISSUE TITLE
add tinylog to log4j2's benchmarks

### ISSUE THREAD

**Issue by pabl0rg** [tinylog-org/tinylog#35]
It would be great to compare tinylog's performance using log4j's own benchmarks

https://github.com/apache/logging-log4j2/tree/master/log4j-perf/src/main/java/org/apache/logging/log4j/perf/jmh

**Comment by pmwmedia** [comment]
It's definitely a good idea! But it needs the permission of a log4j collaborator.

**Comment by pabl0rg** [comment]
You could fork their repo, use it for benchmarks/blog post and also send a PR.

Hopefully, they'd accept it.

**Comment by pmwmedia** [comment]
I have implemented benchmarks for tinylog: https://github.com/apache/logging-log4j2/pull/47

In opposite to tinylog's benchmarks, the format pattern is not configurable in log4j2's benchmarks. So you can benchmark only a static format pattern with category and class name respectively. Log4j is optimized for this use case. If you added method name or drop category / class name, the results would be completely different.

**Comment by pmwmedia** [comment]
Pull request: https://github.com/apache/logging-log4j2/pull/47

**Comment by pmwmedia** [comment]
tinylog 2 contains a JMH benchmark for multiple logging frameworks including Apache Log4j 1 and 2.
