### ISSUE TITLE
Choice-Syntax for Log-Entries

### ISSUE THREAD

**Issue by mstramm** [tinylog-org/tinylog#36]
Hi,
it would be great if you could support a choice-syntax similar to `{0,choice,0#Keinen|1#Einen|2#{0}}` from `MessageFormat.format(...)`.

For the new tinylog-syntax it could be a little bit simpler, like `{0#Keinen|1#Einen|2#{}}` :wink: 
Best regards

**Comment by pmwmedia** [comment]
Implemented in 17cc6b7fe88fe086844e9957d56a453f7e8f78b6

**Comment by mstramm** [comment]
Wow, thanks for the quick implementation. This is a great, meaningful extension. I'm looking forward to version 1.2
