### ISSUE TITLE
Structured logging

### ISSUE THREAD

**Issue by getkey** [tinylog-org/tinylog#369]
In #209, @dbacinski wrote a writer that emits JSON logs. As modern backends are gravitating towards this format, it would be great if it was available in tinylog natively. Could @dbacinski's code be considered for inclusion in the library?

**Comment by pmwmedia** [comment]
It is already available natively in tinylog.

tinylog 2 has a JSON writer for outputting JSON or LDJSON to log files:
https://tinylog.org/v2/configuration/#json-writer

In the coming version 3, the file and console writer can output NDJSON directly:
https://github.com/tinylog-org/website/blob/v3/content/documentation/configuration.md#json

**Comment by getkey** [comment]
Wonderful! Looking forward to v3 :smile:
