### ISSUE TITLE
Add overloaded "isEnabled" method that takes loggerClassName instead of callerDepth

### ISSUE THREAD

**Issue by q3769** [tinylog-org/tinylog#381]
https://github.com/tinylog-org/tinylog/blob/eab5137437ecfdc7fb650105b970465b642e0f7c/tinylog-api/src/main/java/org/tinylog/provider/LoggingProvider.java#L73

Would be nice if a corresponding 

```
boolean isEnabled(String loggerClassName, String tag, Level level);
``` 

method can be added.

**Comment by pmwmedia** [comment]
Fixed in #383
