### ISSUE TITLE
NullPointerException when load tinylog with BootstrapClassLoader

### ISSUE THREAD

**Issue by cspinetta** [tinylog-org/tinylog#39]
First of all, thank you very much for this useful log library! We are using it in [kamon-agent](https://github.com/kamon-io/kamon-agent).

For some integration tests we need to load `tinylog` with the `BootstrapClassLoader`, and this is when this problem manifests itself.

The problem happens when it tries to do things like this:

```
Configurator.class.getClassLoader().getResourceAsStream(file);
```

The calling `Configurator.class.getClassLoader()` returns null since this is the way to say that it was loaded by the bootstrap class loader.

The fix is very simple. For example introducing a method like this:

```
private static InputStream getResourceFromFile(String file) {
    final ClassLoader classLoader = Configurator.class.getClassLoader();
    if (classLoader == null) {
      return ClassLoader.getSystemResourceAsStream(file);
    } else {
      return classLoader.getResourceAsStream(file);
    }
  }
```

And call it from any place where the resource is required.

Let me know if you are agreed with this change and I'll be happy to send a PR.

**Comment by pmwmedia** [comment]
Looks good! Your pull request is welcome :-) `Configurator.class.getClassLoader()` is used in three classes. I guess that there will be the same problem with `BootstrapClassLoader`. Could you provide a fix for all of them?

https://github.com/pmwmedia/tinylog/blob/138e104fa1955e966eb20dab11dfcade896a8137/tinylog/src/org/pmw/tinylog/Configurator.java#L118
https://github.com/pmwmedia/tinylog/blob/138e104fa1955e966eb20dab11dfcade896a8137/tinylog/src/org/pmw/tinylog/Configurator.java#L707
https://github.com/pmwmedia/tinylog/blob/4a147d0b439b2842e14a723c4ccba011c4ce8cbc/tinylog/src/org/pmw/tinylog/ConfigurationObserver.java#L103
https://github.com/pmwmedia/tinylog/blob/dcd88e163ff4230c263bc52afa748111add20150/tinylog/src/org/pmw/tinylog/PropertiesLoader.java#L361

**Comment by cspinetta** [comment]
@pmwmedia yes, of course. This weekend I'll be working on this.
