### ISSUE TITLE
more verbose than necessary

### ISSUE THREAD

**Issue by q3769** [tinylog-org/tinylog#398]
https://github.com/tinylog-org/tinylog/blob/e35fae98e1429317035f1c38f7467305c4b99204/slf4j-tinylog/src/main/java/org/tinylog/slf4j/ModernTinylogLoggerFactory.java#L36

Consider:

```
    public TinylogLogger getLogger(final String name) {
        //		TinylogLogger logger = loggers.get(name);
        //		if (logger == null) {
        //			TinylogLogger newLogger = new TinylogLogger(name);
        //			TinylogLogger existingLogger = loggers.putIfAbsent(name, newLogger);
        //			return existingLogger == null ? newLogger : existingLogger;
        //		} else {
        //			return logger;
        //		}
        return loggers.computeIfAbsent(name, k -> new TinylogLogger(name));
    }
```

**Comment by pmwmedia** [comment]
Unfortunately, we cannot use `computeIfAbsent()` here because we need to be backward compatible with Java 8.

However, tinylog 3 will drop support for Java 8 and use `computeIfAbsent()`:
https://github.com/tinylog-org/tinylog/blob/v3.0/slf4j-tinylog/src/main/java/org/tinylog/slf4j/TinylogLoggerFactory.java#L27

**Comment by q3769** [comment]
> Unfortunately, we cannot use `computeIfAbsent()` here because we need to be backward compatible with Java 8.
> 
> However, tinylog 3 will drop support for Java 8 and use `computeIfAbsent()`: https://github.com/tinylog-org/tinylog/blob/v3.0/slf4j-tinylog/src/main/java/org/tinylog/slf4j/TinylogLoggerFactory.java#L27

Both computeIfAbsent and putIfAbsent are "since 1.8". Why can putIfAbsent be used, but not computeIfAbsent?

**Comment by pmwmedia** [comment]
Sorry, I meant Java 6. In tinylog 2, we need to be backward compatible with Java 6:
https://github.com/tinylog-org/tinylog/blob/v2.7/pom.xml#L141

In Java 6, the `ConcurrentMap` supports `putIfAbsent()`, but does not support `computeIfAbsent()`:
https://docs.oracle.com/javase/6/docs/api/java/util/concurrent/ConcurrentMap.html
