### ISSUE TITLE
Multiple Log Files created when rollover is initiated

### ISSUE THREAD

**Issue by salmanmpp** [tinylog-org/tinylog#423]
```properties
provider=dynamic level
level=trace
writer=rolling file
writer.file=/storage/emulated/0/App/logs/log_{count}.txt
writer.policies=dynamic size,log sync
writer.format={date:yyyy-MM-dd HH:mm:ss.SSSZ } {level} {tag} {message}
writer.append=true
writer2=logcat
writer2.format= {date:yyyy-MM-dd HH:mm:ss.SSSZ } {level} {tag} {message}
```

we are using this property file to create log file . 
we are setting rollover file size dynamically. 
We have come across a scenario at some point when rollover is initiated that is when current file reached max file size ,
 we found that there is two file created one with 0 kb. this is not reproducible always. But we got it few times

**Comment by pmwmedia** [comment]
Could you provide a minimal example project, so that I can reproduce the issue? I'm not able to reproduce the bug on my system by just using your tinylog configuration file.
