### ISSUE TITLE
tinylog not logging some messages when used via SLF4J 2.0 fluent API

### ISSUE THREAD

**Issue by jkmcl** [tinylog-org/tinylog#459]
**Describe the bug**
Using the same tinylog configuration, both statements below should output their message:
```
logger.debug("debug message 1");
logger.atDebug().log("debug message 2"); // this message is not logged
```
However, only the first first log message is output if the below severity is set:

```
level     = debug
level@org = info
```
It seems that tinylog thinks that the logger has the class name `org.slf4j.Logger` when the SLF4J fluent API is being used.

A simple Maven project with a single test class is attached to illustrate the issue: [bug.zip](https://github.com/tinylog-org/tinylog/files/11456077/bug.zip)

**To Reproduce**
1. Run the test in the attached Maven project and observe the output. Only the first message will be output
2. Comment out the line `level@org = info` in the file `tinylog-test.properties` and run the test again. This time both messages will be output

**Environment**
- tinylog version: 2.6.1
- SLF4J version: 2.0.7
- Java version: 11

**Comment by pmwmedia** [comment]
Thank you very much for the great description and the minimal reproduction project. It made it very easy for me to reproduce and fix this issue. I have just released the fix in tinylog 2.6.2.
