### ISSUE TITLE
Format time in UTC timezone

### ISSUE THREAD

**Issue by zarzavat** [tinylog-org/tinylog#503]
I'm trying to format the time as UTC time - so say you're in EEST Time Zone (UTC+3) and it's 17:30, I want to log the time as 14:30 - exactly like that, so not 17:30 +03:00 or similar, basically I'm not interested in the timezone information. Is there a way to achieve this with the current implementation? One way to do this that as far as I can see involves changing this [code](https://github.com/tinylog-org/tinylog/blob/4819b49fe06eae3be79731ba194a525fa1b8aa63/tinylog-api/src/main/java/org/tinylog/runtime/PreciseTimestampFormatter.java#L47C81-L47C81) and set the zone to UTC rather than the system default and similarly in other formatters.

Is it possible to customize the formatter without editing the library code? Alternatively, I'd also be happy with customizing the date that the formatter receives, as I could just apply the offset there. Are either of these two options possible?

Thanks!

**Comment by pmwmedia** [comment]
In tinylog 3, it will be possible to configure the time zone:
https://github.com/tinylog-org/website/blob/v3/content/documentation/configuration.md#time-zone

Unfortunately, tinylog 3 isn't publicly released yet. However, the release is planned for this year.

If you cannot wait and you will have some time for a pull request, you can backport the feature. The main idea would be:

- Add the time zone as third parameter to [RuntimeProvider.createTimestampFormatter()](https://github.com/tinylog-org/tinylog/blob/v2.7/tinylog-api/src/main/java/org/tinylog/runtime/RuntimeProvider.java#L171)
- Adapt the calls of this method as well as both timestamp implementations to support the time zone as parameter
- Read the time zone as property from the configuration in [DateToken](https://github.com/tinylog-org/tinylog/blob/v2.7/tinylog-impl/src/main/java/org/tinylog/pattern/DateToken.java)
