### ISSUE TITLE
tinylog.properties does not seem to be read in version 2.6.2, but works in 2.5.0.

### ISSUE THREAD

**Issue by Headingwest14** [tinylog-org/tinylog#509]
**Describe the bug**
tinylog.properties does not seem to be used for configuration in version 2.6.2. When I rolled back to version 2.5.0 the tinylog.properties file was recognized.
**To Reproduce**
1. Configure tinylog 2.6.2 in an Eclipse Maven project (added dependencies to the pom.xml and added logging statements).
2. Add the tinylog.properties file to src/main/java folder.
3. Ran the program, and logging properties file does not seem to be read.
4. Configure tinlog 2.5.0 in the same project.
5. Ran the program, and the logging properties file is read.

**Environment**
tinylog version: 2.6.2
Java version: JDK  8u 242-b8.
Eclipse version: 2023-06
OS version: Ubuntu 22:04

**Comment by pmwmedia** [comment]
Could you be able to provide a minimal reproduction project?

**Comment by pmwmedia** [comment]
By the way, for Maven projects, properties files should be put into `src/main/resources` instead of `src/main/java`.

**Comment by Headingwest14** [comment]
Sorry I checked it again and now it works. I must have messed up my configs.
Thanks for all your help. Tinylog is my favourite logger!
