### ISSUE TITLE
Documentation for NoSuchMethodError: org.pmw.tinylog.Logger.output

### ISSUE THREAD

**Issue by koppor** [tinylog-org/tinylog#51]
I have following dependencies in my `pom.xml`.

		<dependency>
			<groupId>org.tinylog</groupId>
			<artifactId>tinylog</artifactId>
			<version>1.2</version>
		</dependency>
		<dependency>
			
			<groupId>org.tinylog</groupId>
			<artifactId>tinylog-jul</artifactId>
			<version>1.2</version>
		</dependency>
		<dependency>
			<groupId>org.tinylog</groupId>
			<artifactId>slf4j-binding</artifactId>
			<version>1.2</version>
		</dependency>

When running test cases, everything works, but when I run the jsp inside tomcat8, I get following output:

```
java.lang.NoSuchMethodError: org.pmw.tinylog.Logger.output(ILorg/pmw/tinylog/Level;Ljava/lang/Throwable;Ljava/lang/Object;[Ljava/lang/Object;)V
	org.pmw.tinylog.LogEntryForwarder.forward(Unknown Source)
	org.slf4j.impl.TinylogBridge.log(Unknown Source)
```

Is it possible to detail the documentation with that regard?

**Comment by pmwmedia** [comment]
`slf4j-binding` redirects log entries to tinylog's back end. But `tinylog-jul` doesn't have a real back end as it use Tomcat's logging system as back end. `tinylog-jul` contains the same logging API as the native artifact `tinylog`. You need only one of them.

- If you want to use tinylog's native back end (logging configuration via tinylog), you should remove `tinylog-jul`.
- If you want to use Tomcat's logging system as back end (global logging configuration via Tomcat), you should remove `tinylog` as well as `slf4j-binding` and replace it by slf4j-log4j12-1.6.1.jar.
- If you want to use tinylog's native back end for tests, but Tomcat's logging system as back end for production, you can add`<scope>test</scope>` to the artifacts `tinylog` and `slf4j-binding`.
