### ISSUE TITLE
[Need advice] -  Using tinylog in android app

### ISSUE THREAD

**Issue by sumit784** [tinylog-org/tinylog#52]
Hi, 
This is NOT an issue, but just an advice taking for using tinylog in my android app. 
So, I want to use this in my android app and wanted to write the application logs here. It will be common  file created hourly. I want to keep it multithreaded. 

## Here is what I think as the config :- 

tinylog.writer = sharedfile
tinylog.writer.filename = mylog.txt
tinylog.writer.append = true
tinylog.writer.backups = 100
tinylog.writer.label = timestamp
tinylog.writer.policies = hourly, size: 100KB
tinylog.writingthread = true
tinylog.writingthread.observe = null
tinylog.writingthread.priority = 1

## Queries
- Will the above config allow creation and writing of log files on hourly basis
- I am using Amazon S3 bucket to store the logs
- Shall I write the config in property file in s3 bucket or use java code in android app itself. 

any other suggestions are welcome.

**Comment by pmwmedia** [comment]
You need the rolling file writer (`tinylog.writer = rollingfile`). Only the rolling file writer supports starting new log files based on rules. It appends existing log files automatically, so you can remove the line `tinylog.writer.append = true`.

I haven used Amazon S3 bucket yet. Thus, I can't give any suggestions about Amazon S3 bucket itself. The most developers (including me) prefer to use a property file to configure tinylog rather than Java code.

**Comment by sumit784** [comment]
Thanks for responding. 

Using RollingFile writer, will it support writing from multiple threads ? 
The test case is, lets say there are 1000 users using our android app at the same time and we are logging their activities in our log file. 
will Rollingfile supports writing all these 1000 user values, written to the same file ?

**Comment by pmwmedia** [comment]
tinylog is completly thread-safe. All writes, including the rollging file writer, supports multiple threads. The shared file writer supports additionally that multiple applications can write to the same log file at the same time. But it doesn't support rolling.

**Comment by sumit784** [comment]
So by "multiple applications can write" , did you mean, several different application or "multiple instances" of an application ( like an android app with 10,000 downloads/ users)

I just want to make sure that Rolling Write will be best choice for android app, where data from 10,000 running apps is written to the same log file.

**Comment by pmwmedia** [comment]
I mean both: several different applications and/or multiple instances of an application. However, usually you run only one instance of an app on a device!? Do you plan that thousands of apps log to a remote machine? In this case, you should think about a specialized logging server. Maybe a Graylog server with an external GELF writer for tinylog could be a solution.
