### ISSUE TITLE
Log level on apache package not working?

### ISSUE THREAD

**Issue by totszwai** [tinylog-org/tinylog#53]
I am getting too much verbosity out of the apache packages when I set the logging level to Level.DEBUG, I tried to disable the logging on the apache stuff, but doesn't seem to work?

        Configurator c = Configurator.currentConfig();
        c.level(Level.DEBUG); // set everything to debug by default
        // Trying to turn off other debug that I don't care
        //c.level("org.apache.http.client", Level.OFF);
        //c.level("org.apache.http.client.*", Level.OFF);
        //c.level("org.apache.http.impl.client", Level.OFF);
        //c.level("org.apache.commons.logging.simplelog.log.org.apache.http", Level.OFF);
        //c.level("org.apache.commons.logging.simplelog.log.org.apache.http.wire", Level.OFF);
        //c.level("org.apache.commons.logging.simplelog.log.org.apache.http.impl.conn", Level.OFF);
        //c.level("org.apache.commons.logging.simplelog.log.org.apache.http.impl.client", Level.OFF);
        //c.level("org.apache.commons.logging.simplelog.log.org.apache.http.client", Level.OFF);
        c.level("org.apache.http.impl.client", Level.OFF);
        c.formatPattern("{date:HH:mm:ss} {level|min-size=8} {message}");
        c.activate();

Is this a bug? Or does the "package" only works for tinylog's package? What is the proper way to make it work?

**Comment by pmwmedia** [comment]
Apache HttpComponents 4.x uses Commons Logging. Do you have made sure that tinylog's JCL binding is in the classpath and no other binding to another logging framework? Does Apache HttpComponents output any log entries, if you disable logging at all (```c.level(Level.OFF)```)?
