### ISSUE TITLE
Is it possible to define custom Level via Configurator?

### ISSUE THREAD

**Issue by totszwai** [tinylog-org/tinylog#54]
Looking at the existing source, I don't think that's possible.

I'm wondering if tinylog can support custom levels such as DEBUG1, DEBUG2, DEBUG3, DEBUG4, DEBUG5? 

Right now when I use tinylog, I mostly use this:
```
        Configurator c = Configurator.currentConfig();
        c.level(Level.DEBUG);
        c.formatPattern("{date:HH:mm:ss} {level|min-size=8} {message}");
        c.activate();
```
But it would be nice to be able to control how much debugging to print out.

**Comment by pmwmedia** [comment]
tinylog is a lightware logging framework. Custom logging levels are not supported.
