### ISSUE TITLE
Logger class is missing stack trace error

### ISSUE THREAD

**Issue by afloarea** [tinylog-org/tinylog#565]
First of all, thank you for maintaining this project.

I am using tinylog 2.6.2 with slf4j 2.0.6 with the Vert.x (v4.4.4) toolkit. Logging from my code works fine, however logging done by the toolkit results in errors in the console. I am seeing messages like this
```
2023-10-13 23:29:28 INFO [vert.x-eventloop-thread-1] EntryPoint$SampleVerticle:24 deployed
2023-10-13 23:29:28 INFO [vert.x-eventloop-thread-0] <unknown class>:? Succeeded in deploying verticle
LOGGER ERROR: Logger class "io.vertx.core.logging.Logger" is missing in stack trace
```
I replaced tinylog with logback version 1.4.11 and the output is like this
```
23:44:57 [vert.x-eventloop-thread-1] INFO  EntryPoint$SampleVerticle:24 deployed
23:44:57 [vert.x-eventloop-thread-0] INFO  VertxIsolatedDeployer:? Succeeded in deploying verticle
```

I did some digging and I saw the following
```
io.vertx.core.logging.SLF4JLogDelegate:198
        // I replaced the variables with literal values
	calls l.log(null, "io.vertx.core.logging.Logger", 20, "Succeeded in deploying verticle", null, null) 
        where l is of type ModernTinylogLogger with name "io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer"
        and l.log is org.slf4j.spi.LocationAwareLogger::log (full signature is org.tinylog.slf4j.AbstractTinylogLogger.log(final Marker marker, final String fqcn, final int level, final String message, final Object[] arguments, final Throwable exception)
```
and looking deeper I saw that it fails to identify a `StackTraceElement`:
![tinylog](https://github.com/tinylog-org/tinylog/assets/20104805/15c0b606-1bef-4f3d-947e-2584401464e6)

I am guessing the one at index 9 should be correct one but because the `loggerClassName` is `io.vertx.core.logging.Logger` it doesn't find it and this results in the `LOGGER ERROR: Logger class "io.vertx.core.logging.Logger" is missing in stack trace` printed to `System.err`.

At this point I am confused and I want to ask
1. Is the calling code (i.e. Vert.x) at fault for calling with wrong arguments or could this be an issue in tinylog?
2. Is there a way to disable outputting messages such as `LOGGER ERROR: Logger class "io.vertx.core.logging.Logger" is missing in stack trace`? I have a use case where I want to log incoming http requests and the logging is done by Vert.x and for each request I also get messages like the one above which pollute the console.

I apologize for the long question(s) and I thank you in advance for your patience.

**Comment by pmwmedia** [comment]
Hi @afloarea!

Unfortunately, this is actually a known issue of Vert.x: #191

Especially, this explanation could be helpful to understand the cause of this issue: https://github.com/tinylog-org/tinylog/issues/191#issuecomment-782714420

**Comment by afloarea** [comment]
Thank you @pmwmedia  for the reply with additional info. I had a look at the [Vert.x Delegate](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/logging/SLF4JLogDelegate.java) and I saw it was updated for their next release and might fix the issue.

Thank you for addressing my question.

**Comment by pmwmedia** [comment]
Would be great if this issue is finally fixed :)
