### ISSUE TITLE
Log output to UTF-8

### ISSUE THREAD

**Issue by benbve** [tinylog-org/tinylog#57]
Hi, I recently started using tinylog and it's great.

However, I noticed that it outputs log files to the character set default of the platform (i.e. on OSX it's UTF-8 and on Windows it's ANSI).

It would be good if one could specify the output character set or otherwise enforce UTF-8 across the board (which is actually what I'm after)

**Comment by pmwmedia** [comment]
Enforcing charsets will be supported by tinylog 2.0 and is there already implemented. But tinylog 2.0 itself is still under development.

Example tinylog 2.0 configuration:
```
writer = file
writer.file = log.txt
writer.charset = UTF-8
```

**Comment by pmwmedia** [comment]
Implemented by commits 862ad32988bfc3879b88b1ed41d4138a4d868642 and 3ce6cae93705d4733d315969ffbdf85a4ae0d48b
