### ISSUE TITLE
Why does the JdbcWriter close and re-build prepared statements?

### ISSUE THREAD

**Issue by SebAlbert** [tinylog-org/tinylog#58]
What is the rationale behind closing the prepared statements and re-building them either after each log message or after each batch execution? Could this be a performance bottleneck?

**Comment by pmwmedia** [comment]
I think you are right that a prepared statement should be reused. I'm going to benchmark both cases and according to the result, I will change it in tinylog 1.3.

**Comment by SebAlbert** [comment]
I suspect we should also keep an eye on "autocommit" and the question what happens upon JVM crash (commit-wise) in connection with a re-used prepared statement. But not re-preparing statements all the time (which is often a sort of "compilation" process in the database, involving parsing and query planning) should be a good idea in the first place. Thanks for going after this.

**Comment by pmwmedia** [comment]
Fixed in 39fdb70d171a30a67a53433e156602a69a6759e9
