### ISSUE TITLE
Add support for Supplier for lazy message generation

### ISSUE THREAD

**Issue by SebAlbert** [tinylog-org/tinylog#59]
I like the idea of putting my log messages in a lambda, so that if a certain level is not configured to be output at all (not active), even the parts of the log message don't have to be looked for (or generated) in the calling thread in the first place. I think I have seen this in another logging framework (maybe Log4j).

Is this a possible improvement? And what would we have to consider about thread-safety and race conditions, especially with a separate Writer Thread?

**Comment by pmwmedia** [comment]
Log messages are rendered always in the same thread and before calling the separate writing thread. So it should be no problem to implement lazy lambda messages in tinylog.

**Comment by pmwmedia** [comment]
Implemented in commit 56e5ea1ba22251c83f6823de38c412b8f6e8610a for tinylog 2.0. The next step would be merging it into branch 1.3 (in fact it will be a reimplantation).

Example for tinylog 2.0:
```java
Logger.info(() -> "Hello World!");
Logger.info("{}", () -> 42);
```

**Comment by pmwmedia** [comment]
Implemented in commits 5ff190aef9258ede44ed77cc4e7f6cf9a3973d8f and bd78753c91a48f21329a526c097c953c6766c747 for tinylog 1.3.

**Comment by pmwmedia** [comment]
@SebAlbert I have just released tinylog 1.3-rc-2: https://github.com/pmwmedia/tinylog/releases/tag/1.3-rc2. Testing and feedback is welcome :)

**Comment by SebAlbert** [comment]
Thanks. I have successfully [changed](https://github.com/APTD/Simulation/commit/5310f9578698e6bc391f234257f6bb352e7b6a4a) my usage in ongoing work on a simulation project to 1.3-rc2 with lazy lambdas.

**Comment by pmwmedia** [comment]
Thanks for testing!
