### ISSUE TITLE
 log4j-facade-2.x

### ISSUE THREAD

**Issue by uptimestar** [tinylog-org/tinylog#61]
I see log4j 1.
Is there are log4j 2 adapter?

**Comment by pmwmedia** [comment]
tinylog doesn't have any adapter for Log4j 2.x API yet. In general there seems to be little interest in using Log4j API with tinylog. At least I haven't received any feature request before yours. Currently I'm focusing on releasing tinylog 1.3 and new features for tinylog 2.0. But any contribution is welcome and I'm open to support it.

**Comment by pmwmedia** [comment]
Apache Log4j2 API can be used in tinylog via SLF4J.

Required artifacts:

- [Apache Log4j API](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api)
- [Apache Log4j to SLF4J Adapter](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-to-slf4j)
- [SLF4J Binding For Tinylog](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-to-slf4j)
- [Tinylog Implementation](https://mvnrepository.com/artifact/org.tinylog/slf4j-tinylog)

**Comment by pmwmedia** [comment]
A working example can be found in [issue 106](https://github.com/pmwmedia/tinylog/issues/106#issuecomment-499004401)
