### ISSUE TITLE
Date placeholder in file name does not get applied

### ISSUE THREAD

**Issue by mhmxd** [tinylog-org/tinylog#624]
**Describe the bug**
The date placeholder is placed verbatim in the created log file: `detail_{date: HH-mm}.txt`.

**To Reproduce**
1. Insert this in tinylog.properties:
```
writerDetail               = file
writerDetail.file         = log/detail_{date: HH-mm}.txt
writerDetail.format   = {date: HH:mm:ss.SSS} {level}: {message}
writerDetail.tag         = DETAIL
```
2. Run the program and log.
3. Create file is `log/detail_{date: HH-mm}.txt`
4. Same issue with `detail_{date: HH:mm}.txt`, `detail_{date: HH.mm}.txt`, `{date}.txt`

**Environment**
tinylog version: 2.6.2
Java version: JDK 17.0.2

**Comment by pmwmedia** [comment]
You have to use the [rolling file writer](https://tinylog.org/v2/configuration/#rolling-file-writer), if you want to use a placeholders in your filename.

tinylog.properties:

```properties
writerDetail        = rolling file
writerDetail.file   = log/detail_{date: HH-mm}.txt
writerDetail.format = {date: HH:mm:ss.SSS} {level}: {message}
writerDetail.tag    = DETAIL
```

**Comment by mhmxd** [comment]
@pmwmedia Thank you! I don't know how I missed that in the docs.

**Comment by pmwmedia** [comment]
In tinylog 3, the rolling file writer and file writer will be merged into a single writer to avoid this trap in future.
