### ISSUE TITLE
When attempting to build latest, I can't transfer animal-sniffer

### ISSUE THREAD

**Issue by rwmyers** [tinylog-org/tinylog#626]
**Describe the bug**
I'm attempting to do a new setup and can't get past the following error:
```
[ERROR] Failed to execute goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.23:check (default) on project tinylog-api: Execution default of goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.23:check failed: Plugin org.codehaus.mojo:animal-sniffer-maven-plugin:1.23 or one of its dependencies could not be resolved: Failed to collect dependencies at org.codehaus.mojo:animal-sniffer-maven-plugin:jar:1.23 -> org.codehaus.mojo:animal-sniffer:jar:1.23: Failed to read artifact descriptor for org.codehaus.mojo:animal-sniffer:jar:1.23: Could not transfer artifact org.codehaus.mojo:animal-sniffer:pom:1.23 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/codehaus/mojo/animal-sniffer/1.23/animal-sniffer-1.23.pom: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
```

**To Reproduce**
1. Pull latest tinylog
2. Install maven
3. Install openjdk-9
4. Run `mvn clean verify` as suggested by the contribution MD file

I've attempted this on two different Ubuntu distributions without success. I've pulled the POM as well and attempted to use keytool to apply the cert. The guide suggests submitting a bug.

**Comment by pmwmedia** [comment]
Are you behind a company proxy or firewall? Sounds like a typical issue with proxies that require self-signed third-party SSL certificates. `https://repo.maven.apache.org` is the official remote Maven repository and should have a valid SSL certificate for sure.

A workaround could be to use another JDK (version 11 or 17) for transferring all required artifacts. As soon as all required artifacts are in the local repository, you should be able to use OpenJDK 9 to build tinylog.
