### ISSUE TITLE
Colored console output

### ISSUE THREAD

**Issue by tobiasrm** [tinylog-org/tinylog#63]
**FEATURE REQUEST**

**Please add a possibility for coloured console output.**

- Problem:
Currently, coloring is not available for console output (but I love it ;-) ). The workaround to specify multiple console writers (colorize the different levels) does not work as they are all used, leading to multiple outputs with the same content (different formats though), e.g. the debug level writer format is also used for higher levels.

Of course, coloured outputs could be deeply integrated into Tinylog. However, it also be simple with the following options:

- Possible solution:
  - _Force a console logger to the selected level (or set of levels)_. 
Then, the level specific writers do not apply on higher logger levels (e.g. "debug, info" will not apply on warning or error). Then, the level format can include ASCII colour codes for each level and content placeholder.
  - _Allow hierarchical overwrites._ 
For example, if you have to consoler writers,  writerInfo for info level and writerWarn for warning level, only the writerWarn will be used for warnings and lower level writers ignored.

I love tinylog and just migrated my whole project :-) 
Would be great if you could consider my requerst.

Cheers,
Tobias

**Comment by pmwmedia** [comment]
Hi Tobias,

That's a really specific request. As tinylog should be lightweight logging framework, I prefer to store a colored console writer in an external artifact. tinylog can be easily extended: http://www.tinylog.org/extend. You could create a ColoredConsoleWriter and register it as a service. Then the writer can be configured in your properties file in the same way as native writers.

**Comment by tobiasrm** [comment]
Wow, thanks for the super fast response. I fully agree to your choice of a lightweight framework. The extension way is the the way to go. And who knows why my eyes fully ignored the extensions :-)
Thanks for you advice.

**Comment by pmwmedia** [comment]
A good template for starting could be the console writer of tinylog 1.2: https://github.com/pmwmedia/tinylog/blob/v1.2/tinylog/src/org/pmw/tinylog/writers/ConsoleWriter.java

Please let me know if you have any further questions, I'd be happy to help :-)

**Comment by ralleal** [comment]
Hi,
Regarding making a colored console writer in version 2, how could I approach it?  If I extend the Writer, I lose the formatted pattern, and if I extend the AbstractFormatPatternWriter, I cannot see how could I control the individual elements of the pattern so I could wrap them with ANSI colors. I just have access to a render(). 
Thanks!

**Comment by pmwmedia** [comment]
I suggest to implement directly the interface [Writer](https://github.com/pmwmedia/tinylog/blob/v2.2/tinylog-impl/src/main/java/org/tinylog/writers/Writer.java), if you want to create a colored console writer in the [same way](https://github.com/tobiasrm/tinylog-coloredconsole) as tobiasrm did for tinylog 1.

In the constructor of your writer, you can manipulate the format pattern and insert the ANSI colors for each severity level.

```java
public ColoredConsoleWriter(final Map<String, String> properties) {
	String pattern = properties.get("format");
	if (pattern == null) {
		pattern = DEFAULT_FORMAT_PATTERN;
	}

	String exception = properties.get("exception");

	String tracePattern = applyTraceColors(pattern + NEW_LINE);
	traceToken = new FormatPatternParser(exception).parse(tracePattern);

	String debugPattern = applyDebugColors(pattern + NEW_LINE);
	debugToken = new FormatPatternParser(exception).parse(debugPattern);

	String infoPattern = applyInfoColors(pattern + NEW_LINE);
	infoToken = new FormatPatternParser(exception).parse(infoPattern);

	String warnPattern = applyWarnColors(pattern + NEW_LINE);
	warnToken = new FormatPatternParser(exception).parse(warnPattern);

	String errorPattern = applyErrorColors(pattern + NEW_LINE);
	errorToken = new FormatPatternParser(exception).parse(errorPattern);

	boolean writingThread = Boolean.parseBoolean(properties.get("writingthread"));
	builder = writingThread ? new StringBuilder(BUILDER_CAPACITY) : null;
}
```

In the `write()` method, you can use the corresponding token for each severity level for rendering a log entry.

```java
public void write(final LogEntry logEntry) {
	StringBuilder builder;
	if (this.builder == null) {
		builder = new StringBuilder(BUILDER_CAPACITY);
	} else {
		builder = this.builder;
		builder.setLength(0);
	}

	switch (logEntry.getLevel()) {
		case ERROR:
			errorToken.render(logEntry, builder);
			System.err.print(builder);
			break;
		case: ....
	}
}
```

The code above is not tested. However, I hope it shows my idea of implementing a colored console writer for tinylog 2. Like for all other writers for tinylog 2, the same string builder instance is reused if the writing thread is enabled, but a new string builder has to be used if the writing thread is disabled.

**Comment by ralleal** [comment]
Ok, I get the idea, I was complicating things :-)
Nice work with Tinylog btw, it's simple and fast, we couldn't ask for more :-) I think it should be more widely used.
Thanks!

**Comment by pmwmedia** [comment]
You are welcome! Let me know when you are done with the implementation :-)
