### ISSUE TITLE
tinylog.format in property file not used

### ISSUE THREAD

**Issue by flashpixx** [tinylog-org/tinylog#64]
I'm using tinylog in my application with this configuration file

```
tinylog.level = warning
tinylog.writer = console
tinylog.format = {date:yyyy-MM-dd HH:mm:ss}    {thread}    {class}.{method} {line}    {level}: {message}
```

but the item ```tinylog.format``` is not used, but if I set it with ```-D"tinylog.format = {date:yyyy-MM-dd HH:mm:ss}    {thread}    {class}.{method} {line}    {level}: {message}"``` it works correctly. I'm using ```Logger.info``` and ```Logger.error``` directly without any other instantiation of tinylog

**Comment by pmwmedia** [comment]
I am not able to reproduce this issue.

Example Java application:

```java
import org.pmw.tinylog.Logger;

public class Application {

	public static void main(String[] args) {
		Logger.error("Hello World!");
	}

}
```

Configuration /tinylog.properties:

```
tinylog.level = warning
tinylog.writer = console
tinylog.format = {date:yyyy-MM-dd HH:mm:ss}    {thread}    {class}.{method} {line}    {level}: {message}
```

Output:

```
2017-12-15 12:15:40    main    Application.main 6    ERROR: Hello World!
```

Where have you stored the configuration file? Can you try to change other properties in your configuration file to verify if tinylog uses it.

**Comment by flashpixx** [comment]
You found the whole source code (Maven project) under https://github.com/LightJason/Benchmark
(your need also this framework https://github.com/LightJason/AgentSpeak). 

The configuration file is stored under https://github.com/LightJason/Benchmark/blob/master/src/main/resources/org/lightjason/benchmark/tinylog.properties

A testing running configuration can be found in this branch https://github.com/LightJason/Benchmark/tree/synchronizedcount5 just run the jar with the yaml file as input

**Comment by pmwmedia** [comment]
Please try to put 'tinylog.properties' to 'src/main/resources' instead of 'src/main/resources/org/lightjason/benchmark'.

**Comment by flashpixx** [comment]
I have moved it, but then it will not be read, so the console writer is not set on changing the file location

**Comment by pmwmedia** [comment]
I have tested your project. After moving 'tinylog.properties' to 'src/main/resources', logging does work and your configured format pattern is used for writing log entries into the console.

**Comment by flashpixx** [comment]
If I moved the file, the output is not shown, you can test it with a docker container:
https://hub.docker.com/r/lightjason/benchmark/
You can follow-up the CircleCI log output https://circleci.com/gh/LightJason/Benchmark/15
on a previous run https://circleci.com/gh/LightJason/Benchmark/11 with the location ```src/main/resources/org/lightjason/benchmark``` of the property file it will shown the result.

**Comment by pmwmedia** [comment]
In your tinylog.properties, you have set `tinylog.level = warning`. Therefor info log entries will be not output. If you want to see info log entries in your console output, you have to set `tinylog.level = info`.

**Comment by flashpixx** [comment]
Based on this description http://www.tinylog.org/de/konfiguration#level
``` TRACE < DEBUG < INFO < WARNING < ERROR```
is warning higher than info, so if I set the log level to warning all info texts are also included

So your last answer is the opposite of this definition, so based on your answer, the list should be ``` TRACE < DEBUG < WARNING < INFO < ERROR``` but I have tested it, so it seems to work and the documentation seems to be incorrect

**Comment by pmwmedia** [comment]
It's the way around. Each logging level includes all higher levels. INFO includes infos, warnings and errors, WARNING includes only warnings and errors.
