### ISSUE TITLE
How to programmatically set the log file path？

### ISSUE THREAD

**Issue by lizhongyue248** [tinylog-org/tinylog#654]
I want to set the path of the log file in my program instead of through the configuration file.

Configuration file like :
```
writer=console
writer.format={date: HH:mm:ss.SSS} {pid} {level} [{thread}] {class}.{method}:{line} - {message}
# ------------------------------------------------------------------------------
writer2=file
writer2.file=logs/port-view.log
writer2.level=info
writer2.format={date: HH:mm:ss.SSS} {pid} {level} [{thread}] - {message}
writer2.charset=UTF-8
```

How do I change the `writer2.file` in my program when user input path?

```
TextField(
    value = filtPathState,
    onValueChange = {
        filtPathState.value = it
        // Change log file path.....
    },
)
```

Thanks!

**Comment by pmwmedia** [comment]
You can set `writer2.file` programmatically. However, you have to be aware that tinylog's configuration becomes immutable as soon as the first log entry is issued. This behavior allows tinylog to process log entries with disabled severity levels way faster than other logging frameworks: https://tinylog.org/v2/benchmark/#discarding-log-entries

How to set `writer2.file` programmatically:

```properties
Configuration.set("writer2.format", "<your path>");
```

**Comment by lizhongyue248** [comment]
Thanks！It works very well！
