### ISSUE TITLE
Can't log with `{`

### ISSUE THREAD

**Issue by Lawendt** [tinylog-org/tinylog#66]
I'm trying to use a format that has `{` in it, like this: `{ \"method\": \"{method}\", "message": \"{message}\" }`. But with this format the output is: `"method": "foo()", "message":"something happened"`, without the curly brackets in the start and the end.
Is there a way of dealing with this?

**Comment by pmwmedia** [comment]
Escaping curly brackets is not supported yet. Do you want to generate JSON?

**Comment by pmwmedia** [comment]
Curly brackets can be escaped in tinylog 2.0 with double backslashes.

Example: ```\\{ - {message} - \\}```

**Comment by Lawendt** [comment]
Yes, it is for JSON. Thanks for the info :D

**Comment by dbacinski** [comment]
I am trying to make it work with tinylog 2.3.1, but it doesn't work:
```
writer2=console
writer2.format=\\{ - {message} - \\}
```
is logged as:
`\ - test message - \`
but expected is:
`{ - test message - }`

or

```
writer2.format=\\{\"timestamp\":\"{date:yyyy-MM-dd HH:mm:ss.SSS}\",\"severity\":\"{level}\",\"threadId\":\"{thread}\",\"file\":\"{file}:{line}\",\"message\":\"{message}\"\\}
```

it logs as:
`\"timestamp":"2021-06-01 21:50:45.530","severity":"INFO","threadId":"main","file":"properties.kt:31","message":"test message"\`
but expected is:
`{"timestamp":"2021-06-01 21:50:45.530","severity":"INFO","threadId":"main","file":"properties.kt:31","message":"test message"}`

**Comment by pmwmedia** [comment]
You need to use `{opening-curly-bracket}` and `{closing-curly-bracket}` (see https://tinylog.org/v2/configuration/#format-pattern):

```
writer2=console
writer2.format={opening-curly-bracket} - {message} - {closing-curly-bracket}
```

By the way, tinylog 2.4 has also a native JSON writer (see https://tinylog.org/v2/configuration/#json-writer),
