### ISSUE TITLE
How to skip the log output of third-party packages?

### ISSUE THREAD

**Issue by lizhongyue248** [tinylog-org/tinylog#665]
Tinylog has been integrated into the application, and some third-party packages can also be used, but I hope to skip the log output of the specified third-party package. Can the output be ignored through package name matching?

**Comment by pmwmedia** [comment]
This is just a one liner in your `tinylog.properties`:

```properties
level@com.third.party.package = off
```

Also see https://tinylog.org/v2/configuration/#severity-level

**Comment by lizhongyue248** [comment]
Great, I didn't expect to be able to do it this way! Tinylog really very useful！
