### ISSUE TITLE
Non-OS depend tinylog.writer.filename values.

### ISSUE THREAD

**Issue by romanlinhard** [tinylog-org/tinylog#67]
Hello,
I want to use TinyLog in different OS environments (WIN, Linux, ...) and therefore, I missed the possibility to define not an hardlink to /tmp/ .
Better would be a placeholder like $TMP and $HOME, %t and %h (like JUL) or something similar.
I switch in the moment my ANT-Build-Environment pretty easy from JUL to your very cool TinyLog.

Thank you for that great tool and your work!

**Current properties file (example):**

tinylog.writer = file
tinylog.writer.filename = /tmp/JTemplate.log
tinylog.writer.format = [{level}] {line}:{class}.{method}()\t{message}

**That's a snippet from the JUL documents:**

    "/" the local pathname separator
    "%t" the system temporary directory
    "%h" the value of the "user.home" system property
    "%g" the generation number to distinguish rotated logs
    "%u" a unique number to resolve conflicts
    "%%" translates to a single percent sign "%"

**Comment by pmwmedia** [comment]
tinylog can handle environment variables "${name}" and "/" as path separator on any OS.

This works for me on Windows and Linux:

```
tinylog.writer = file
tinylog.writer.filename = ${tmp}/JTemplate.log
tinylog.writer.format = [{level}] {line}:{class}.{method}()\t{message}
```

**Comment by romanlinhard** [comment]
Thanks, that works very well!
