### ISSUE TITLE
Tinylog Writing-Thread 

### ISSUE THREAD

**Issue by ghost** [tinylog-org/tinylog#68]
Hey,

is it possible to use the Writing-Thread with the option to let the Thread end when no new logs are incoming, so when the Application crash the last Logs get written to the file ?

**Comment by pmwmedia** [comment]
If the JVM crashes, you will no longer be able to run any Java code. If your application only crashes due to an uncaught exception, the Writing-Thread should output all your log entries. Do you have a concrete example of losing log entries?
