### ISSUE TITLE
Limit number of stored log files to a given number

### ISSUE THREAD

**Issue by danieleformichelli** [tinylog-org/tinylog#69]
Hello,

I would like to use the DailyPolicy and only keep the logs of the last 7 days.
I have tried to set the backups property to the Logger configuration but it seems that old logs are never deleted.
Could you please clarify whether this is expected?
Could you please clarify if there is a way to obtain the desired behavior?

Regards,
Daniele

**Comment by pmwmedia** [comment]
Could you provide your configuration for tinylog?

**Comment by danieleformichelli** [comment]
Hello Martin,

I am trying to configure it via code:
Configurator.defaultConfig().writer(new RollingFileWriter(Paths.get("wrk",
"log.log").toString(), 7, new TimestampLabeler("yyyy.MM.dd"), new
DailyPolicy())).formatPattern("{date}
{message}").level(Level.DEBUG).activate()

Regards,
Daniele


Il dom 18 feb 2018, 23:58 Martin Winandy <notifications@github.com> ha
scritto:

**Comment by pmwmedia** [comment]
Hi Daniele,

I can reproduce it. There is a bug. I'm going to fix it tonight.

**Comment by pmwmedia** [comment]
I fixed it in [tinylog-1.3.3-rc-1](https://github.com/pmwmedia/tinylog/files/1737910/tinylog-1.3.3-rc-1.zip).

@danyf90 Could you test it, if it works for you, too?

**Comment by danieleformichelli** [comment]
Hello @pmwmedia ,

Thank you for your prompt reply.
It works for me, too.

**Comment by pmwmedia** [comment]
Hi Daniele,

Thank you for testing! Then I will release the final version 1.3.3 tonight.
