### ISSUE TITLE
TinyLog doesn't honor default log level

### ISSUE THREAD

**Issue by sahil-ramagiri** [tinylog-org/tinylog#698]
**Describe the bug**
I swear it was working before, but then the default logging level seems to be TRACE. It's not my environment, I tried to use online java compilers and I see its the same.

**To Reproduce**
1. https://onecompiler.com/java/426vjvt5q
2. No Environment variables or Vm arguments are used

Code:
``` java
import java.util.*;

import org.tinylog.Logger;

public class Main {
    public static void main(String[] args) {

      System.out.println("TraceEnabled= "+Logger.isTraceEnabled());
      Logger.trace("log on trace");

      System.out.println("DebugEnabled= "+Logger.isDebugEnabled());
      Logger.debug("log on debug");

  }
}
```

Expected:
```
TraceEnabled= false
DebugEnabled= false
```

Actual
```
TraceEnabled= true
2024-03-10 17:55:20 [main] Main.main()
TRACE: log on trace
DebugEnabled= true
2024-03-10 17:55:20 [main] Main.main()
DEBUG: log on debug
```

**Environment**
tinylog version: 2.7.0
Java version:

Example Screenshots:

![image](https://github.com/tinylog-org/tinylog/assets/45749746/66daf09b-0f0e-4a0d-a836-0c9484ca99de)

**Comment by pmwmedia** [comment]
In tinylog 2, all severity levels are enabled by default, including `trace` and `debug`. Therefore, the actual output is correct. If you want to disable both severity levels, you can set another default severity level: https://tinylog.org/v2/configuration/#severity-level
