### ISSUE TITLE
Can the log output of Logback and log4j2 be seamlessly migrated to tinylog for output?

### ISSUE THREAD

**Issue by WenTao-Love** [tinylog-org/tinylog#748]
Thanks!

**Comment by pmwmedia** [comment]
Yes, tinylog can receive log entries via SLF4J.

If you use Logback, you properly use SLF4J as logging API. So, you just have to remove the logback JARs and use [`slf4j-tinylog`](https://tinylog.org/v2/download/#slf4j-16--20) instead.

For log4j2, you have to use [`slf4j-tinylog`](https://tinylog.org/v2/download/#slf4j-16--20) together with [`log4j-to-slf4`](https://logging.apache.org/log4j/2.3.x/log4j-to-slf4j/).
