### ISSUE TITLE
Change logging level at runtime when writingthread = true

### ISSUE THREAD

**Issue by mhtocs** [tinylog-org/tinylog#755]
I am running some apps in Kubernetes and generally, whenever I encounter an issue and want to enable debug logging, I currently have to update the logging level in a file and restart the pod again. Is there a way to change the logging level if I update a system property or if tinylog.properties is changed?

I have writingthread set to true, so i am not sure if [this solution](https://github.com/tinylog-org/tinylog-reload-configuration-example/tree/master) will work or not. That example mentions that it will not work if writingthread is true ? can you explain why not?

**Comment by agentgt** [comment]
I think a useful feature that tinylog could copy that is in my logging framework is allowing certain logger names to change levels dynamically.

https://jstach.io/doc/rainbowgum/current/apidocs/#level_resolvers

Basically Rainbow Gum is static and immutable for all other loggers unless you specify it in config.

```
logging.global.change=true          # this is required to turn on level changing.
logging.change.com.mycompany=level  # only logger names starting with com.mycompany can have their levels changed.
```

Then if you did

```
logging.level.com.mycompany=INFO  # Was ERROR
logging.level.com.mycompany.anything=DEBUG # Was INFO
```

it would update the loggers similar to logback and log4j2 regardless of writers (and outputs).

**Comment by pmwmedia** [comment]
tinylog 2 is designed to use frozen logging configurations as these allow the JVM to detect disabled logging levels and to remove the corresponding log statement code completely. This is the reason why tinylog 2 has such a great performance: https://tinylog.org/v2/benchmark/#discarding-log-entries.

> I have writingthread set to true, so i am not sure if [this solution](https://github.com/tinylog-org/tinylog-reload-configuration-example/tree/master) will work or not. That example mentions that it will not work if writingthread is true ? can you explain why not?

The linked workaround solution uses refactoring to makes final fields mutable at runtime. Depending on your JVM, it is very likely that the writing thread will see the changes with a delay or even not at all. With newer JVMs, it can even happen that refactoring operations are blocked at all.

However, tinylog 3 will optionally support logging configuration changes at runtime out-of-the-box. And the logging API of tinylog 2 and 3 is source code compatible.
