### ISSUE TITLE
Documentation corrupted

### ISSUE THREAD

**Issue by Yjuq** [tinylog-org/tinylog#78]
Hey - It's look like the JavaDoc about the Logger class is damaged:
https://tinylog.org/javadoc/org/pmw/tinylog/Logger.html

And I have a feature request for your tinylog. What do you think about a option in the configuration file to filter a stacktrace. At the moment I filter (print only informations about special packages) the stacktrace extern in a own class before I give them to the Logger.

A other thing - If you imp!ement this, can you add a feature to hide the 'caused by' information from exceptions? Currently you just print the stacktrace and limit them with a option. That's not enought for me :D

**Comment by pmwmedia** [comment]
Thank you for your issue for the missing HTML page for the logger class! I have upload the Javadoc again and it should be complete now.

Your feature request is welcome :-) I have already thought about some advance features for removing nondescript stack trace elements. Could you create a separate issue for your feature request?
