### ISSUE TITLE
Cant get log naiming

### ISSUE THREAD

**Issue by davigre** [tinylog-org/tinylog#80]
I need the following log naming:

'logs\log2018_08_17_00.log'
'logs\log2018_08_17_01.log'
'logs\log2018_08_17_02.log'

with out 'rolling'. Never erase any file.

I try with tinylog.properties file:
`
tinylog.level = trace
tinylog.format = {date:yyyy-MM-dd HH:mm:ss} {level}:{message}

tinylog.writer = rollingfile
tinylog.writer.filename = logs/log.log
tinylog.writer.backups = 9999
tinylog.writer.label = timestamp: yyyy_MM_dd
tinylog.writer.policies = size: 1KB
`
How can I get the 'count' part ?

Thank you.

**Comment by pmwmedia** [comment]
tinylog 1.x supports only one label (count, timestamp or process ID). However tinylog 2.x will support multiple labels: https://tinylog.org/v2/configuration/#rolling-file-writer. The first milestone of tinylog 2.x is technical already finished. As soon as the new website is finished too, I will release it.
