### ISSUE TITLE
TinyLog 2.0.0-M2 not in Maven Central

### ISSUE THREAD

**Issue by mikehearn** [tinylog-org/tinylog#83]
I'd like to upgrade to TinyLog 2 but I need the SLF4J and JUL bridge support. The M2 release with this in didn't make it to Maven Central yet.

https://search.maven.org/search?q=g:org.tinylog%20AND%20a:tinylog-impl&core=gav

**Comment by pmwmedia** [comment]
I triggered the release again via https://oss.sonatype.org/.

**Comment by pmwmedia** [comment]
tinylog 2.0.0-M2 is available on Maven Central now: https://repo1.maven.org/maven2/org/tinylog/
