### ISSUE TITLE
Feature request: SLF4J 1.8 support

### ISSUE THREAD

**Issue by mikehearn** [tinylog-org/tinylog#85]
SLF4J 1.8 is compatible with the Java module system. The API is identical from a user's perspective, but from a provider perspective, it needs changes to use ServiceLoader to expose the provider instead of magic class names.

**Comment by pmwmedia** [comment]
Support for SLF4J 1.8 is planned for tinylog 1.3 and 2.0 as soon as it is stable. The current beta 2 of SLF4J 1.8 is still declared as experimental.

**Comment by pmwmedia** [comment]
SLF4J 1.8 seems to be dead as this version has been removed from the official download page: https://www.slf4j.org/download.html
