### ISSUE TITLE
Feature request: Micrometer metrics support

### ISSUE THREAD

**Issue by re-thc** [tinylog-org/tinylog#87]
Hi, can tinylog be integrated with Micrometer for metrics? Currently missing this to move from log4j2. Tinylog seems faster but doesn't have the metrics we use in reporting. Thanks!

**Comment by pmwmedia** [comment]
Micrometer seems to support SLF4J: https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/logging/LoggingMeterRegistry.java#L74

This means you would just have to add tinylog's SLF4J binding for outputting these metrics via tinylog.

**Comment by re-thc** [comment]
Hi, it's for collecting metrics from Tinylog and not outputting metrics to Tinylog. Not sure if that's the same, but see https://github.com/micrometer-metrics/micrometer/tree/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/logging where there's a logback and log4j2 implementation.

**Comment by pmwmedia** [comment]
Thank you! I got it. In this case, a tinylog binder should be added to Micrometer. According to the both existing logging binders, the implementation should be trivial. Have you tried to add a feature request or pull request there?

**Comment by re-thc** [comment]
Thanks, ok, if the request should go in Micrometer I'll create it there and see what happens. Cheers!

**Comment by pmwmedia** [comment]
https://github.com/micrometer-metrics/micrometer/issues/1171
