### ISSUE TITLE
Keep buffer of JdbcWriter after connection loss

### ISSUE THREAD

**Issue by re-thc** [tinylog-org/tinylog#91]
Hi, currently JDBCWriter will lose logs if a connection drops or before a connection is established.

Can a replay buffer be added to deal with these situations? i.e. check connection and reconnect if required, but do not "lose" these entries. Instead add it to a queue and write them again when connect is available.

**Comment by gabrielnasser** [comment]
Perhaps this could be done via the existing writing thread functionality by adding persistence to it? That way persistence can be enjoyed by any writer.

**Comment by re-thc** [comment]
There's a slight difference. If persistence happens across the board - where does this go? In a file or JDBC? Which becomes a circular problem. A global buffer would be good though - even for file so we can log before it opens.

I think slf4j does something similar with a substitute logger that gets initialized at the start and then swaps over once the real logger initializes.

**Comment by subinsoman** [comment]
can i try this?

**Comment by pmwmedia** [comment]
A pull request is welcome!

**Comment by pmwmedia** [comment]
Could be solved easily inside of [JdbcWriter.java](https://github.com/tinylog-org/tinylog/blob/v2.5/tinylog-impl/src/main/java/org/tinylog/writers/JdbcWriter.java)
