### ISSUE TITLE
Feature request: netty InternalLogger implementation

### ISSUE THREAD

**Issue by AlexanderBykin** [tinylog-org/tinylog#92]
Hi
There is should be `io.netty.util.internal.logging.InternalLogger` implementation to create `tinylog` factory for `netty` logging

**Comment by pmwmedia** [comment]
Would you be able to submit a pull request? However you can also use Slf4JLoggerFactory, if you use the SLF4J binding for tinylog 2.

**Comment by AlexanderBykin** [comment]
i haven't any implementation of this thing, will try to use SL4J binding
