### ISSUE TITLE
Overload resolution ambiguity

### ISSUE THREAD

**Issue by scott-rc** [tinylog-org/tinylog#94]
Hello :wave:

After upgrading from 1.3.6 -> 2.0.0-M3, I am getting a function ambiguity issue when invoking any of the log levels (info, warn, etc...) with a String as the only argument.

One of the ways to get around this is to cast the string to Any (Object in Kotlin) to give the compiler a hint.

![tinylog_ambiguity_error](https://user-images.githubusercontent.com/21965521/54325385-4686c280-45d8-11e9-93b8-918584c7029d.png)

This may not be a priority if Kotlin is not supported (or if this is intended behavior) - but I thought I'd share.

PS: I love the size, performance, and simplicity of this lib - keep up the great work! :+1:

**Comment by pmwmedia** [comment]
I will look at that. tinylog 2 should also be easy to use with Kotlin.

**Comment by pmwmedia** [comment]
After trying several things, I decided to provide a separate logging API for Kotlin, Scala and Groovy. This is the only way I can deal with the features and specialties of all three programming languages.

Here is a preview version for Kotlin: [tinylog-kotlin-2.0-SNAPSHOT.zip](https://github.com/pmwmedia/tinylog/files/2972864/tinylog-kotlin-2.0-SNAPSHOT.zip)

Some examples that are working now:

```kotlin
Logger.info("Hello World!")
Logger.info("Hello {}!", { "Mister" })
Logger.info { "Hello $name!" }
Logger.info(exception) { "Hello $name!" }
```

**Comment by danielwilson1702** [comment]
@pmwmedia can you think of a reason this might come up again, in a library project? I think I'm going insane :)

**Comment by pmwmedia** [comment]
@danielwilson1702 Which Kotlin and IntelliJ version are you using?

**Comment by danielwilson1702** [comment]
Sorry for the delay! Kotlin is 1.3.61 and IntelliJ is Android Studio 3.5.3 (actually can't tell how the hell to see a specific IntelliJ version). I think it must be something about marking the project as a library. Whilst the app module in the library project also throws the error, remote consumers of the library are fine.

Dependencies in the library gradle file are specified like so:
```
    api 'org.tinylog:tinylog-api-kotlin:2.0.1'
    api 'org.tinylog:tinylog-impl:2.0.1'
```

I will try and make a sample if it helps.

**Comment by danielwilson1702** [comment]
Ok I spent a little over an hour basically being an idiot, maybe someone else will run into this, you never know! It was confused a little by the fact that the lib consumer is a Java project, so while he uses `org.tinylog.Logger` without issue, my library project was also trying to use that when he should be using `org.tinylog.kotlin.Logger`. Now all my problems are gone (doh)
