### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by tebriz159** [tinylog-org/tinylog#95]
Hi, I'm a logo designer and I can design a free logo for your project. So ,what do you think?

**Comment by pmwmedia** [comment]
Wow! That sounds amazing :-) I would be happy to have a professional scalable logo for tinylog.

**Comment by tebriz159** [comment]
Hi, sorry for delay. I made a design for this project. If you like it I'll send you all files to use it.

![tinylogpr](https://user-images.githubusercontent.com/31902754/56435393-49688780-62e9-11e9-8ee6-a43ef3fd5d63.png)

Which color variation do you prefer?

![tinylogpr1](https://user-images.githubusercontent.com/31902754/56435410-4ec5d200-62e9-11e9-8697-6a62c6155578.png)

**Comment by pmwmedia** [comment]
Thank you very much for the great logo :-) I really love it!

I prefer the primary color #33AD00 from the [tinylog 2 website](https://tinylog.org/v2/), plus a second one with the light color #C8FFC1 for dark backgrounds.

Could your provide the logo also as SVG? It would simplify the use a lot for me.

**Comment by tebriz159** [comment]
Sure, I'll do it tomorrow.

**Comment by tebriz159** [comment]
I used the colors that you wanted, which variation do you want to use?

![tinylogpr2](https://user-images.githubusercontent.com/31902754/56919564-fbfece00-6ad1-11e9-8b3f-ba8e1c1e1b8b.png)

**Comment by pmwmedia** [comment]
Thank you very much for your efforts! I really like to see the new logo in tinylog's primary color :-) I would like to use both logos from the left side. The project preferred spelling is "tinylog" in lower case letters. Could you adapt this?
