### ISSUE TITLE
Logging doesn't run when using Java Web Start

### ISSUE THREAD

**Issue by gabrielnasser** [tinylog-org/tinylog#96]
Hello,

We have a single-jar application where we package all our classes and dependent classes from our jars (including tinylog-related classes) into a single archive. Using maven within Eclipse, everything runs fine and logging works as expected. The same goes for the runnable jar we produce. However, when we launch the jar via a JNLP file, logging doesn't work at all. 

We use the following dependencies

org.tinylog:tinylog-api:2.0.0-M3
org.tinylog:tinylog-impl:2.0.0-M3
org.tinylog:slf4j-tinylog:2.0.0-M3
org.slf4j:slf4j-api:1.7.25

What is confusing is that the output from the Java Web Start console prints the following message

LOGGER ERROR: No logging framework implementation found in classpath. Add tinylog-impl.jar for outputting log entries.

However, like I mentioned, the same referenced jar from the JNLP works standalone and clearly works. I even confirmed the presence of the manifest information and all seems fine. Further, I  confirmed a few things by printing some output to stderr, including the configuration being loaded correctly by printing the contents of the Configuration. All seems fine.

After inspecting the source code of tinylog, I tried to programmatically define the provider with the following snippet

Configuration.set("provider", "org.tinylog.core.TinylogLoggingProvider");

since i believe that is one of the ways for the ProviderRegistry to load the LoggingProvider. So, I ran the code once more and confirmed that the Configuration value exists and is set to the correct value. However, to my bafflement, the internal logger threw the following in the console:

LOGGER ERROR: Service implementation 'rolling file' not found

So my questions are:

1. Why is it not working with Web Start? What am I doing wrong?
2. Does a provider get loaded correctly when defined programmatically or via the configuration file?
3. Why does the internal logger try to load a provider incorrectly by retrieving the configuration of my "writer" property in the configuration file (or programmatically as I tried both approaches)?

Thank you

**Comment by pmwmedia** [comment]
I assume that Java Web Start does not provide the permissions for reading any files in META-INF by default. All logging providers, writers and policies are registered in a service file in META-INF.

Probably reading service files via `AccessController` could solve the problems with using tinylog in a Java Web Start application.

**Comment by pmwmedia** [comment]
I have created a test version that uses `AccessController`:

- [tinylog-2.0-SNAPSHOT.zip](https://github.com/pmwmedia/tinylog/files/2990436/tinylog-2.0-SNAPSHOT.zip)
- [slf4j-tinylog-2.0-SNAPSHOT.zip](https://github.com/pmwmedia/tinylog/files/2990437/slf4j-tinylog-2.0-SNAPSHOT.zip)

@gabrielnasser Could you test it?

**Comment by gabrielnasser** [comment]
Thank you for the quick turnaround. We tried that and it didn't work. The console displays the following message:

LOGGER WARN: No logging framework implementation found in classpath. Add tinylog-impl.jar for outputting log entries.

**Comment by gabrielnasser** [comment]
Attached a partial snippet of our JNLP file.
[example.txt](https://github.com/pmwmedia/tinylog/files/2991568/example.txt)

**Comment by pmwmedia** [comment]
I haven't worked with Java Web Start yet. @gabrielnasser Could you provide a minimal example project that I can use for testing and reproducing the issue?

**Comment by gabrielnasser** [comment]
@pmwmedia I'll try to get a sample project. In the meantime, I noticed that perhaps you may not be using the intended class loader in ServiceLoader? In the constructor, you have

`this.classLoader = Thread.currentThread().getContextClassLoader();`

whereas in loadClasses(), you're calling

`urls = ClassLoader.getSystemResources(name); // Abstract class`

Shouldn't it be the following instead?

`urls = classLoader.getSystemResources(name); //  Thread.currentThread().getContextClassLoader()`

If my understanding is correct, Java Web Start should work just fine if you use the thread's context class loader.

**Comment by pmwmedia** [comment]
I agree that `Thread.currentThread().getContextClassLoader()` should be always used. However, I don't know, if other changes has be applied to satisfy Java Web Start.

@gabrielnasser  Snapshot version that includes your suggested change:

- [tinylog-2.0-SNAPSHOT.zip](https://github.com/pmwmedia/tinylog/files/2994134/tinylog-2.0-SNAPSHOT.zip)
- [slf4j-tinylog-2.0-SNAPSHOT.zip](https://github.com/pmwmedia/tinylog/files/2994138/slf4j-tinylog-2.0-SNAPSHOT.zip)

**Comment by gabrielnasser** [comment]
@pmwmedia that worked! Looking forward to the next official build on maven :)

Thank you very much.
