### ISSUE TITLE
Unit test fails when building latest release

### ISSUE THREAD

**Issue by gabrielnasser** [tinylog-org/tinylog#98]
I have downloaded the latest release and when running 

`mvn clean install -P release`

the build consistently fails with the following output

`
[ERROR] Tests run: 24, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.808 s <<< FAILURE! - in org.tinylog.path.DynamicPathTest
[ERROR] getMultiTokenFiles(org.tinylog.path.DynamicPathTest)  Time elapsed: 0.014 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting:
  <[/var/folders/4y/0h2fbwbs7hg_12ltvff3g29m0000gn/T/junit4167999617599005228/2018_2.log,
    /var/folders/4y/0h2fbwbs7hg_12ltvff3g29m0000gn/T/junit4167999617599005228/2018+3.log,
    /var/folders/4y/0h2fbwbs7hg_12ltvff3g29m0000gn/T/junit4167999617599005228/2018_1.log]>
to contain exactly in any order:
  <[/var/folders/4y/0h2fbwbs7hg_12ltvff3g29m0000gn/T/junit4167999617599005228/2018_1.log,
    /var/folders/4y/0h2fbwbs7hg_12ltvff3g29m0000gn/T/junit4167999617599005228/2018_2.log]>
but the following elements were unexpected:
  <[/var/folders/4y/0h2fbwbs7hg_12ltvff3g29m0000gn/T/junit4167999617599005228/2018+3.log]>

	at org.tinylog.path.DynamicPathTest.getMultiTokenFiles(DynamicPathTest.java:224)
`

Environment information:

Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: /usr/local/Cellar/maven/3.6.0/libexec
Java version: 9.0.4, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.3", arch: "x86_64", family: "mac"

**Comment by pmwmedia** [comment]
Which operating system are you using? All JUnit tests run consistently on the Linux build server (https://travis-ci.org/pmwmedia/tinylog/builds/510059156) as well as on my private Windows 10 machine. What JDK are you using?

Could you debug the test `org.tinylog.path.DynamicPathTest.getMultiTokenFiles()`? For analyzing why this test fails on your machine, I would be helpful to know what are the values of the variables `folder` and `files` in `org.tinylog.path.DynamicPath.collectFiles()` and the value of the field `plainTexts`.

**Comment by pmwmedia** [comment]
@gabrielnasser I have found the cause why this test failed on your machine. The reason is the underscore in your path. I will fix the index in `org.tinylog.path.DynamicPath.collectFiles()`.

**Comment by gabrielnasser** [comment]
For good measure, I'll add the environment info to the original comment.

**Comment by gabrielnasser** [comment]
I also confirm the build passes with this fix. Thank you.
