### ISSUE TITLE
Configuring Logcat for Android

### ISSUE THREAD

**Issue by mailz** [tinylog-org/tinylog#99]
There is information about configuring TAG for Logcat in the documentation for tinylog 2.0:

> The tag is configurable, and any format pattern can be used.
> writer.tag = {tag}  # optional, default: {class-name}

But it doesn't work.

ConfigurationParser has method `createWriters` with code:

`public static Collection<Writer>[][] createWriters(final List<String> tags, final Level minimumLevel, final boolean writingThread) {`
...
`configuration.remove("tag");`
`configuration.remove("level");`
...
`}`

which removes `tag` and you can't set another tag pattern

**Comment by pmwmedia** [comment]
The tag property of the logcat writer collides with the new support of tagged log entries. I'm going to rename the property to `tagname` for the logcat writer.

**Comment by mailz** [comment]
It's great, thank you!
